import json, collections

PATH = "content/java-backend-fresher/debugging-logging/log-levels/complete-qa.json"
d = json.load(open(PATH))
qs = d["questions"]
U = {}

def S(t, title, content):
    return {"type": t, "title": title, "content": content}

# ---- 001 ----
U["jbf-debug-log-levels-001"] = dict(
    layout_type="concept-explainer",
    direct_answer="Java logging has **five severity levels**, from least to most severe: **TRACE**, **DEBUG**, **INFO**, **WARN**, **ERROR**. The configured level is a **threshold** — set INFO and you see INFO, WARN, and ERROR but not DEBUG or TRACE. TRACE/DEBUG are development diagnostics, INFO is business events, WARN is recoverable surprises, ERROR is real failures.",
    interviewer_intent={
        "testing": "Whether you know the five levels in the correct severity order AND understand that a level is an inclusive threshold, not a single filter.",
        "common_mistake": "Listing the names but saying 'INFO shows only INFO' or reversing the order so ERROR looks more verbose than DEBUG.",
        "to_stand_out": "Tie each level to a production decision: INFO for the business narrative, WARN for handled surprises, ERROR for things that page on-call, and note that framework loggers usually run at WARN while your app runs at INFO.",
    },
    sections=[
        S("overview", "The Five Java Log Levels",
          "Log levels are **severity filters** for your application's output. Java's logging APIs (SLF4J, Logback, Log4j2, `java.util.logging`) all share the same idea: every log statement is tagged with a level, and the logger only emits statements at or above the configured **threshold**.\n\nFrom least to most severe the five standard levels are **TRACE**, **DEBUG**, **INFO**, **WARN**, **ERROR**. The key fresher insight: the level you configure is a *minimum*, not an exact match. Setting INFO means \"INFO and everything more severe\" — so INFO, WARN, and ERROR all appear, while DEBUG and TRACE are suppressed. This lets you turn verbosity up or down with one setting and no code change."),
        S("concept_map", "Five Levels at a Glance",
          "cyan|TRACE|~Finest detail|method entry/exit|almost never in prod|noisiest level\nblue|DEBUG|~Dev diagnostics|SQL, variable values|off in production|for developers only\nemerald|INFO|~Business events|order placed, user registered|default prod level|the app's narrative\namber|WARN|~Handled surprise|retry, fallback used|reviewed, not paged|degraded but working\nrose|ERROR|~Real failure|DB down, unhandled exception|pages on-call|operation failed"),
        S("comparison_table", "What Each Level Is For",
          "| Level | Meaning | Example | On in production? |\n|---|---|---|---|\n| **TRACE** | Finest-grained tracing | `Entering processOrder(42)` | No |\n| **DEBUG** | Development diagnostics | `Fetched 3 rows for orderId=42` | No |\n| **INFO** | Significant business event | `Order 42 placed for customer 7` | Yes |\n| **WARN** | Unexpected but handled | `Config missing, using default timeout` | Yes |\n| **ERROR** | Failure that stopped the operation | `Payment gateway timeout for order 42` | Yes |\n\nSeverity order: `TRACE < DEBUG < INFO < WARN < ERROR`. The threshold includes everything to its right."),
        S("code_example", "Using Each Level with SLF4J",
          "```java\nimport org.slf4j.Logger;\nimport org.slf4j.LoggerFactory;\n\npublic class OrderService {\n    // One logger per class, named after the class\n    private static final Logger log = LoggerFactory.getLogger(OrderService.class);\n\n    public void processOrder(long orderId) {\n        log.trace(\"Entering processOrder, orderId={}\", orderId);   // finest detail\n        log.debug(\"Loading order from DB, orderId={}\", orderId);    // dev diagnostics\n        Order order = findOrder(orderId);\n        log.info(\"Processing order {} for customer {}\", orderId, order.customerId()); // business event\n        if (order.total() > 10_000) {\n            log.warn(\"Large order {} exceeds threshold: {}\", orderId, order.total()); // handled surprise\n        }\n        try {\n            charge(order);\n        } catch (PaymentException e) {\n            log.error(\"Payment failed for order {}\", orderId, e); // real failure + stack trace\n            throw e;\n        }\n    }\n}\n```\n\nWith the logger set to INFO, the `trace` and `debug` lines never print — but the same code shows them the moment you lower the threshold to DEBUG."),
        S("common_mistakes", "Common Mistakes",
          "- **Treating levels as independent**: thinking INFO shows only INFO. It's a threshold — INFO also shows WARN and ERROR.\n- **Reversing the order**: assuming ERROR is verbose. ERROR is the *least* verbose; it shows the fewest messages.\n- **Logging everything at one level**: putting framework loggers and your app at the same level, so either you drown in Spring/Hibernate noise or miss your own business events."),
        S("key_points", "Key Points",
          "- **Five levels**: TRACE < DEBUG < INFO < WARN < ERROR (least to most severe).\n- **Threshold, not filter**: setting INFO shows INFO, WARN, and ERROR; hides DEBUG and TRACE.\n- **TRACE/DEBUG** = developer diagnostics, off in production.\n- **INFO** = business narrative; **WARN** = handled surprise; **ERROR** = failure that pages on-call.\n- **Production pattern**: framework loggers at WARN, your application at INFO."),
        S("speakable_answer", "How to Answer This Verbally",
          "Java logging has five standard levels, and the order matters: from least to most severe they're TRACE, DEBUG, INFO, WARN, and ERROR. The thing most freshers get wrong is thinking the level you set is an exact filter. It isn't — it's a threshold. If I set my logger to INFO, I see INFO and everything more severe, so INFO, WARN, and ERROR all show up, but DEBUG and TRACE get filtered out. Let me walk through what each one is for. TRACE is the finest detail, like method entry and exit — you almost never turn it on, even in development. DEBUG is for developer diagnostics, like the SQL that just ran or the value of a variable; it's on locally and off in production. INFO is the business narrative — an order was placed, a user registered, a job finished. That's what you keep on in production. WARN is for something unexpected that you handled gracefully, like falling back to a default config or a retry that eventually succeeded — worth noticing, but the app kept working. ERROR is a real failure, like the database being down or an unhandled exception — that's the kind of thing that should page someone. A detail that makes you sound experienced: in production you usually set framework loggers like Spring or Hibernate to WARN so they stay quiet, and keep your own application code at INFO so you can actually follow what it's doing."),
    ],
    hook="Most people can list the five level names — the real test is knowing a level is a threshold, so INFO quietly includes WARN and ERROR too.",
)

# ---- 002 ----
U["jbf-debug-log-levels-002"] = dict(
    layout_type="recipe-builder",
    direct_answer="Pick the level by asking **who needs to see this, and how urgently**. **ERROR** = an operation failed and someone should act now. **WARN** = unexpected but handled (retry, fallback). **INFO** = a normal business event worth keeping in production. **DEBUG** = developer-only diagnostics. The classic trap: logging expected exceptions like validation failures at ERROR, which creates alert fatigue.",
    interviewer_intent={
        "testing": "Practical judgment — can you map a real situation to the right level instead of defaulting everything to ERROR or DEBUG.",
        "common_mistake": "Logging every caught exception at ERROR, including expected ones like a declined card or invalid input, so real failures drown in noise.",
        "to_stand_out": "Distinguish expected business exceptions (user typo, declined card) from genuine system failures, and mention alert fatigue as the operational cost of over-using ERROR.",
    },
    sections=[
        S("overview", "A Decision Framework for Log Levels",
          "Choosing a level comes down to one question: **who needs to see this message, and when?** If on-call should be paged at 3 AM, it's **ERROR**. If it should be reviewed during business hours, it's **WARN**. If it describes normal business flow, it's **INFO**. If only a developer debugging locally needs it, it's **DEBUG**.\n\nThe distinction freshers miss is **expected vs unexpected**. A user entering an invalid email is expected — that's not an ERROR. A database connection dropping is unexpected — that is. Your level choice directly shapes alert quality and on-call sanity."),
        S("flow_diagram", "Picking the Level",
          "```mermaid\nflowchart TB\n    A[New log statement] --> B{Did the operation<br/>fail to complete?}\n    B -->|Yes, system fault| C[ERROR<br/>pages on-call]\n    B -->|No, but handled<br/>a surprise| D[WARN]\n    B -->|No, normal flow| E{Useful in<br/>production?}\n    E -->|Yes, business event| F[INFO]\n    E -->|No, dev diagnostics| G[DEBUG]\n```"),
        S("step", "Step 1 — Did the Operation Fail?",
          "Ask whether the situation stopped the caller's request from completing.\n\n| Situation | Failed? | Level |\n|---|---|---|\n| Payment gateway is down | Yes, system fault | ERROR |\n| Card declined by bank | No, user retries | INFO/DEBUG |\n| Retry succeeded after one timeout | No, handled | WARN |\n| Order saved successfully | No, normal | INFO |\n\nIf you are catching an exception, ask: is this something I *anticipated* in business logic, or a genuine system problem?"),
        S("code_example", "Step 2 — Match the Audience to the Level",
          "```java\ntry {\n    paymentGateway.charge(order);\n} catch (CardDeclinedException e) {\n    // Expected business outcome — the user will try another card\n    log.info(\"Card declined for order {}: {}\", order.id(), e.reasonCode());\n} catch (GatewayTimeoutException e) {\n    // Unexpected but we recovered via retry\n    log.warn(\"Gateway slow for order {}, retrying\", order.id());\n} catch (GatewayDownException e) {\n    // System failure — the order cannot be placed\n    log.error(\"Payment gateway unavailable for order {}\", order.id(), e);\n    throw e;\n}\n```\n\nThree exceptions, three very different levels — because the *consequence* differs, not because they are all 'errors'."),
        S("common_mistakes", "Common Mistakes",
          "- **Every exception is ERROR**: catching a validation or authentication failure and logging it at ERROR, paging people for normal user behavior.\n- **Detail at INFO**: putting cache hits or query timings at INFO, making production logs unreadable. That's DEBUG.\n- **Choosing for local dev**: picking levels by what's convenient on your laptop instead of what production observability needs."),
        S("key_points", "Key Points",
          "- **ERROR** = operation failed, needs action now (pages on-call).\n- **WARN** = unexpected but handled (retry, fallback, soft limit).\n- **INFO** = normal business event worth keeping in production.\n- **DEBUG** = developer diagnostics, off in production.\n- **Expected ≠ ERROR**: invalid input and declined cards are normal, not failures.\n- **Over-using ERROR causes alert fatigue** — real failures get ignored."),
        S("speakable_answer", "How to Answer This Verbally",
          "When I add a log statement, I decide the level by asking who needs to see this and how urgently. My first question is: did this situation actually stop the operation from completing? If the database is down and I can't save an order, that's ERROR, because the operation failed and someone needs to act. But if a user typed an invalid email and validation caught it, that's not an error at all — that's expected behavior, so it's INFO or even DEBUG. The user will just fix it and resubmit. My second question is about production visibility. Significant business events like an order being placed or a user registering go at INFO, because that's the narrative operations teams follow. Something unexpected that I handled — say I retried a slow call and it eventually worked, or I fell back to a default config — that's WARN. It's worth noticing, but the app kept working. Anything that's purely developer diagnostics, like the exact SQL or a cache hit, goes at DEBUG and stays off in production. The biggest mistake I see freshers make is logging every caught exception at ERROR. Not every exception is a failure. A declined card or a wrong password is normal user behavior. If you log those at ERROR, you get alerts constantly, and that's alert fatigue — eventually people ignore the alerts, and when a real database outage happens, it gets missed in the noise. So my rule is simple: ERROR for things that broke and need attention, WARN for handled surprises, INFO for normal business activity, DEBUG for developer detail."),
    ],
    hook="The trick to picking a log level isn't the definitions — it's separating a real failure from a user simply doing something you already planned for.",
)

# ---- 003 ----
U["jbf-debug-log-levels-003"] = dict(
    layout_type="recipe-builder",
    direct_answer="In Spring Boot you set per-package levels in **application.properties** (or YAML) with the `logging.level.<package>` prefix. Keep `logging.level.root=INFO` as a safe default, then raise just your own code with `logging.level.com.myapp=DEBUG`. You can target a single class, suppress framework noise, and even change levels at runtime via **Spring Boot Actuator** without a restart.",
    interviewer_intent={
        "testing": "Whether you know the concrete Spring Boot mechanism (logging.level.<package>) and the root-vs-package strategy, not just that 'you can configure logging'.",
        "common_mistake": "Setting the root logger to DEBUG to debug your own code, which floods logs with Spring, Hibernate, and Tomcat internals.",
        "to_stand_out": "Mention the Actuator /loggers endpoint for changing a level live during an incident, plus per-profile config for dev vs prod.",
    },
    sections=[
        S("overview", "Per-Package Logging in Spring Boot",
          "Different parts of an app need different verbosity. Framework code (Spring, Hibernate, Tomcat) emits huge amounts of DEBUG that would bury your own logs, so you keep the **root logger** conservative and selectively raise your own packages.\n\nSpring Boot reads this from **application.properties** / **application.yml** using the `logging.level` prefix. Logger names follow the Java package hierarchy, so `logging.level.com.myapp` controls every class under that package — surgical control with zero code changes."),
        S("concept_map", "Where Levels Are Set",
          "blue|root logger|~Default for everything|logging.level.root=INFO|covers all libraries|keep it conservative\nemerald|your package|~Your own code|logging.level.com.app=DEBUG|raise while investigating|children inherit\namber|single class|~Targeted deep dive|logging.level.com.app.X=TRACE|one class only|finest control\nviolet|runtime|~No restart|Actuator /loggers POST|flip during incident|set back after"),
        S("code_example", "Step 1 — Set a Safe Root, Then Raise Your Package",
          "```properties\n# application.properties\n# Conservative default for ALL loggers (including libraries)\nlogging.level.root=INFO\n\n# Your own code, more verbose while investigating\nlogging.level.com.bookstore=DEBUG\n\n# A single noisy/important class\nlogging.level.com.bookstore.order.OrderService=TRACE\n\n# Quiet the framework\nlogging.level.org.springframework.web=WARN\nlogging.level.org.hibernate.SQL=WARN\n```\n\nChild loggers inherit the parent's level unless overridden, so one package line covers all its subpackages."),
        S("step", "Step 2 — YAML and Per-Environment Profiles",
          "```yaml\n# application-dev.yml  (active with spring.profiles.active=dev)\nlogging:\n  level:\n    root: INFO\n    com.bookstore: DEBUG\n    org.springframework: WARN\n```\n\nUse `application-dev.yml`, `application-prod.yml` profiles so dev can run DEBUG while production stays at INFO/WARN — no manual edits at deploy time."),
        S("step", "Step 3 — Change Levels at Runtime with Actuator",
          "```bash\n# Requires the actuator dependency and the loggers endpoint exposed\ncurl -X POST http://localhost:8080/actuator/loggers/com.bookstore.order \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"configuredLevel\": \"DEBUG\"}'\n```\n\nDuring an incident you can switch a package to DEBUG, reproduce the issue, then set it back — all without restarting or redeploying."),
        S("common_mistakes", "Common Mistakes",
          "- **`logging.level.root=DEBUG`**: turns on DEBUG for every dependency, producing thousands of framework lines that bury your own logs.\n- **Committing DEBUG to prod**: leaving your package at DEBUG after local troubleshooting, hurting performance and inflating log storage bills.\n- **One properties file for all envs**: not using profiles, so you can't have different levels per environment without editing files."),
        S("key_points", "Key Points",
          "- **`logging.level.<package>=LEVEL`** in application.properties/yml controls a package and its children.\n- **Keep `root=INFO`**, raise only your own packages — never set root to DEBUG.\n- **Target a single class** with its fully-qualified name.\n- **Profiles** (`application-{profile}`) keep dev verbose and prod quiet.\n- **Actuator `/actuator/loggers`** changes levels at runtime, no restart."),
        S("speakable_answer", "How to Answer This Verbally",
          "In Spring Boot you configure different log levels per package in application.properties or application.yml using the logging.level prefix. The strategy is to keep the root logger at a conservative level like INFO, and then raise just the packages you care about. So I'd set logging.level.root equals INFO as the baseline for everything, including all the libraries, and then add logging.level.com.mycompany.myapp equals DEBUG to get detailed logging only for my own code. The logger name matches the Java package structure, so that line covers every class in that package and its subpackages, and child packages inherit the parent's level unless I override them. I can go even more granular and set a single class, like logging.level.com.myapp.OrderService equals TRACE, for a targeted deep dive. A common pattern is quieting the framework by setting org.springframework and org.hibernate to WARN, because their DEBUG output is overwhelming. The reason you don't just set root to DEBUG is that it switches on DEBUG for Spring, Hibernate, Tomcat, everything — thousands of lines per request that bury your own logs. For different environments I'd use Spring profiles, so application-dev has DEBUG and application-prod stays at INFO. The thing that really stands out to interviewers is mentioning Spring Boot Actuator. If Actuator is enabled, you can change a log level at runtime with a POST to the slash actuator slash loggers endpoint — no restart needed. During a production incident that's genuinely useful: flip a package to DEBUG, reproduce the bug, then flip it back."),
    ],
    hook="The secret to readable Spring Boot logs is one rule — keep the root logger quiet and only turn the volume up on your own package.",
)

# ---- 004 ----
U["jbf-debug-log-levels-004"] = dict(
    layout_type="concept-explainer",
    direct_answer="The log level hierarchy is **inclusive**: the configured level is a minimum threshold, so it shows that level and everything more severe. Setting **INFO** shows INFO, WARN, and ERROR while suppressing DEBUG and TRACE. Loggers also inherit: a child package logger uses its parent's level unless explicitly overridden.",
    interviewer_intent={
        "testing": "Whether you understand level filtering as an inclusive threshold and know about logger (package) inheritance.",
        "common_mistake": "Believing INFO shows only INFO, or getting the severity direction backwards so ERROR seems to show more output.",
        "to_stand_out": "Explain logger inheritance through the package hierarchy and note that guarded/parameterized logging avoids the cost of suppressed statements.",
    },
    sections=[
        S("overview", "How the Threshold Works",
          "The level hierarchy is an **inclusive filter**. When you set a logger to INFO, you're saying \"show me INFO and anything more severe than INFO\" — so INFO, WARN, and ERROR appear, while DEBUG and TRACE are dropped.\n\nThe five levels in increasing severity are `TRACE < DEBUG < INFO < WARN < ERROR`. Setting any level lets that level and everything to its right pass. Lower the threshold to see more detail; raise it to see only the serious stuff."),
        S("concept_map", "Threshold Behaviour",
          "blue|Set DEBUG|~Very verbose|DEBUG, INFO, WARN, ERROR|TRACE hidden|local development\nemerald|Set INFO|~Production default|INFO, WARN, ERROR|DEBUG/TRACE hidden|business + problems\namber|Set WARN|~Quiet|WARN, ERROR only|INFO hidden|just the surprises\nrose|Set ERROR|~Silent|ERROR only|everything else hidden|failures only"),
        S("code_example", "Same Code, Different Thresholds",
          "```java\nlog.trace(\"entry: registerCustomer({})\", email); // shown only at TRACE\nlog.debug(\"validating email {}\", email);          // shown at DEBUG and below threshold\nlog.info(\"registering customer {}\", email);        // shown at INFO, WARN... no, at INFO threshold\nlog.warn(\"duplicate attempt for {}\", email);       // shown at INFO and WARN thresholds\nlog.error(\"failed to save {}\", email);             // shown at every threshold up to ERROR\n```\n\n```properties\n# logging.level.com.example=INFO\n#   -> trace + debug are suppressed\n#   -> info, warn, error all print\n```\n\nNothing in the code changes; only the configured threshold decides what reaches the output."),
        S("comparison_table", "What Each Setting Shows",
          "| Configured level | Messages emitted |\n|---|---|\n| TRACE | TRACE, DEBUG, INFO, WARN, ERROR |\n| DEBUG | DEBUG, INFO, WARN, ERROR |\n| INFO | INFO, WARN, ERROR |\n| WARN | WARN, ERROR |\n| ERROR | ERROR only |\n\nThe lower (more verbose) the level, the more rows you get."),
        S("common_mistakes", "Common Mistakes",
          "- **Exclusive thinking**: expecting INFO to show only INFO, then being confused that WARN/ERROR still appear.\n- **Inheritance surprise**: assuming setting `com.app` to DEBUG also lowers `com.app.sub` when that subpackage is explicitly set to INFO — explicit settings win.\n- **Backwards severity**: thinking ERROR is the most verbose; it's the least."),
        S("key_points", "Key Points",
          "- **Inclusive threshold**: a level shows itself and all more-severe levels.\n- **Order**: TRACE < DEBUG < INFO < WARN < ERROR.\n- **INFO** in prod shows business events plus WARN/ERROR; hides DEBUG/TRACE.\n- **Logger inheritance**: child packages inherit the parent level unless overridden.\n- **Use parameterized logging** (`{}`) so suppressed statements stay cheap."),
        S("speakable_answer", "How to Answer This Verbally",
          "The log level hierarchy works inclusively, not exclusively. When you set a logger to INFO, you're not saying show me only INFO messages — you're saying show me INFO and everything more severe than INFO. So INFO, WARN, and ERROR all appear, while DEBUG and TRACE get filtered out. The five levels from least to most severe are TRACE, DEBUG, INFO, WARN, and ERROR. Think of the configured level as a minimum threshold: everything at that level or higher in severity passes through. So if you set WARN, you only see WARN and ERROR. If you set ERROR, you only see ERROR. And if you set DEBUG, you see everything except TRACE. This is what makes logging configuration so flexible — you control verbosity with a single setting and no code change. The hierarchy also applies to loggers themselves, through your package structure. If I set com.example to INFO but never configure com.example.payment, that subpackage inherits INFO from its parent. But if I explicitly set com.example.payment to DEBUG, that explicit setting wins for just that package. Two mistakes freshers make: first, thinking INFO literally means only INFO, then being confused when WARN and ERROR still show up. Second, getting the direction backwards — ERROR is more severe than DEBUG, so setting ERROR gives you fewer messages, not more. One more practical note: use parameterized logging with curly-brace placeholders, so that even the suppressed debug statements don't waste time building strings that never get printed."),
    ],
    hook="If you've ever set a logger to INFO and wondered why WARN messages still showed up, the answer is that a level is a floor, not an exact match.",
)

# ---- 005 ----
U["jbf-debug-log-levels-005"] = dict(
    layout_type="concept-explainer",
    direct_answer="**Too much logging** buries the signal in noise, costs CPU/disk I/O, inflates storage bills, and — worst of all — causes **alert fatigue** when everything is ERROR. **Too little logging** leaves you blind: you can't reconstruct what happened during an incident. The goal is **intentional, leveled logging** with business context, not logging everything 'just in case'.",
    interviewer_intent={
        "testing": "Whether you see logging as having real costs and trade-offs, not as a free 'more is better' activity.",
        "common_mistake": "Discussing only one extreme, or assuming logging is costless so adding more is always safe.",
        "to_stand_out": "Name alert fatigue specifically and mention concrete costs — I/O, cloud log ingestion bills, and the inability to diagnose without business identifiers in logs.",
    },
    sections=[
        S("overview", "The Logging Balance Problem",
          "Logging is a balance: too much is as harmful as too little. **Over-logging** creates a signal-to-noise problem — a critical ERROR hides among thousands of DEBUG lines — and it has real costs: disk I/O, network bandwidth to ship logs, storage/retention bills, and CPU to format messages. **Under-logging** leaves you flying blind: when a customer reports a failure, you can't reconstruct what happened.\n\nThe target is **intentional logging**: business events at INFO, surprises at WARN, failures at ERROR, DEBUG off unless actively troubleshooting — with identifiers (order ID, user ID) so events can be correlated."),
        S("concept_map", "Two Failure Modes",
          "rose|Too Much|~Signal lost in noise|I/O + CPU cost|cloud ingestion bills|alert fatigue\nemerald|Just Right|~Leveled + contextual|INFO business events|IDs for correlation|DEBUG off by default\namber|Too Little|~Flying blind|can't diagnose incidents|no audit trail|redeploy just to add logs"),
        S("tradeoffs", "Weighing the Two Extremes",
          "**Too much**: log files grow to gigabytes/day and become unsearchable. Disk I/O can saturate and slow the whole app. Cloud logging (CloudWatch, Datadog) bills by volume, so verbose DEBUG in prod adds real money. And logging every caught exception at ERROR pages on-call for routine events — **alert fatigue** — so real failures get ignored.\n\n**Too little**: a customer says their payment failed, but you only logged successes — now you can't tell if it was a timeout, a validation error, or a DB outage. Post-incident reviews become guesswork, security incidents can't be traced, and you end up redeploying just to add logging while customers are affected."),
        S("code_example", "Noise vs Signal",
          "```java\n// Noise: logs every iteration at INFO, no context\nfor (Item i : cart.items()) {\n    log.info(\"processing item\"); // floods logs, says nothing useful\n}\n\n// Signal: one leveled, contextual line per meaningful event\nlog.debug(\"Pricing {} items for cart {}\", cart.size(), cart.id()); // dev detail\nlog.info(\"Order {} placed: {} items, total {}\",\n         order.id(), order.size(), order.total());                 // business event w/ IDs\n```\n\nThe second style is searchable, correlatable by `order.id()`, and stays quiet at production INFO level."),
        S("common_mistakes", "Common Mistakes",
          "- **Logging every variable**: leaving debug-everything statements in production code, treating logging as free.\n- **ERROR overuse**: logging expected exceptions at ERROR, creating alert storms and desensitizing the team.\n- **No business context**: logging 'operation failed' with no order ID or user ID, so the line is useless during an incident."),
        S("key_points", "Key Points",
          "- **Over-logging** = noise + I/O cost + storage bills + alert fatigue.\n- **Under-logging** = blind during incidents, forced redeploys to add logs.\n- **Logging isn't free**: CPU to format, I/O to write, network to ship, money to store.\n- **Add identifiers** (order/user/request ID) so events correlate.\n- **Right-size**: INFO for events, WARN for surprises, ERROR for failures, DEBUG off by default."),
        S("speakable_answer", "How to Answer This Verbally",
          "Logging too much and too little both cause serious problems, just different ones. Start with too much. The immediate issue is noise — if you log every method call and every variable at DEBUG in production, the logs become unreadable, and when a real error happens it's buried in thousands of routine lines. There's also a performance cost, because writing logs is disk I/O and disk is slow; at high volume you can actually saturate I/O and slow the whole application down. Then there's money — cloud logging services charge by data volume, so shipping verbose DEBUG logs to something like CloudWatch or Datadog can add real cost to the monthly bill. But the worst consequence is alert fatigue: if you log every caught exception at ERROR, including things like validation failures, your on-call team gets paged constantly, they start ignoring alerts, and a genuine database outage gets missed. On the flip side, too little logging leaves you blind. If a customer says their payment failed but you only logged successful payments, you have no idea what went wrong — was it a timeout, a validation error, a database failure? You end up deploying new code just to add logging, which stretches incident resolution from minutes to hours while customers are affected. The right balance is intentional logging: business events at INFO, handled surprises at WARN, real failures at ERROR, and DEBUG off in production unless you're actively troubleshooting. And always include context like order IDs and user IDs so you can correlate events. The thing that impresses interviewers is acknowledging that logging has real costs — CPU to format, I/O to write, network to ship, storage to keep. Treating it as expensive makes you more deliberate about what you log."),
    ],
    hook="Logging feels free, so people add more and more — until a real outage hides inside a million harmless lines and nobody notices.",
)

# ---- 006 ----
U["jbf-debug-log-levels-006"] = dict(
    layout_type="comparison-arena",
    direct_answer="`System.out.println` has **no log levels** (can't filter), **no timestamps** (can't correlate), **no logger name/context**, **no per-environment configuration**, and writes to stdout which may not be captured in production. A logging framework like **SLF4J + Logback** (the Spring Boot default) gives all of that for the same effort — `log.info(...)` instead of `System.out.println(...)`.",
    interviewer_intent={
        "testing": "Whether you can give concrete technical reasons println fails in production, not just 'use a logger because it's professional'.",
        "common_mistake": "Thinking println is fine because it works on your laptop and shows output instantly.",
        "to_stand_out": "List several concrete gaps (levels, timestamps, context, config, routing) and name SLF4J + Logback as the Spring Boot default replacement.",
    },
    sections=[
        S("overview", "Why println Fails in Production",
          "`System.out.println` is tempting because it needs zero setup. But it lacks everything production observability requires: no **levels** to filter by severity, no **timestamps** to build a timeline, no **logger name** to know which class spoke, no **structured format** for log tools, and **no per-environment config** — the debug print you forgot will spam production. It also writes to standard output, which in a container or service manager may go nowhere you can read.\n\nA logging framework — **SLF4J** with **Logback** (Spring Boot's default) — solves all of this and is just as easy to call."),
        S("concept_map", "What a Framework Adds Over println",
          "rose|System.out.println|~Console only|no levels|no timestamps|vanishes in containers\nemerald|SLF4J + Logback|~Production-ready|levels + timestamps|class name + MDC|files, JSON, remote\nblue|Same effort|~log.info(...)|one logger per class|config, not code|Spring Boot default"),
        S("comparison_table", "println vs a Logging Framework",
          "| Capability | System.out.println | SLF4J + Logback |\n|---|---|---|\n| Severity levels | None | TRACE → ERROR |\n| Timestamps | No | Automatic |\n| Logger/class name | No | Automatic |\n| Per-env configuration | No (edit + redeploy) | Properties/XML, no code change |\n| Output routing (file, JSON, remote) | stdout only | Appenders |\n| Stack traces | Manual | `log.error(msg, e)` |\n| Effort to use | `System.out.println(...)` | `log.info(...)` |"),
        S("before_code", "Without a Framework — println",
          "```java\npublic void processPayment(long orderId, double amount) {\n    System.out.println(\"Processing payment for order: \" + orderId);\n    // No timestamp, no level, no class name, can't be disabled in prod\n    try {\n        charge(amount);\n        System.out.println(\"Payment successful\"); // no context\n    } catch (PaymentException e) {\n        System.out.println(\"ERROR: payment failed\"); // loses the stack trace\n    }\n}\n```"),
        S("after_code", "With SLF4J — Levels, Timestamps, Context",
          "```java\nimport org.slf4j.Logger;\nimport org.slf4j.LoggerFactory;\n\npublic class PaymentService {\n    private static final Logger log = LoggerFactory.getLogger(PaymentService.class);\n\n    public void processPayment(long orderId, double amount) {\n        log.info(\"Processing payment for orderId={}, amount={}\", orderId, amount);\n        try {\n            charge(amount);\n            log.info(\"Payment completed for orderId={}\", orderId);\n        } catch (PaymentException e) {\n            log.error(\"Payment failed for orderId={}\", orderId, e); // full stack trace\n        }\n    }\n}\n// Output: 2026-06-04 10:23:45.123 INFO  [PaymentService] Processing payment for orderId=42, amount=99.99\n```\n\nSame number of lines, but now you can filter by level, correlate by timestamp, see the class, and disable it in production with one config line."),
        S("when_to_use", "When println Is Actually OK",
          "`System.out.println` is fine for **throwaway local experiments**, **learning exercises** following a tutorial, or **CLI tools** whose job is to print to the console (a migration script showing progress). The moment code leaves your laptop — code review, CI, staging, production — replace it with a logger. Even locally, using a logger from the start saves you from a find-and-replace later."),
        S("key_points", "Key Points",
          "- **No levels**: can't separate debug from errors or filter in production.\n- **No timestamps / class name**: can't build a timeline or locate the source.\n- **Not configurable**: changing behavior means editing code and redeploying.\n- **stdout may vanish** in containers/service managers; appenders route to files or remote sinks.\n- **SLF4J + Logback** is the Spring Boot default and just as simple to call."),
        S("speakable_answer", "How to Answer This Verbally",
          "You should avoid System.out.println in production because it's missing every feature real logging gives you. First, there are no log levels. With println, everything looks the same — there's no way to say this is debug detail versus this is a critical error, and no way to filter by severity. With a logger you use log.info for normal events and log.error for failures, then configure production to show only what matters. Second, there are no timestamps. If you print order placed, you have no idea when it happened, and during an incident you need timestamps to reconstruct the sequence of events. Loggers add them automatically. Third, there's no logger name or context, so you can't tell which class produced the message without manually prefixing it. Fourth, you can't configure println per environment — the debug print you used locally will also run in production unless you remember to delete every single one. With a logger you just set the level to INFO in prod and all your debug statements are suppressed. Fifth, println writes to standard output, which in a Docker container or a systemd service might not be captured anywhere you can actually read. Loggers write to configured appenders — files, JSON, or centralized logging. The fix is SLF4J, the standard logging facade, with Logback as the implementation — and that's already the default in Spring Boot. You declare a private static final Logger with LoggerFactory.getLogger and then call log.info or log.error. It's the same amount of typing as println, but you get levels, timestamps, context, configuration, and routing for free."),
    ],
    hook="println works perfectly on your laptop and then quietly disappears the moment your app runs inside a container — that's the whole problem.",
)

# ---- 007 ----
U["jbf-debug-log-levels-007"] = dict(
    layout_type="recipe-builder",
    direct_answer="Log incoming HTTP requests at **INFO** in production — a concise summary (method, path, status, duration) as an audit trail — and at **DEBUG** during development for headers, params, and bodies. Never log at ERROR for normal traffic, and **never log sensitive data** (auth tokens, passwords, card numbers) at any level. Spring Boot offers built-in request logging, but a custom filter gives you precise control.",
    interviewer_intent={
        "testing": "Whether you can apply log-level judgment to a concrete, everyday Spring Boot scenario and remember the security angle.",
        "common_mistake": "Logging requests at ERROR, or leaving DEBUG request logging on in production so passwords and tokens end up in logs.",
        "to_stand_out": "Separate the INFO summary from DEBUG detail, mention correlation IDs (MDC), and call out redaction of sensitive fields.",
    },
    sections=[
        S("overview", "Logging HTTP Requests Well",
          "Request logging balances **audit trail vs noise vs security**. In production, log a concise summary at **INFO** — HTTP method, path, status code, and response time — enough to understand traffic and diagnose issues. Reserve **DEBUG** for full detail (headers, query params, bodies) during troubleshooting.\n\nThe non-negotiable rule: requests routinely carry **secrets** — Authorization headers, passwords, card numbers, PII. Never log those at any level; redact them. Spring Boot ships `CommonsRequestLoggingFilter`, but teams often write a custom filter or interceptor for exact control."),
        S("concept_map", "Request Logging by Level",
          "emerald|INFO (prod)|~Audit trail|method + path|status + duration|no secrets ever\nblue|DEBUG (dev)|~Full detail|headers + params|body when needed|redact sensitive\nrose|Never|~Security risk|auth tokens|passwords + cards|PII in plain text\namber|MDC|~Correlation|requestId per request|grep one request|ties lines together"),
        S("code_example", "Step 1 — INFO Summary in Production",
          "```java\nimport org.slf4j.Logger;\nimport org.slf4j.LoggerFactory;\nimport org.springframework.web.servlet.HandlerInterceptor;\n\npublic class RequestLogInterceptor implements HandlerInterceptor {\n    private static final Logger log = LoggerFactory.getLogger(RequestLogInterceptor.class);\n\n    public boolean preHandle(HttpServletRequest req, HttpServletResponse res, Object handler) {\n        req.setAttribute(\"start\", System.currentTimeMillis());\n        return true;\n    }\n    public void afterCompletion(HttpServletRequest req, HttpServletResponse res, Object h, Exception e) {\n        long ms = System.currentTimeMillis() - (long) req.getAttribute(\"start\");\n        // Metadata only — never the body or auth header\n        log.info(\"{} {} -> {} ({} ms)\", req.getMethod(), req.getRequestURI(), res.getStatus(), ms);\n    }\n}\n```"),
        S("step", "Step 2 — DEBUG Detail + Redaction",
          "```java\n// Only at DEBUG, and with sensitive fields stripped\nif (log.isDebugEnabled()) {\n    log.debug(\"Headers: {}\", redact(headers));      // strip Authorization, Cookie\n    log.debug(\"Query: {}\", req.getQueryString());\n}\n\nprivate Map<String,String> redact(Map<String,String> h) {\n    Map<String,String> safe = new HashMap<>(h);\n    safe.replaceAll((k, v) -> SENSITIVE.contains(k.toLowerCase()) ? \"***\" : v);\n    return safe; // password, authorization, cookie, card -> ***\n}\n```\n\nGuarding with `isDebugEnabled()` also avoids building the detail string when DEBUG is off."),
        S("step", "Step 3 — Add a Correlation ID with MDC",
          "```properties\n# Pattern includes %X{requestId} so every line for one request is tied together\nlogging.pattern.level=%5p [%X{requestId}]\n```\n\nPut a request ID into SLF4J's MDC at the start of the request so all logs for that request can be grepped together — invaluable when one user reports a problem."),
        S("common_mistakes", "Common Mistakes",
          "- **Requests at ERROR**: treating normal traffic as errors, making ERROR meaningless and paging people for routine load.\n- **DEBUG left on in prod**: enabling `logging.level.org.springframework.web=DEBUG` to chase one bug and forgetting it, dumping every header and param — including secrets.\n- **No redaction**: logging whole request objects with `password` or `creditCard` fields, a security and compliance violation."),
        S("key_points", "Key Points",
          "- **INFO** in prod: method, path, status, duration — a clean audit trail.\n- **DEBUG** for headers/params/bodies, only while troubleshooting.\n- **Never log secrets** (auth tokens, passwords, card numbers, PII) at any level — redact.\n- **Correlation/request ID via MDC** ties a request's logs together.\n- **Custom filter/interceptor** beats the built-in for precise, safe control."),
        S("speakable_answer", "How to Answer This Verbally",
          "For logging incoming HTTP requests in Spring Boot, I'd use INFO in production and DEBUG during development. The reasoning is that requests are normal business events, not errors — every user action generates one. So at INFO I log the essential metadata: the HTTP method, the path, the response status, and how long it took. Something like POST slash api slash orders, status 200, 145 milliseconds. That gives operations a clean audit trail — which endpoints are hit, whether they succeed, and where the latency is — without flooding the logs. During development I switch to DEBUG to capture the detail: headers, query parameters, sometimes the request body. That's exactly what you need when a specific request is failing, but you'd never want it for every request in production because of volume and, more importantly, security. And that's the critical part. Requests routinely carry secrets — Authorization headers, passwords on login, card numbers at checkout, personal data. I never log those at any level; I redact them before logging. A lot of teams maintain a list of sensitive field names and replace their values with asterisks. The mistakes freshers make are logging requests at ERROR because they seem important, which makes ERROR useless, or leaving DEBUG request logging on in production and accidentally writing passwords and tokens into the logs. One thing that stands out is mentioning correlation IDs — putting a request ID into the MDC so every log line for a single request can be tied together, which is gold when one user reports an issue. Spring Boot has built-in request logging, but I usually prefer a small custom interceptor so I control exactly what gets logged and at what level."),
    ],
    hook="Logging an HTTP request is easy — logging it without dumping someone's password or auth token into your log files is the part interviewers actually probe.",
)

# ---- 008 ----
U["jbf-debug-log-levels-008"] = dict(
    layout_type="comparison-arena",
    direct_answer="**WARN** means something unexpected happened but the application **handled it and the operation still completed** (a retry succeeded, a fallback was used). **ERROR** means the operation **failed or produced a wrong result** (database down, payment couldn't be processed). The operational difference: ERROR typically **pages on-call**, while WARN is reviewed later — so misusing them creates alert fatigue or missed incidents.",
    interviewer_intent={
        "testing": "Whether you grasp the semantic line between a handled surprise and a genuine failure, and the operational impact on alerting.",
        "common_mistake": "Logging every caught exception at ERROR, including expected business exceptions like validation or auth failures.",
        "to_stand_out": "Use a clean rule — if the user's action still succeeded, it's WARN; if it failed, it's ERROR — and connect over-use of ERROR to alert fatigue.",
    },
    sections=[
        S("overview", "WARN vs ERROR — Did the Operation Complete?",
          "The difference is about **completion and correctness**. **WARN** = the app noticed something off but **kept working** — possibly degraded or via a fallback — and the caller's request still succeeded. **ERROR** = the operation **failed to complete** or returned an incorrect result.\n\nThis matters operationally: ERROR logs usually trigger **alerts/paging**, while WARN logs are monitored during business hours. Mislabel them and you get either alert fatigue (too many ERRORs) or missed incidents (real failures hidden at WARN)."),
        S("concept_map", "WARN vs ERROR at a Glance",
          "amber|WARN|~Handled surprise|operation completed|retry, fallback|reviewed later\nrose|ERROR|~Real failure|operation failed|DB down, payment failed|pages on-call\nblue|The test|~Did it complete?|user succeeded -> WARN|user failed -> ERROR|consequence, not exception"),
        S("comparison_table", "WARN vs ERROR",
          "| Aspect | WARN | ERROR |\n|---|---|---|\n| Operation outcome | Completed, maybe degraded | Failed or wrong result |\n| System state | Working, with a concern | Impaired / failing |\n| On-call response | Review later | Act now |\n| Alerting | Logged, no page | Pages on-call |\n| Examples | Retry succeeded, fallback config, soft limit hit | DB down, payment failed, unhandled exception |"),
        S("before_code", "Mislabelled — Everything at ERROR",
          "```java\ntry {\n    user = login(email, password);\n} catch (BadCredentialsException e) {\n    // WRONG: a wrong password is normal user behavior, not a system failure\n    log.error(\"Login failed for {}\", email, e); // pages on-call for typos\n}\n```"),
        S("after_code", "Correct — Level Matches Consequence",
          "```java\ntry {\n    user = login(email, password);\n} catch (BadCredentialsException e) {\n    log.info(\"Failed login attempt for {}\", email); // expected, not an error\n}\n\ntry {\n    inventory.reserve(order); // calls a downstream service\n} catch (TransientException e) {\n    log.warn(\"Inventory slow, retrying order {}\", order.id()); // handled, request continues\n} catch (ServiceDownException e) {\n    log.error(\"Inventory unavailable, order {} failed\", order.id(), e); // real failure\n    throw e;\n}\n```\n\nSame try/catch shape — the level is chosen by whether the user's request ultimately succeeded."),
        S("when_to_use", "When to Use Each",
          "**WARN** when the app detects a problem but works around it: a deprecated API in use, a missing property so a default kicks in, a circuit breaker opening but cached data served, a retried transient error, a soft limit exceeded.\n\n**ERROR** when an operation can't complete: a DB connection failure that blocks a save, a payment rejection that stops checkout, an unhandled exception bubbling up, a lost message delivery. The test: *did the caller's request succeed or fail?*"),
        S("key_points", "Key Points",
          "- **WARN** = unexpected but handled; the request still completed.\n- **ERROR** = the operation failed or returned a wrong result.\n- **Operational impact**: ERROR pages on-call; WARN is reviewed later.\n- **Expected exceptions** (validation, bad password) are not ERROR.\n- **Clean rule**: user action succeeded → WARN; user action failed → ERROR.\n- **Over-using ERROR** = alert fatigue, so real failures get ignored."),
        S("speakable_answer", "How to Answer This Verbally",
          "The difference between WARN and ERROR comes down to whether the operation actually completed. WARN is for when something unexpected happened but the application handled it and the operation still succeeded. For example, you tried to read a config property, it wasn't set, so you fell back to a default — that's WARN, the app kept working but it's worth noting. Or a downstream service was slow, you retried, and it eventually worked — also WARN. The user's request succeeded; you were just in a degraded mode for a moment. ERROR is for genuine failures where the operation couldn't complete or produced a wrong result. If you try to save an order but the database is down, that's ERROR — the order didn't get saved. If a payment gateway rejects the transaction and you can't process the payment, that's ERROR, because the thing the caller asked for failed. The operational distinction is what interviewers really want to hear: ERROR logs typically trigger alerts and page on-call engineers, while WARN logs are reviewed during business hours. So if you mislabel things and log routine events at ERROR, you create alert fatigue — people start ignoring alerts, and a real outage gets missed. The most common fresher mistake is logging every caught exception at ERROR. Not every exception is an error. A user entering the wrong password isn't a system failure, it's normal behavior, so that's INFO. Expected business exceptions like a validation failure or an insufficient-balance exception aren't ERROR either — those are scenarios you designed for. My simple rule is: if the user's action still succeeded despite the hiccup, use WARN; if their action failed, use ERROR. And a secondary check — should this page someone right now? If yes, ERROR. If it can wait until morning, WARN."),
    ],
    hook="WARN and ERROR look almost identical in the catch block — the question is whether the user still got what they asked for or walked away empty-handed.",
)

# Apply
for q in qs:
    u = U.get(q["id"])
    if not u:
        print("NO UPDATE FOR", q["id"]); continue
    q["direct_answer"] = u["direct_answer"]
    q["interviewer_intent"] = u["interviewer_intent"]
    q["layout_type"] = u["layout_type"]
    q["last_updated"] = "2026-06-04"
    q["answer"] = {"sections": u["sections"]}
    sv2 = q.get("speakable_v2")
    if isinstance(sv2, dict):
        sv2["hook"] = u["hook"]

json.dump(d, open(PATH, "w"), indent=2, ensure_ascii=False)
print("WROTE", PATH, len(qs), "questions")
