"""
Phase A — Scaffold the new content tree under content/java-backend-intermediate/.

Creates one folder per locked module, one subfolder per topic, and a
_config.json per module containing:
    moduleNumber, pillar, pillarName, moduleSlug, title, seoSlug,
    altSlugs[], topics[], appUrl, seoUrl

Drawn from content/ARCHITECTURE.md — this script is the single place the
module/topic/url map lives in code form.

Does NOT copy any Q&A content. That is Phase B.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TARGET_ROOT = REPO_ROOT / "content" / "java-backend-intermediate"
APP_PREFIX = "/java-backend-intermediate"


MODULES: list[dict] = [
    # ---------- Pillar 01: Java Language & Core ----------
    {
        "moduleNumber": "M01",
        "pillar": "P01",
        "pillarName": "Java Language & Core",
        "moduleSlug": "core-java",
        "title": "Core Java & OOP",
        "seoSlug": "core-java-interview-questions",
        "altSlugs": ["java-oop-interview-questions"],
        "topics": [
            "oop-principles",
            "generics-wildcards",
            "exception-handling",
            "string-handling",
            "reflection-annotations",
            "java-io-nio",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M02",
        "pillar": "P01",
        "pillarName": "Java Language & Core",
        "moduleSlug": "java-collections",
        "title": "Java Collections & Algorithms",
        "seoSlug": "java-collections-interview-questions",
        "altSlugs": ["java-data-structures-interview-questions"],
        "topics": [
            "collections-internals",
            "algorithm-complexity",
            "sorting-and-searching",
            "trees-and-graphs",
            "dynamic-programming",
            "problem-solving-patterns",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M03",
        "pillar": "P01",
        "pillarName": "Java Language & Core",
        "moduleSlug": "java-streams",
        "title": "Java Streams, Lambdas & Modern Java",
        "seoSlug": "java-streams-interview-questions",
        "altSlugs": [
            "java-8-interview-questions",
            "java-17-interview-questions",
            "java-21-interview-questions",
            "java-lambda-interview-questions",
        ],
        "topics": [
            "lambdas-functional-interfaces",
            "streams-api",
            "optional-api",
            "java-9-to-11-features",
            "java-14-to-17-features",
            "java-21-features",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M04",
        "pillar": "P01",
        "pillarName": "Java Language & Core",
        "moduleSlug": "java-concurrency",
        "title": "Java Concurrency & Multithreading",
        "seoSlug": "java-concurrency-interview-questions",
        "altSlugs": [
            "java-multithreading-interview-questions",
            "java-thread-interview-questions",
        ],
        "topics": [
            "threads-and-lifecycle",
            "synchronization-and-locks",
            "thread-pools-and-executor",
            "completable-future",
            "concurrent-collections",
            "java-memory-model",
            "virtual-threads",
            "concurrency-patterns",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M05",
        "pillar": "P01",
        "pillarName": "Java Language & Core",
        "moduleSlug": "jvm-internals",
        "title": "JVM Internals & Performance",
        "seoSlug": "jvm-interview-questions",
        "altSlugs": [
            "java-jvm-interview-questions",
            "java-garbage-collection-interview-questions",
        ],
        "topics": [
            "jvm-architecture",
            "garbage-collection",
            "jvm-tuning",
            "memory-analysis",
            "profiling-and-debugging",
            "scenario-based",
            "comparisons",
        ],
    },
    # ---------- Pillar 02: Spring Ecosystem ----------
    {
        "moduleNumber": "M06",
        "pillar": "P02",
        "pillarName": "Spring Ecosystem",
        "moduleSlug": "spring-core",
        "title": "Spring Core & IoC",
        "seoSlug": "spring-core-interview-questions",
        "altSlugs": [
            "spring-ioc-interview-questions",
            "spring-dependency-injection-interview-questions",
        ],
        "topics": [
            "dependency-injection",
            "bean-lifecycle",
            "aop",
            "spring-internals",
            "custom-components",
            "spring-events",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M07",
        "pillar": "P02",
        "pillarName": "Spring Ecosystem",
        "moduleSlug": "spring-boot",
        "title": "Spring Boot",
        "seoSlug": "spring-boot-interview-questions",
        "altSlugs": [],
        "topics": [
            "auto-configuration",
            "starters",
            "actuator",
            "profiles-and-properties",
            "embedded-servers",
            "configuration-management",
            "testing",
            "troubleshooting",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M08",
        "pillar": "P02",
        "pillarName": "Spring Ecosystem",
        "moduleSlug": "spring-data-jpa",
        "title": "Spring Data, JPA & Hibernate",
        "seoSlug": "hibernate-interview-questions",
        "altSlugs": [
            "spring-data-jpa-interview-questions",
            "jpa-interview-questions",
        ],
        "topics": [
            "jpa-fundamentals",
            "hibernate-internals",
            "spring-data-jpa",
            "entity-relationships",
            "transactions",
            "n-plus-one-problem",
            "query-optimization",
            "custom-repositories",
            "database-migrations",
            "batch-processing",
            "multi-tenancy",
            "caching",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M09",
        "pillar": "P02",
        "pillarName": "Spring Ecosystem",
        "moduleSlug": "spring-security",
        "title": "Spring Security & Identity",
        "seoSlug": "spring-security-interview-questions",
        "altSlugs": [
            "oauth2-interview-questions",
            "jwt-interview-questions",
        ],
        "topics": [
            "security-fundamentals",
            "authentication",
            "authorization",
            "jwt",
            "oauth2",
            "cors-and-csrf",
            "sso-and-saml",
            "security-configuration",
            "testing",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M10",
        "pillar": "P02",
        "pillarName": "Spring Ecosystem",
        "moduleSlug": "spring-webflux",
        "title": "Spring WebFlux & Reactive Programming",
        "seoSlug": "spring-webflux-interview-questions",
        "altSlugs": [
            "reactive-programming-interview-questions",
            "project-reactor-interview-questions",
        ],
        "topics": [
            "reactive-programming-basics",
            "mono-and-flux",
            "backpressure",
            "spring-webflux-setup",
            "r2dbc-reactive-data",
            "error-handling-reactive",
            "testing-reactive",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M11",
        "pillar": "P02",
        "pillarName": "Spring Ecosystem",
        "moduleSlug": "spring-batch",
        "title": "Spring Batch & Scheduling",
        "seoSlug": "spring-batch-interview-questions",
        "altSlugs": ["spring-scheduling-interview-questions"],
        "topics": [
            "batch-fundamentals",
            "job-and-step-structure",
            "chunk-processing",
            "item-reader-writer-processor",
            "job-scheduling-with-quartz",
            "scheduled-tasks",
            "batch-error-handling",
            "partitioning-and-parallel-steps",
            "scenario-based",
            "comparisons",
        ],
    },
    # ---------- Pillar 03: Data & Persistence ----------
    {
        "moduleNumber": "M12",
        "pillar": "P03",
        "pillarName": "Data & Persistence",
        "moduleSlug": "sql-databases",
        "title": "SQL & Relational Databases",
        "seoSlug": "sql-interview-questions",
        "altSlugs": [
            "postgresql-interview-questions",
            "database-interview-questions",
        ],
        "topics": [
            "sql-fundamentals",
            "joins-and-subqueries",
            "indexes-and-performance",
            "transactions-and-acid",
            "postgresql-features",
            "advanced-sql-features",
            "connection-pooling",
            "query-optimization",
            "partitioning-and-sharding",
            "replication",
            "database-migrations",
            "backup-recovery",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M13",
        "pillar": "P03",
        "pillarName": "Data & Persistence",
        "moduleSlug": "nosql-mongodb",
        "title": "NoSQL & MongoDB",
        "seoSlug": "mongodb-interview-questions",
        "altSlugs": [
            "nosql-interview-questions",
            "elasticsearch-interview-questions",
        ],
        "topics": [
            "nosql-fundamentals",
            "document-model",
            "mongodb-core",
            "mongodb-with-spring",
            "mongodb-indexes",
            "nosql-patterns",
            "elasticsearch-basics",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M14",
        "pillar": "P03",
        "pillarName": "Data & Persistence",
        "moduleSlug": "redis-caching",
        "title": "Redis & Caching",
        "seoSlug": "redis-interview-questions",
        "altSlugs": [
            "caching-interview-questions",
            "spring-cache-interview-questions",
        ],
        "topics": [
            "redis-data-structures",
            "redis-advanced",
            "redis-persistence",
            "spring-data-redis",
            "cache-patterns",
            "caching-strategies",
            "caffeine-cache",
            "distributed-caching",
            "cache-invalidation",
            "performance-optimization",
            "scenario-based",
            "comparisons",
        ],
    },
    # ---------- Pillar 04: APIs, Microservices & Messaging ----------
    {
        "moduleNumber": "M15",
        "pillar": "P04",
        "pillarName": "APIs, Microservices & Messaging",
        "moduleSlug": "rest-api",
        "title": "REST API & Spring MVC",
        "seoSlug": "rest-api-interview-questions",
        "altSlugs": [
            "spring-mvc-interview-questions",
            "graphql-interview-questions",
            "grpc-interview-questions",
        ],
        "topics": [
            "rest-fundamentals",
            "spring-mvc-controllers",
            "request-and-response-handling",
            "api-design",
            "error-handling",
            "openapi-and-swagger",
            "hateoas",
            "rest-client-and-feign",
            "http-caching-and-compression",
            "versioning",
            "graphql-with-spring",
            "grpc-basics",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M16",
        "pillar": "P04",
        "pillarName": "APIs, Microservices & Messaging",
        "moduleSlug": "microservices",
        "title": "Microservices Architecture",
        "seoSlug": "microservices-interview-questions",
        "altSlugs": [
            "spring-cloud-interview-questions",
            "service-mesh-interview-questions",
        ],
        "topics": [
            "fundamentals",
            "service-design",
            "api-gateway",
            "service-discovery",
            "circuit-breaker",
            "load-balancing",
            "feign-client",
            "config-management",
            "distributed-tracing",
            "resilience-patterns",
            "communication-patterns",
            "service-mesh",
            "contract-testing",
            "saga-pattern",
            "migration-strategies",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M17",
        "pillar": "P04",
        "pillarName": "APIs, Microservices & Messaging",
        "moduleSlug": "messaging-events",
        "title": "Messaging & Event-Driven Architecture",
        "seoSlug": "kafka-interview-questions",
        "altSlugs": [
            "rabbitmq-interview-questions",
            "event-driven-architecture-interview-questions",
            "event-sourcing-interview-questions",
        ],
        "topics": [
            "messaging-fundamentals",
            "kafka-architecture",
            "kafka-patterns",
            "spring-kafka",
            "rabbitmq",
            "event-sourcing",
            "cqrs",
            "message-guarantees",
            "stream-processing",
            "webhooks",
            "scenario-based",
            "comparisons",
        ],
    },
    # ---------- Pillar 05: Architecture & Design ----------
    {
        "moduleNumber": "M18",
        "pillar": "P05",
        "pillarName": "Architecture & Design",
        "moduleSlug": "design-patterns",
        "title": "Design Patterns & SOLID",
        "seoSlug": "design-patterns-interview-questions",
        "altSlugs": [
            "solid-principles-interview-questions",
            "java-design-patterns-interview-questions",
        ],
        "topics": [
            "solid-principles",
            "creational-patterns",
            "structural-patterns",
            "behavioral-patterns",
            "design-patterns-legacy",
            "refactoring",
            "technical-debt",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M19",
        "pillar": "P05",
        "pillarName": "Architecture & Design",
        "moduleSlug": "architecture-patterns",
        "title": "Architecture Patterns & Principles",
        "seoSlug": "software-architecture-interview-questions",
        "altSlugs": [
            "clean-architecture-interview-questions",
            "domain-driven-design-interview-questions",
            "ddd-interview-questions",
        ],
        "topics": [
            "architectural-styles",
            "clean-architecture",
            "hexagonal-architecture",
            "domain-driven-design",
            "cqrs-and-event-sourcing",
            "microservices-patterns",
            "scenario-based",
            "comparisons",
        ],
    },
    # ---------- Pillar 06: System Design ----------
    {
        "moduleNumber": "M20",
        "pillar": "P06",
        "pillarName": "System Design",
        "moduleSlug": "system-design",
        "title": "System Design Fundamentals",
        "seoSlug": "system-design-interview-questions",
        "altSlugs": [],
        "topics": [
            "design-fundamentals",
            "scalability",
            "high-availability",
            "cap-theorem",
            "capacity-planning",
            "database-design-at-scale",
            "caching-at-scale",
            "load-balancing",
            "event-driven-design",
            "microservices-design",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M21",
        "pillar": "P06",
        "pillarName": "System Design",
        "moduleSlug": "system-design-cases",
        "title": "System Design Case Studies",
        "seoSlug": "system-design-problems",
        "altSlugs": ["system-design-case-studies"],
        "topics": [
            "url-shortener",
            "notification-service",
            "payment-system",
            "social-media-feed",
            "rate-limiter",
            "chat-system",
            "search-autocomplete",
            "scenario-based",
        ],
    },
    # ---------- Pillar 07: Security ----------
    {
        "moduleNumber": "M22",
        "pillar": "P07",
        "pillarName": "Security",
        "moduleSlug": "application-security",
        "title": "Application Security & OWASP",
        "seoSlug": "application-security-interview-questions",
        "altSlugs": [
            "owasp-interview-questions",
            "web-security-interview-questions",
        ],
        "topics": [
            "owasp-top-10",
            "encryption",
            "secure-coding",
            "secrets-management",
            "security-architecture",
            "security-testing",
            "vulnerability-scanning",
            "compliance",
            "scenario-based",
            "comparisons",
        ],
    },
    # ---------- Pillar 08: Testing & Quality ----------
    {
        "moduleNumber": "M23",
        "pillar": "P08",
        "pillarName": "Testing & Quality",
        "moduleSlug": "unit-testing",
        "title": "Unit & Integration Testing",
        "seoSlug": "java-testing-interview-questions",
        "altSlugs": [
            "junit-interview-questions",
            "mockito-interview-questions",
        ],
        "topics": [
            "unit-testing-basics",
            "unit-testing-advanced",
            "mocking-with-mockito",
            "integration-testing",
            "spring-boot-testing",
            "testcontainers",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M24",
        "pillar": "P08",
        "pillarName": "Testing & Quality",
        "moduleSlug": "advanced-testing",
        "title": "Advanced Testing Strategies",
        "seoSlug": "advanced-testing-interview-questions",
        "altSlugs": [
            "tdd-interview-questions",
            "testcontainers-interview-questions",
            "contract-testing-interview-questions",
        ],
        "topics": [
            "tdd-practices",
            "test-automation",
            "contract-testing",
            "performance-testing",
            "chaos-testing",
            "testing-strategies",
            "scenario-based",
            "comparisons",
        ],
    },
    # ---------- Pillar 09: DevOps ----------
    {
        "moduleNumber": "M25",
        "pillar": "P09",
        "pillarName": "DevOps",
        "moduleSlug": "git-build-tools",
        "title": "Git & Build Tools",
        "seoSlug": "git-interview-questions",
        "altSlugs": [
            "maven-interview-questions",
            "gradle-interview-questions",
        ],
        "topics": [
            "git-internals",
            "git-workflows",
            "maven-build",
            "gradle-build",
            "code-quality-gates",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M26",
        "pillar": "P09",
        "pillarName": "DevOps",
        "moduleSlug": "cicd",
        "title": "CI/CD Pipelines",
        "seoSlug": "cicd-interview-questions",
        "altSlugs": [
            "jenkins-interview-questions",
            "github-actions-interview-questions",
            "devops-interview-questions",
        ],
        "topics": [
            "cicd-fundamentals",
            "jenkins-pipelines",
            "github-actions",
            "infrastructure-as-code",
            "deployment-strategies",
            "rollback-strategies",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M27",
        "pillar": "P09",
        "pillarName": "DevOps",
        "moduleSlug": "docker",
        "title": "Docker & Containerization",
        "seoSlug": "docker-interview-questions",
        "altSlugs": ["containerization-interview-questions"],
        "topics": [
            "docker-fundamentals",
            "docker-compose",
            "docker-networking",
            "docker-security",
            "multi-stage-builds",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M28",
        "pillar": "P09",
        "pillarName": "DevOps",
        "moduleSlug": "kubernetes",
        "title": "Kubernetes & Orchestration",
        "seoSlug": "kubernetes-interview-questions",
        "altSlugs": [
            "k8s-interview-questions",
            "helm-interview-questions",
        ],
        "topics": [
            "kubernetes-fundamentals",
            "kubernetes-workloads",
            "kubernetes-configuration",
            "kubernetes-networking",
            "kubernetes-scaling",
            "helm",
            "scenario-based",
            "comparisons",
        ],
    },
    # ---------- Pillar 10: Cloud ----------
    {
        "moduleNumber": "M29",
        "pillar": "P10",
        "pillarName": "Cloud",
        "moduleSlug": "aws-cloud",
        "title": "AWS & Cloud Platforms",
        "seoSlug": "aws-interview-questions",
        "altSlugs": [
            "cloud-computing-interview-questions",
            "gcp-interview-questions",
        ],
        "topics": [
            "aws-core-services",
            "ecs-and-fargate",
            "rds-with-spring",
            "s3-storage",
            "iam-and-security",
            "aws-messaging",
            "serverless",
            "gcp-and-azure-overview",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M30",
        "pillar": "P10",
        "pillarName": "Cloud",
        "moduleSlug": "cloud-native",
        "title": "Cloud-Native & Infrastructure as Code",
        "seoSlug": "cloud-native-interview-questions",
        "altSlugs": [
            "terraform-interview-questions",
            "infrastructure-as-code-interview-questions",
        ],
        "topics": [
            "12-factor-app",
            "cloud-design-patterns",
            "deployment-strategies",
            "disaster-recovery",
            "multi-region-architecture",
            "cost-optimization",
            "scenario-based",
            "comparisons",
        ],
    },
    # ---------- Pillar 11: Production ----------
    {
        "moduleNumber": "M31",
        "pillar": "P11",
        "pillarName": "Production",
        "moduleSlug": "observability",
        "title": "Observability & Monitoring",
        "seoSlug": "observability-interview-questions",
        "altSlugs": [
            "monitoring-interview-questions",
            "prometheus-interview-questions",
            "distributed-tracing-interview-questions",
        ],
        "topics": [
            "structured-logging",
            "distributed-log-aggregation",
            "metrics-and-micrometer",
            "prometheus-and-grafana",
            "distributed-tracing",
            "health-checks-and-probes",
            "alerting",
            "apm-tools",
            "scenario-based",
            "comparisons",
        ],
    },
    {
        "moduleNumber": "M32",
        "pillar": "P11",
        "pillarName": "Production",
        "moduleSlug": "production-sre",
        "title": "Production Operations & SRE",
        "seoSlug": "sre-interview-questions",
        "altSlugs": [
            "production-operations-interview-questions",
            "site-reliability-engineering-interview-questions",
        ],
        "topics": [
            "debugging-production",
            "thread-and-heap-dumps",
            "memory-leaks",
            "performance-troubleshooting",
            "incident-response",
            "incident-management",
            "root-cause-analysis",
            "postmortems",
            "chaos-engineering",
            "sre-practices",
            "capacity-planning",
            "runbooks",
            "on-call",
            "scenario-based",
        ],
    },
    # ---------- Pillar 12: Interview Readiness ----------
    {
        "moduleNumber": "M33",
        "pillar": "P12",
        "pillarName": "Interview Readiness",
        "moduleSlug": "engineering-practices",
        "title": "Engineering Practices",
        "seoSlug": "engineering-practices-interview-questions",
        "altSlugs": [
            "code-review-interview-questions",
            "software-engineering-best-practices-interview-questions",
        ],
        "topics": [
            "code-review",
            "architecture-decisions",
            "technical-documentation",
            "technical-debt",
            "team-collaboration",
            "knowledge-sharing",
            "mentoring",
            "scenario-based",
        ],
    },
    {
        "moduleNumber": "M34",
        "pillar": "P12",
        "pillarName": "Interview Readiness",
        "moduleSlug": "behavioral",
        "title": "Behavioral & Leadership",
        "seoSlug": "behavioral-interview-questions-software-engineer",
        "altSlugs": [
            "java-developer-behavioral-interview-questions",
            "technical-leadership-interview-questions",
        ],
        "topics": [
            "star-method",
            "conflict-resolution",
            "technical-leadership",
            "agile-and-scrum",
            "delivering-under-pressure",
            "failure-and-learning",
            "career-growth",
        ],
    },
]


def build_module_config(m: dict) -> dict:
    return {
        "moduleNumber": m["moduleNumber"],
        "pillar": m["pillar"],
        "pillarName": m["pillarName"],
        "moduleSlug": m["moduleSlug"],
        "title": m["title"],
        "appUrl": f"{APP_PREFIX}/{m['moduleSlug']}",
        "seoSlug": m["seoSlug"],
        "seoUrl": f"/{m['seoSlug']}",
        "altSlugs": m["altSlugs"],
        "altUrls": [f"/{alt}" for alt in m["altSlugs"]],
        "topics": m["topics"],
    }


def scaffold() -> tuple[int, int]:
    TARGET_ROOT.mkdir(parents=True, exist_ok=True)
    module_count = 0
    topic_count = 0

    for m in MODULES:
        module_dir = TARGET_ROOT / m["moduleSlug"]
        module_dir.mkdir(parents=True, exist_ok=True)
        module_count += 1

        for topic in m["topics"]:
            topic_dir = module_dir / topic
            topic_dir.mkdir(parents=True, exist_ok=True)
            (topic_dir / "answers").mkdir(parents=True, exist_ok=True)
            topic_count += 1

        config_path = module_dir / "_config.json"
        config_path.write_text(
            json.dumps(build_module_config(m), indent=2) + "\n",
            encoding="utf-8",
        )

    return module_count, topic_count


def write_index() -> None:
    """Top-level index file listing every module + its SEO URLs."""
    index = {
        "appRoot": APP_PREFIX,
        "totalModules": len(MODULES),
        "modules": [build_module_config(m) for m in MODULES],
    }
    (TARGET_ROOT / "_index.json").write_text(
        json.dumps(index, indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    modules, topics = scaffold()
    write_index()
    print(f"[scaffold] target: {TARGET_ROOT.relative_to(REPO_ROOT)}")
    print(f"[scaffold] modules created/verified: {modules}")
    print(f"[scaffold] topic folders created/verified: {topics}")
    print(f"[scaffold] wrote _index.json with {modules} modules")
