"""
seed_jfi_phase1_data_angular.py
===============================

Angular pillar (P16) question scaffolds. Exports `ANGULAR_TOPIC_DEFS`
which is merged into master TOPIC_DEFS by `seed_jfi_phase1_data.py`.
"""

ANG_T = ["microsoft", "google", "accenture", "infosys", "tcs", "wipro", "cognizant"]
FE = ["meta", "google", "airbnb", "netflix", "uber", "flipkart", "razorpay"]

ANGULAR_TOPIC_DEFS: dict = {

    # -----------------------------------------------------------------------
    # M24 angular-core (10 topics, 15 Qs)
    # -----------------------------------------------------------------------
    "angular-core": {
        "modules-and-components": ("Modules & Components", [
            ("angular-ngmodule-vs-standalone",
             "NgModule vs Standalone components in Angular — what's the difference?",
             "NgModule vs Standalone Components (Angular 14+) — Migration Guide",
             "comparison", "medium", "high", 6,
             "NgModules wrap declarations/imports/providers; standalone components (v14+) eliminate boilerplate and are the new default",
             "Still starting new projects with AppModule in 2026 — Angular 17+ defaults to standalone and modules are considered legacy",
             "Note Angular 17+ CLI generates standalone by default and the roadmap deprecates NgModule for new code",
             ANG_T,
             ["Are NgModules deprecated?",
              "How do you migrate from NgModule to standalone?",
              "What is bootstrapApplication?",
              "How do standalone components handle DI?"],
             "NgModule vs Standalone Components in Angular (2026)",
             "Choose between NgModule and standalone components in Angular 14+: migration, bootstrapApplication, DI, and 2026 defaults."),

            ("angular-component-decorator-selector-template",
             "What is the @Component decorator in Angular? Explain selector, template, and styles.",
             "@Component in Angular — selector, template, styles Explained",
             "default", "easy", "high", 5,
             "@Component metadata: selector, template/templateUrl, styles/styleUrls, changeDetection, providers, standalone",
             "Using inline templates for complex UIs — prefer templateUrl and style files for separation of concerns",
             "Show OnPush change detection on the decorator and how to opt into standalone mode",
             ANG_T,
             ["What is changeDetection: OnPush?",
              "Can a component be standalone without NgModule?",
              "When should you use inline templates?",
              "What does ViewEncapsulation.None do?"],
             "@Component in Angular (2026) — selector, template, styles",
             "Master Angular's @Component decorator: selector, template/styles, ChangeDetection.OnPush, standalone, and ViewEncapsulation modes."),
        ]),

        "dependency-injection": ("Dependency Injection", [
            ("angular-dependency-injection-explained",
             "How does Angular's dependency injection (DI) work?",
             "Angular Dependency Injection Explained — Providers & Injector",
             "default", "medium", "high", 7,
             "Hierarchical injector tree, providers with providedIn, constructor injection, inject() function (v14+), tokens and @Injectable",
             "Registering a service at both component and module level and getting two instances — understand injector hierarchy before using providers",
             "Introduce the new inject() function for functional DI (cleaner than constructor DI), and tree-shakable providedIn: 'root'",
             ANG_T,
             ["What is the inject() function in Angular 14+?",
              "What is providedIn: 'root'?",
              "What is hierarchical DI?",
              "How do injection tokens work?"],
             "Angular DI Explained (2026) — Providers, Injector, inject()",
             "Master Angular dependency injection: hierarchical injector, providers, providedIn: 'root', inject() function, and tokens."),

            ("angular-providedin-root-vs-module",
             "What is the difference between providedIn: 'root' and module-level providers?",
             "providedIn: 'root' vs Module Providers — Singleton Services",
             "comparison", "medium", "medium", 5,
             "providedIn: 'root' tree-shakable singleton; module-level providers scope to that module's injector; component-level creates per-instance",
             "Providing a service at component level thinking it's a singleton — it creates a new instance per component",
             "Recommend providedIn: 'root' for 99% of services; providedIn: 'platform' for cross-app sharing; component-level for per-instance state",
             ANG_T,
             ["What is providedIn: 'platform'?",
              "When should you scope a service to a component?",
              "Are providedIn: 'root' services lazy-loaded?",
              "How does tree shaking interact with providers?"],
             "providedIn 'root' vs Module Providers (2026) — DI Scopes",
             "Choose between providedIn: 'root', 'platform', and module/component-level providers in Angular for singleton vs scoped services."),
        ]),

        "directives-structural-and-attribute": ("Directives — Structural & Attribute", [
            ("angular-structural-vs-attribute-directives",
             "What is the difference between structural and attribute directives in Angular?",
             "Structural vs Attribute Directives in Angular — Differences",
             "comparison", "medium", "high", 6,
             "Structural directives change DOM layout (*ngIf, *ngFor, *ngSwitch); attribute directives change appearance/behavior (ngClass, ngStyle, custom)",
             "Applying two structural directives to the same element — not allowed; use a wrapper ng-container",
             "Mention the new Angular 17+ control flow syntax (@if, @for, @switch) that replaces *ngIf/*ngFor",
             ANG_T,
             ["What is Angular 17+ control flow syntax?",
              "Why can't you use two structural directives on one element?",
              "What is ng-container?",
              "How do you create a custom directive?"],
             "Structural vs Attribute Directives in Angular (2026)",
             "Master Angular directives: structural (*ngIf, *ngFor, @if, @for in v17+) vs attribute (ngClass, custom), with ng-container patterns."),

            ("angular-control-flow-syntax-v17",
             "What is the new Angular 17+ control flow syntax (@if, @for, @switch)?",
             "Angular 17 Control Flow — @if, @for, @switch (Replacing *ngIf/*ngFor)",
             "default", "medium", "high", 5,
             "Built-in @if/@for/@switch blocks, tracking with track, @empty blocks, faster and ergonomically better than *ngIf/*ngFor",
             "Still using *ngIf/*ngFor in new Angular 17+ code — the new control flow is faster and recommended",
             "Highlight that Angular CLI includes a migration schematic; new syntax gives better type narrowing and perf",
             ANG_T,
             ["How do you migrate from *ngIf to @if?",
              "What is the track expression in @for?",
              "Does the new control flow affect bundle size?",
              "Are @if/@for available without a library import?"],
             "Angular 17+ Control Flow (2026) — @if, @for, @switch",
             "Master Angular 17+ built-in control flow: @if, @for (with track), @switch, @empty, migration schematic, and perf improvements."),
        ]),

        "pipes-builtin-and-custom": ("Pipes — Built-in & Custom", [
            ("angular-pure-vs-impure-pipes",
             "What is the difference between pure and impure pipes in Angular?",
             "Pure vs Impure Pipes in Angular — Performance Explained",
             "comparison", "medium", "high", 5,
             "Pure (default) recomputes only when input reference changes; impure recomputes every change detection cycle; impure pipes can hurt perf",
             "Writing an impure pipe that does heavy work — it runs every CD cycle; prefer a component property with reactive updates",
             "Mention the async pipe is technically impure (subscribes to Observable) but highly optimized; it handles unsubscription automatically",
             ANG_T,
             ["Why is the async pipe considered special?",
              "When should a pipe be impure?",
              "How do pipes interact with OnPush change detection?",
              "Can you memoize an impure pipe?"],
             "Pure vs Impure Pipes in Angular (2026) — Performance",
             "Understand pure vs impure pipes in Angular: default pure behavior, async pipe exception, performance implications, and OnPush interaction."),

            ("angular-async-pipe-observable-subscription",
             "What is the async pipe in Angular? Why is it recommended?",
             "Angular Async Pipe Explained — Auto-Subscribe & Unsubscribe",
             "default", "easy", "high", 4,
             "Subscribes to Observables/Promises in the template, auto-unsubscribes on destroy, triggers CD on emissions, pairs perfectly with OnPush",
             "Subscribing manually in ngOnInit and forgetting to unsubscribe in ngOnDestroy — leaks; async pipe handles this automatically",
             "Show async pipe with OnPush + Signals as the modern trio; mention the *ngFor + async + trackBy combo",
             ANG_T,
             ["What happens if a component using async pipe is destroyed?",
              "How does async pipe interact with OnPush?",
              "Can async pipe subscribe to Signals?",
              "What is the difference between async pipe and manual subscription?"],
             "Angular Async Pipe (2026) — Auto-Subscribe & OnPush Pairing",
             "Master the Angular async pipe: auto-subscribe/unsubscribe, OnPush pairing, Signals interop, and memory-leak prevention."),
        ]),

        "lifecycle-hooks": ("Lifecycle Hooks", [
            ("angular-lifecycle-hooks-order-oninit-ondestroy",
             "What are Angular lifecycle hooks and their execution order?",
             "Angular Lifecycle Hooks — ngOnInit, ngOnDestroy & Order",
             "default", "medium", "high", 6,
             "ngOnChanges → ngOnInit → ngDoCheck → ngAfterContentInit → ngAfterContentChecked → ngAfterViewInit → ngAfterViewChecked → ngOnDestroy",
             "Using ngOnInit to access @ViewChild — child views aren't initialized yet; use ngAfterViewInit",
             "Mention Angular 16+ DestroyRef and takeUntilDestroyed() for modern unsubscription patterns (replaces ngOnDestroy + Subject)",
             ANG_T,
             ["What is DestroyRef in Angular 16+?",
              "What does takeUntilDestroyed() do?",
              "When is ngOnChanges called?",
              "What's the difference between ngAfterContentInit and ngAfterViewInit?"],
             "Angular Lifecycle Hooks (2026) — Execution Order & Modern Cleanup",
             "Master Angular lifecycle hooks: ngOnInit → ngAfterViewInit → ngOnDestroy order, DestroyRef, takeUntilDestroyed(), and @ViewChild timing."),
        ]),

        "change-detection": ("Change Detection", [
            ("angular-change-detection-default-vs-onpush",
             "Default vs OnPush change detection in Angular — what's the difference?",
             "Angular Change Detection — Default vs OnPush (Performance)",
             "comparison", "hard", "high", 7,
             "Default CD runs on any async event (setTimeout, Promise, event, HTTP); OnPush only runs on input-reference change, events, async pipe, or markForCheck",
             "Using OnPush with a mutated array/object — the reference didn't change, so Angular skips the view; use immutable updates",
             "Mention Angular Signals (v17+) and how they provide fine-grained reactivity without Zone.js and replace OnPush optimization in many cases",
             ANG_T,
             ["What are Angular Signals?",
              "How does Zone.js trigger change detection?",
              "What is markForCheck?",
              "Why does OnPush require immutable inputs?"],
             "Angular Change Detection (2026) — Default vs OnPush, Signals",
             "Master Angular change detection: Default vs OnPush, Zone.js, markForCheck, immutable inputs, and Signals as the modern alternative."),

            ("angular-signals-reactivity-v17",
             "What are Angular Signals? How do they change reactivity in Angular 17+?",
             "Angular Signals Explained — Fine-Grained Reactivity (v17+)",
             "default", "medium", "high", 6,
             "signal() for writable values, computed() for derivations, effect() for side effects; no Zone.js dependency; fine-grained updates",
             "Mixing Signals with RxJS Observables carelessly — they interop (toSignal/toObservable) but have different mental models",
             "Mention Angular's roadmap toward zoneless apps, signal-based components, and interop helpers",
             ANG_T,
             ["What is toSignal / toObservable?",
              "Will Angular remove Zone.js?",
              "How do Signals compare to RxJS?",
              "What is a computed signal?"],
             "Angular Signals (v17+) Explained (2026) — Fine-Grained Reactivity",
             "Master Angular Signals: signal, computed, effect, Zone.js-free reactivity, RxJS interop, and the roadmap to signal-based components."),
        ]),

        "services-and-providers": ("Services & Providers", [
            ("angular-services-singleton-providedin",
             "What is an Angular service? How do you make it a singleton?",
             "Angular Services & Singleton Pattern — providedIn Explained",
             "default", "easy", "high", 5,
             "@Injectable class, providedIn: 'root' for tree-shakable app-wide singleton, dependency injection, functional inject() API",
             "Creating a new instance of a service with new MyService() instead of injecting it — bypasses DI and provider scope",
             "Show the modern functional DI pattern with inject() for cleaner code and better tree shaking",
             ANG_T,
             ["What is @Injectable decorator?",
              "How do you test an Angular service?",
              "What is a factory provider?",
              "Can you inject a service into another service?"],
             "Angular Services & Singleton Pattern (2026) — providedIn",
             "Master Angular services: @Injectable, providedIn: 'root' singleton pattern, inject() function, and testing approaches."),
        ]),

        "standalone-components-and-signals": ("Standalone Components & Signals", [
            ("standalone-components-bootstrapapplication",
             "How do standalone components work with bootstrapApplication?",
             "Standalone Components & bootstrapApplication in Angular",
             "default", "medium", "high", 5,
             "bootstrapApplication(AppComponent, {providers: [...]}) replaces AppModule; imports live in the component decorator; tree-shakable",
             "Mixing AppModule and standalone components without planning — migrate incrementally; the CLI has a schematic",
             "Mention ng update --schematic to auto-migrate and the roadmap for Angular's standalone-first future",
             ANG_T,
             ["How do you migrate from AppModule to bootstrapApplication?",
              "Can standalone and NgModule components coexist?",
              "What is provideRouter?",
              "What is the Angular standalone migration schematic?"],
             "Standalone Components & bootstrapApplication (2026)",
             "Master Angular standalone components and bootstrapApplication: imports in @Component, provideRouter, migration schematic, and incremental adoption."),
        ]),

        "scenario-based": ("Scenario-Based", [
            ("component-communication-parent-child-sibling",
             "How do Angular components communicate? (Parent-child, sibling, unrelated)",
             "Angular Component Communication — @Input, @Output, Services",
             "default", "medium", "high", 6,
             "Parent→child: @Input; Child→parent: @Output (EventEmitter); siblings: shared service with BehaviorSubject or Signal; unrelated: global store",
             "Using @Input/@Output chains across many levels — prefer a shared service for distant components",
             "Modern: use Signals + service for fine-grained reactive communication; input()/output() API in v17.3+",
             ANG_T,
             ["What is the new input() function in Angular 17.3+?",
              "How do you communicate between sibling components?",
              "When should you reach for NgRx over a service?",
              "What is EventEmitter?"],
             "Angular Component Communication (2026) — @Input, @Output",
             "Master Angular component communication: @Input/@Output, shared services with Signals/Subjects, and the new input()/output() functions."),
        ]),

        "comparisons": ("Comparisons", []),
    },

    # -----------------------------------------------------------------------
    # M25 angular-rxjs (8 topics, 12 Qs)
    # -----------------------------------------------------------------------
    "angular-rxjs": {
        "observables-vs-promises": ("Observables vs Promises", [
            ("observables-vs-promises-rxjs",
             "Observables vs Promises — what are the differences?",
             "Observables vs Promises — Cold, Hot, Cancellation, Operators",
             "comparison", "medium", "high", 6,
             "Observable: lazy, cancellable, multiple values, operators; Promise: eager, single value, not cancellable (without AbortController)",
             "Treating subscribe() like await — subscribe requires unsubscription; prefer async pipe in Angular templates",
             "Mention how Angular is moving toward Signals (not Promises) for state, but Observables remain king for event streams",
             ANG_T,
             ["Are Observables lazy or eager?",
              "How do you cancel a Promise vs an Observable?",
              "Can Observables emit multiple values?",
              "When should you convert an Observable to a Promise?"],
             "Observables vs Promises (2026) — Lazy, Cancellation, Operators",
             "Master Observables vs Promises: lazy vs eager, cancellation, multiple values, operator pipeline, and RxJS-vs-Signals in Angular."),

            ("cold-vs-hot-observables-rxjs",
             "What is the difference between cold and hot Observables in RxJS?",
             "Cold vs Hot Observables in RxJS — Multicast, share, Subjects",
             "comparison", "medium", "high", 5,
             "Cold: each subscriber gets its own execution (e.g., HttpClient); Hot: shared execution (e.g., DOM events); share/multicast convert cold to hot",
             "Subscribing twice to a cold HttpClient Observable and getting two network calls — use share() or shareReplay() to multicast",
             "Show shareReplay({ bufferSize: 1, refCount: true }) as the common multicast pattern",
             ANG_T,
             ["What does shareReplay do?",
              "Why do HttpClient Observables fire twice on double-subscribe?",
              "What is multicast?",
              "Are Subjects hot or cold?"],
             "Cold vs Hot Observables in RxJS (2026) — share, Subjects",
             "Master cold vs hot Observables in RxJS: share, shareReplay, multicast, and common HttpClient double-subscribe bugs."),
        ]),

        "operators-map-switchmap-mergemap": ("Operators — map, switchMap, mergeMap", [
            ("switchmap-vs-mergemap-vs-concatmap-vs-exhaustmap",
             "switchMap vs mergeMap vs concatMap vs exhaustMap — what's the difference?",
             "switchMap vs mergeMap vs concatMap vs exhaustMap — RxJS Guide",
             "comparison", "hard", "high", 7,
             "switchMap cancels previous (latest wins); mergeMap runs in parallel; concatMap queues sequentially; exhaustMap ignores new while active",
             "Using mergeMap for a typeahead search — duplicate requests; use switchMap so earlier requests are cancelled",
             "Map each to a real UI pattern: typeahead (switch), upload queue (merge), ordered writes (concat), prevent double-submit (exhaust)",
             ANG_T,
             ["Which operator for a typeahead search?",
              "Which operator for an upload queue?",
              "What is exhaustMap good for?",
              "How does concatMap maintain order?"],
             "switchMap vs mergeMap vs concatMap vs exhaustMap (2026)",
             "Master RxJS flattening operators: switchMap for typeahead, mergeMap for parallel, concatMap for ordered, exhaustMap for ignore-while-active."),

            ("rxjs-common-operators-map-filter-tap",
             "What are the most commonly used RxJS operators? (map, filter, tap, debounceTime, distinctUntilChanged)",
             "Common RxJS Operators — map, filter, tap, debounceTime, distinct",
             "default", "medium", "high", 6,
             "Transform: map; filter: filter; side effects: tap; timing: debounceTime, throttleTime, delay; dedupe: distinctUntilChanged",
             "Putting side effects in map — use tap for side effects; map should be pure",
             "Show a typeahead pipeline: debounceTime → distinctUntilChanged → switchMap for classic search UX",
             ANG_T,
             ["Why put side effects in tap, not map?",
              "What is distinctUntilChanged?",
              "How do you build a typeahead search with RxJS?",
              "What is catchError?"],
             "Common RxJS Operators (2026) — map, filter, tap, debounceTime",
             "Master common RxJS operators: map, filter, tap, debounceTime, throttleTime, distinctUntilChanged, and typeahead composition."),

            ("typeahead-search-with-rxjs",
             "How do you build a typeahead search with RxJS? (debounceTime + switchMap + distinctUntilChanged)",
             "Typeahead Search with RxJS — debounce + switchMap + distinct",
             "code", "medium", "high", 5,
             "valueChanges pipe: debounceTime(300) → distinctUntilChanged() → switchMap(q => http.get(...)); handles rapid typing and cancels old requests",
             "Forgetting distinctUntilChanged — trailing identical emissions fire duplicate requests",
             "Recommend adding loading/error state with scan() or multicasting; catchError for resilience",
             ANG_T,
             ["Why switchMap over mergeMap here?",
              "How do you add loading state?",
              "Why debounce before distinctUntilChanged?",
              "How do you handle network errors in the pipeline?"],
             "Typeahead Search with RxJS (2026) — Full Pipeline",
             "Build a typeahead search with RxJS: debounceTime, distinctUntilChanged, switchMap, loading state, and error handling."),
        ]),

        "subjects-and-behaviorsubjects": ("Subjects & BehaviorSubjects", [
            ("rxjs-subject-vs-behaviorsubject-vs-replaysubject-vs-asyncsubject",
             "Subject vs BehaviorSubject vs ReplaySubject vs AsyncSubject — what's the difference?",
             "RxJS Subjects — Subject vs Behavior vs Replay vs Async",
             "comparison", "medium", "high", 6,
             "Subject: no initial/replay; BehaviorSubject: current value + new subs get latest; ReplaySubject: replay N past; AsyncSubject: only emits last on complete",
             "Using a plain Subject for shared state — new subscribers get nothing until the next emit; BehaviorSubject is usually correct",
             "Map to use cases: state sharing (Behavior), event bus (Subject), history (Replay), one-shot completion (Async)",
             ANG_T,
             ["When should you use ReplaySubject?",
              "What is BehaviorSubject initial value used for?",
              "How do Subjects relate to hot/cold Observables?",
              "Why use Signals over BehaviorSubject in v17+?"],
             "RxJS Subjects Compared (2026) — Subject, Behavior, Replay, Async",
             "Master RxJS Subjects: Subject, BehaviorSubject, ReplaySubject, AsyncSubject — use cases, hot semantics, and Signal alternatives."),
        ]),

        "error-handling-in-rxjs": ("Error Handling in RxJS", [
            ("rxjs-catcherror-retry-retrywhen",
             "How do you handle errors in RxJS? (catchError, retry, retryWhen)",
             "RxJS Error Handling — catchError, retry, retryWhen Examples",
             "default", "medium", "high", 6,
             "catchError returns a replacement Observable; retry re-subscribes on error; retryWhen for custom retry (exponential backoff)",
             "Placing catchError after a subscribe instead of inside the pipe — error handling must be inside the pipe to be part of the Observable",
             "Show an exponential-backoff retry pattern with retry({count, delay: error => timer(...)}); mention operator changes in RxJS 7+",
             ANG_T,
             ["What replaces retryWhen in RxJS 7+?",
              "How do you retry with exponential backoff?",
              "Where do you put catchError in a pipe?",
              "How do you log errors without swallowing them?"],
             "RxJS Error Handling (2026) — catchError, retry with Backoff",
             "Master RxJS error handling: catchError, retry, retry({delay}) exponential backoff, and placement inside pipes."),
        ]),

        "multicasting-and-hot-cold": ("Multicasting & Hot/Cold", [
            ("rxjs-share-sharereplay-multicast",
             "How do share and shareReplay work in RxJS? When should you use them?",
             "RxJS share & shareReplay — Multicast Observables Explained",
             "default", "medium", "medium", 5,
             "share() multicasts a cold Observable; shareReplay({bufferSize, refCount}) replays for late subscribers; prevents duplicate HTTP calls",
             "Leaving refCount at false (default) — subscription is never torn down on unsubscribe; memory leak",
             "Show shareReplay({bufferSize: 1, refCount: true}) as the safe default for HTTP-backed state",
             ANG_T,
             ["What does refCount do in shareReplay?",
              "When does shareReplay leak memory?",
              "How do share and shareReplay differ?",
              "Can you use shareReplay with BehaviorSubject?"],
             "RxJS share & shareReplay (2026) — Multicast Explained",
             "Master RxJS multicasting: share, shareReplay with bufferSize and refCount, and the common HTTP-dedup pattern."),
        ]),

        "schedulers": ("Schedulers", [
            ("rxjs-schedulers-async-animationframe-queue",
             "What are RxJS Schedulers? (asyncScheduler, animationFrameScheduler, queueScheduler)",
             "RxJS Schedulers Explained — async, animationFrame, queue",
             "default", "hard", "medium", 5,
             "Control when/where emissions happen; asyncScheduler (setTimeout 0), animationFrameScheduler (rAF), queueScheduler (sync), asapScheduler (microtask)",
             "Using asyncScheduler for animations — use animationFrameScheduler to align with paint",
             "Show a debounceTime + animationFrameScheduler for smoother animations; common in UI libraries",
             ANG_T,
             ["When should you use animationFrameScheduler?",
              "What is the difference between asap and queue schedulers?",
              "Is queueScheduler synchronous?",
              "When are Schedulers needed?"],
             "RxJS Schedulers Explained (2026) — Async, rAF, Queue",
             "Master RxJS Schedulers: asyncScheduler, animationFrameScheduler, queueScheduler, asapScheduler — when to use each."),
        ]),

        "rxjs-with-http-and-forms": ("RxJS with HTTP & Forms", [
            ("angular-httpclient-with-rxjs-typing",
             "How do you use Angular's HttpClient with RxJS operators?",
             "Angular HttpClient + RxJS — Typed Requests, Retry, catchError",
             "default", "medium", "high", 6,
             "HttpClient returns Observables, typed via generics, interceptors for auth/logging, retry() with exponential backoff, catchError for error mapping",
             "Subscribing to HttpClient Observable twice — fires the request twice; use shareReplay or single subscription",
             "Show an API service with interceptor-attached JWT, retry with backoff, and catchError mapping to user-friendly messages",
             ANG_T,
             ["How do HTTP interceptors work?",
              "How do you type an HttpClient call?",
              "How do you dedupe HttpClient calls?",
              "How does functional interceptor (v15+) differ from class-based?"],
             "Angular HttpClient + RxJS (2026) — Typed, Retry, catchError",
             "Master Angular HttpClient with RxJS: typed requests, interceptors, retry with backoff, catchError, and shareReplay dedup."),
        ]),

        "scenario-based": ("Scenario-Based", []),
    },

    # -----------------------------------------------------------------------
    # M26 angular-forms-router (7 topics, 10 Qs)
    # -----------------------------------------------------------------------
    "angular-forms-router": {
        "template-driven-forms": ("Template-Driven Forms", [
            ("template-driven-vs-reactive-forms-angular",
             "Template-driven vs Reactive forms in Angular — what's the difference?",
             "Template-Driven vs Reactive Forms in Angular — When to Use Each",
             "comparison", "medium", "high", 6,
             "Template-driven: ngModel, two-way binding, less code for simple forms; Reactive: FormGroup/FormControl, type-safe, scalable for complex forms",
             "Using template-driven for large dynamic forms — hard to test and scale; prefer Reactive",
             "Recommend Reactive for everything non-trivial; note typed forms (v14+) give strong TS support",
             ANG_T,
             ["What are typed reactive forms?",
              "Which is better for dynamic forms?",
              "How do you test a template-driven form?",
              "Can you mix template-driven and reactive in the same app?"],
             "Template-Driven vs Reactive Forms in Angular (2026)",
             "Compare Angular template-driven vs reactive forms: ngModel, FormGroup, typed forms, and when each fits."),
        ]),

        "reactive-forms": ("Reactive Forms", [
            ("angular-reactive-forms-formcontrol-formgroup-formarray",
             "What are FormControl, FormGroup, and FormArray in Angular reactive forms?",
             "Angular Reactive Forms — FormControl, FormGroup, FormArray",
             "default", "medium", "high", 6,
             "FormControl: single input; FormGroup: object of controls; FormArray: dynamic list; FormBuilder shorthand; typed forms v14+",
             "Adding a FormControl at runtime with untyped forms — typed forms (v14+) catch this at compile time",
             "Show a typed reactive form with validators, nested FormGroup, FormArray for a dynamic list",
             ANG_T,
             ["What is FormBuilder?",
              "How do typed forms work?",
              "How do you add a control dynamically?",
              "What is the difference between FormControl.value and valueChanges?"],
             "Angular Reactive Forms (2026) — FormControl, Group, Array, Typed",
             "Master Angular reactive forms: FormControl, FormGroup, FormArray, FormBuilder, validators, and typed forms (v14+)."),

            ("angular-form-validation-sync-async",
             "How do synchronous and asynchronous validators work in Angular?",
             "Angular Form Validators — Sync, Async & Custom",
             "default", "medium", "high", 6,
             "Built-in validators (required, minLength, pattern); custom returning ValidationErrors | null; async returning Observable/Promise; combine with Validators.compose",
             "Running an async validator on every keystroke without debouncing — floods the server; debounce via updateOn: 'blur' or custom debouncing",
             "Show an async username-uniqueness validator with debounce + HttpClient; updateOn: 'blur' as a simpler alternative",
             ANG_T,
             ["What is updateOn in AbstractControl?",
              "How do you debounce an async validator?",
              "How do you write a custom synchronous validator?",
              "How do cross-field validators work?"],
             "Angular Form Validators (2026) — Sync, Async, Custom, Cross-Field",
             "Master Angular form validation: built-in, custom sync, async validators with debounce, cross-field validation, and updateOn."),
        ]),

        "custom-validators-and-async-validators": ("Custom & Async Validators", [
            ("custom-validator-angular-example",
             "How do you write a custom validator in Angular?",
             "Custom Validator in Angular — Sync & Async Examples",
             "code", "medium", "medium", 5,
             "Function returning ValidationErrors | null for sync; Observable<ValidationErrors | null> for async; attach to FormControl via validators/asyncValidators",
             "Returning truthy boolean instead of the error-object shape — Angular expects null or an object",
             "Show a passwordStrength sync validator and a uniqueUsername async validator with debounce",
             ANG_T,
             ["How do you combine multiple validators?",
              "Why return an object from a validator?",
              "What is AbstractControl?",
              "How do you unit-test a validator?"],
             "Custom Angular Validators (2026) — Sync & Async Examples",
             "Write custom Angular validators: ValidationErrors shape, sync + async variants, debouncing, and testing."),
        ]),

        "router-basics-and-route-guards": ("Router Basics & Route Guards", [
            ("angular-router-basics-provideRouter",
             "What are the basics of the Angular Router (provideRouter, RouterLink, routerLinkActive)?",
             "Angular Router Basics — provideRouter, RouterLink, Navigation",
             "default", "easy", "high", 5,
             "Route config, RouterOutlet, RouterLink/routerLinkActive, provideRouter in standalone bootstrap, functional configuration",
             "Still using RouterModule.forRoot in standalone apps — prefer provideRouter for bootstrapApplication",
             "Show a provideRouter setup with lazy loading, functional guards, and component-based routing (v17+)",
             ANG_T,
             ["What is provideRouter?",
              "How do you redirect in the router?",
              "What does routerLinkActive do?",
              "What is RouterOutlet?"],
             "Angular Router Basics (2026) — provideRouter, RouterLink",
             "Master Angular Router v17+: provideRouter, RouterLink, routerLinkActive, RouterOutlet, and functional route config."),

            ("angular-route-guards-canactivate-candeactivate-resolve",
             "How do CanActivate, CanDeactivate, and Resolve route guards work in Angular?",
             "Angular Route Guards — CanActivate, CanDeactivate, Resolve",
             "default", "medium", "high", 7,
             "CanActivate: before navigation; CanDeactivate: before leaving; Resolve: pre-fetch data; functional guards (v15+) are the new recommendation",
             "Still writing class-based guards in Angular 16+ code — functional guards are simpler and tree-shakable",
             "Show functional CanActivate with inject(AuthService); a CanDeactivate 'unsaved changes' pattern",
             ANG_T,
             ["How do you write a functional guard?",
              "How do CanActivate and CanMatch differ?",
              "What are resolvers for?",
              "How do you test a route guard?"],
             "Angular Route Guards (2026) — CanActivate, Deactivate, Resolve",
             "Master Angular route guards: CanActivate, CanDeactivate, Resolve, functional (v15+) guards, and auth/unsaved-changes patterns."),
        ]),

        "lazy-loading-modules": ("Lazy Loading Modules", [
            ("lazy-loading-routes-angular-standalone",
             "How do you lazy-load routes in Angular (with standalone components)?",
             "Lazy Loading Routes in Angular — Standalone loadComponent",
             "default", "medium", "high", 5,
             "loadComponent for standalone components; loadChildren for module-based; webpack code-splits each; preloading strategies",
             "Not using lazy loading for a large app — initial bundle bloats; every big feature should live behind a lazy route",
             "Mention PreloadAllModules / QuicklinkStrategy for optimistic prefetching; standalone loadComponent for new code",
             ANG_T,
             ["What is the difference between loadComponent and loadChildren?",
              "What is QuicklinkStrategy?",
              "How does PreloadAllModules work?",
              "How do you debug a missing lazy chunk?"],
             "Lazy Loading Routes in Angular (2026) — Standalone loadComponent",
             "Lazy-load Angular routes: loadComponent (standalone) and loadChildren (module), preloading strategies, and bundle analysis."),
        ]),

        "resolvers-and-preloading": ("Resolvers & Preloading", [
            ("angular-resolver-pattern-data-prefetch",
             "What is an Angular Resolver? When should you use one?",
             "Angular Resolver Pattern — Prefetch Route Data",
             "default", "medium", "medium", 5,
             "Resolver fetches data BEFORE route activation so the component mounts with data available; ActivatedRoute.data$ reads it",
             "Using resolver for data that's better fetched inside the component with loading UI — resolvers block navigation; users see no progress",
             "Recommend resolvers only for critical path; for others, fetch in component and show skeleton loaders",
             ANG_T,
             ["When is a resolver better than fetching in ngOnInit?",
              "How do you write a functional resolver?",
              "How does the user know something is loading with a resolver?",
              "Can a resolver be canceled?"],
             "Angular Resolver Pattern (2026) — Prefetch Route Data",
             "Use Angular Resolvers wisely: prefetch route data, functional resolvers (v15+), and when in-component loading with skeletons is better."),
        ]),

        "scenario-based": ("Scenario-Based", []),
    },

    # -----------------------------------------------------------------------
    # M27 angular-state-testing (10 topics, 8 Qs)
    # -----------------------------------------------------------------------
    "angular-state-testing": {
        "ngrx-fundamentals": ("NgRx Fundamentals", [
            ("ngrx-store-actions-reducers-selectors",
             "What are the core concepts of NgRx Store? (Actions, Reducers, Selectors)",
             "NgRx Store Core Concepts — Actions, Reducers, Selectors",
             "default", "medium", "high", 7,
             "Single store, Actions (typed via createAction), Reducers (createReducer), Selectors (createSelector with memoization), dispatch",
             "Defining actions as strings instead of using createAction — loses type safety and autocomplete",
             "Show createFeature (v14+) that collapses actions/reducer/selectors into one cohesive block",
             ANG_T,
             ["What is createFeature in NgRx v14+?",
              "Why are selectors memoized?",
              "How does NgRx compare to Redux Toolkit?",
              "What is the difference between a feature state and the root state?"],
             "NgRx Store Core Concepts (2026) — Actions, Reducers, Selectors",
             "Master NgRx Store: Actions, Reducers, Selectors, createAction/createReducer/createSelector, and createFeature in v14+."),

            ("ngrx-vs-akita-vs-component-store",
             "NgRx Store vs NgRx Component Store vs Akita — which should you pick?",
             "NgRx Store vs Component Store vs Akita (2026) — Comparison",
             "comparison", "medium", "medium", 6,
             "NgRx Store: global, Redux-like; Component Store: local reactive state per component; Akita: simpler, entity-focused, less maintained in 2026",
             "Using NgRx Store for component-scoped state — heavy boilerplate; Component Store is designed for this",
             "Recommend NgRx Store for app-wide, Component Store for component-local, and caution on Akita's 2026 maintenance",
             ANG_T,
             ["When should you use Component Store over Store?",
              "Is Akita still maintained?",
              "How do you share state between Component Stores?",
              "What replaces Akita in modern Angular apps?"],
             "NgRx Store vs Component Store vs Akita (2026) — Choice",
             "Choose between NgRx Store, Component Store, and Akita: global vs local, maintenance status, and Angular state-management best practices."),
        ]),

        "ngrx-effects-and-selectors": ("NgRx Effects & Selectors", [
            ("ngrx-effects-async-side-effects",
             "What are NgRx Effects? How do they handle async side effects?",
             "NgRx Effects — Handling Async Side Effects Cleanly",
             "default", "medium", "high", 6,
             "createEffect for side effects; listens to actions, performs async work via RxJS operators, dispatches success/failure actions",
             "Putting side effects inside reducers — reducers must be pure; effects are the right home",
             "Show a loadUsers effect using switchMap → HTTP → map to success action + catchError → failure action",
             ANG_T,
             ["Why must reducers be pure?",
              "How do you unit-test an effect?",
              "How does createEffect differ from @Effect decorator?",
              "What is ofType?"],
             "NgRx Effects (2026) — Handling Async Side Effects Cleanly",
             "Master NgRx Effects: createEffect, ofType, RxJS switchMap, success/failure actions, and keeping reducers pure."),

            ("ngrx-selectors-memoization-createselector",
             "How do NgRx selectors work? Why are they memoized?",
             "NgRx Selectors — createSelector Memoization Explained",
             "default", "medium", "medium", 5,
             "createSelector combines selectors; reselect-style memoization prevents recomputation unless inputs change; combine with store.select",
             "Not memoizing selectors — template re-computes derived data on every change-detection cycle",
             "Show a featureSelector → property selectors → combined createSelector with OnPush component",
             ANG_T,
             ["What is reselect?",
              "How do feature selectors differ from global selectors?",
              "How do you combine multiple selectors?",
              "Can selectors have side effects?"],
             "NgRx Selectors (2026) — createSelector Memoization Explained",
             "Master NgRx selectors: createSelector, reselect-style memoization, feature vs global selectors, and integration with OnPush."),
        ]),

        "ngrx-component-store": ("NgRx Component Store", [
            ("ngrx-component-store-use-cases",
             "What is NgRx Component Store? When should you use it over NgRx Store?",
             "NgRx Component Store — Local Reactive State (When to Use)",
             "default", "medium", "medium", 5,
             "ComponentStore<T> for per-component reactive state; select for reads, updater for writes, effect for async; lighter than global Store",
             "Reaching for global NgRx Store for component-local state — leads to boilerplate that Component Store removes",
             "Recommend Component Store for data-heavy components (dashboards, wizards) where the state doesn't need to be global",
             ANG_T,
             ["What is the updater function?",
              "How does ComponentStore integrate with Signals?",
              "Can you share a ComponentStore across components?",
              "What's the diff from Akita store?"],
             "NgRx Component Store (2026) — Local Reactive State",
             "Master NgRx Component Store: ComponentStore<T>, select, updater, effect, and when it's lighter than global NgRx Store."),
        ]),

        "akita-and-alternatives": ("Akita & Alternatives", []),

        "testbed-and-unit-testing": ("TestBed & Unit Testing", [
            ("angular-testbed-testing-components",
             "How do you use TestBed to test Angular components?",
             "Angular TestBed — Unit Testing Components Guide",
             "default", "medium", "high", 6,
             "TestBed.configureTestingModule, createComponent, fixture.detectChanges, DebugElement queries (By.css), component interactions",
             "Calling ngOnInit manually after createComponent — detectChanges triggers it; avoid duplicate calls",
             "Show shallow vs deep tests; mention @angular/cdk/testing component harnesses as the modern interaction API",
             ANG_T,
             ["What are component harnesses?",
              "What is fixture.detectChanges for?",
              "How do you query child elements in a test?",
              "Shallow vs deep Angular tests — which is better?"],
             "Angular TestBed — Unit Testing Components (2026) — Guide",
             "Master Angular TestBed: configureTestingModule, DebugElement queries, component harnesses, and shallow vs deep tests."),
        ]),

        "karma-and-jasmine": ("Karma & Jasmine", [
            ("jasmine-spies-and-mocks",
             "What are Jasmine spies? How do you mock dependencies in Angular tests?",
             "Jasmine Spies & Mocks in Angular — createSpyObj Guide",
             "default", "medium", "medium", 5,
             "jasmine.createSpy, createSpyObj, spyOn, .and.returnValue / .and.callFake; providing mocks via TestBed",
             "Spying on a service method and then testing the component without providing the spy in TestBed — the real service is still used",
             "Mention Jest adoption in Angular 16+ experimentally and that Karma is in maintenance mode",
             ANG_T,
             ["Is Karma deprecated?",
              "How do you provide a mock service in TestBed?",
              "What is createSpyObj?",
              "Can you use Jest with Angular 16+?"],
             "Jasmine Spies & Mocks in Angular (2026) — Guide",
             "Master Jasmine spies in Angular: createSpy, createSpyObj, spyOn, and providing mocks via TestBed — plus Jest migration notes."),
        ]),

        "component-testing": ("Component Testing", []),
        "e2e-with-cypress": ("E2E with Cypress", []),
        "scenario-based": ("Scenario-Based", []),

        "comparisons": ("Comparisons", [
            ("ngrx-vs-ngxs-vs-akita-vs-component-store",
             "NgRx vs NgXs vs Akita vs Component Store — which state manager?",
             "NgRx vs NgXs vs Akita vs Component Store (2026) — Comparison",
             "comparison", "medium", "medium", 6,
             "NgRx: Redux-style, large ecosystem; NgXs: simpler decorator API; Akita: entity store (maintenance concerns); Component Store: per-component; Signals as alternative",
             "Picking Akita in 2026 without checking maintenance status — the project is less active than NgRx and Component Store",
             "Give 2026-accurate adoption: NgRx most popular; Component Store + Signals gaining; Akita declining",
             ANG_T,
             ["What is NgXs?",
              "Which state lib has the largest community in 2026?",
              "Can Signals replace an Angular state library?",
              "When is Component Store enough by itself?"],
             "NgRx vs NgXs vs Akita vs Component Store (2026) — Comparison",
             "Compare Angular state libraries in 2026: NgRx, NgXs, Akita, Component Store, and Signals — adoption, ergonomics, and recommendations."),
        ]),
    },
}
