"""
seed_jfi_phase1_data_integration_build.py
=========================================

P17 (Fullstack Integration) + P18 (Frontend Build & Delivery) question
scaffolds. Exports `INTEGRATION_BUILD_TOPIC_DEFS` which is merged into
master TOPIC_DEFS by `seed_jfi_phase1_data.py`.
"""

FS = ["amazon", "google", "meta", "uber", "flipkart", "razorpay", "swiggy"]
SEC = ["amazon", "google", "microsoft", "razorpay", "stripe", "paytm"]
BUILD = ["meta", "google", "netflix", "airbnb", "flipkart", "microsoft"]
FE = ["meta", "google", "airbnb", "netflix", "uber", "flipkart", "razorpay"]

INTEGRATION_BUILD_TOPIC_DEFS: dict = {

    # =========================================================================
    # PILLAR P17 — Fullstack Integration
    # =========================================================================

    # -----------------------------------------------------------------------
    # M34 api-integration (10 topics, 15 Qs)
    # -----------------------------------------------------------------------
    "api-integration": {
        "fetch-vs-axios": ("Fetch vs Axios", [
            ("fetch-vs-axios-comparison",
             "Fetch vs Axios — what are the differences and when should you use each?",
             "Fetch vs Axios (2026) — Differences, Interceptors, Progress",
             "comparison", "easy", "high", 6,
             "Fetch: browser-native, Promise-based; Axios: auto JSON, interceptors, progress events, wider feature set; bundle cost",
             "Picking Axios purely for JSON parsing in 2026 — Fetch is native and fine for most cases; measure Axios's bundle cost",
             "Mention modern alternatives: ky (tiny fetch wrapper), wretch, ofetch (Nuxt); note that Axios still wins for upload progress",
             FS,
             ["What is ky or ofetch?",
              "Does Fetch support upload progress?",
              "How do Axios interceptors compare to Fetch middleware?",
              "Does Fetch reject on 404?"],
             "Fetch vs Axios (2026) — Differences & Modern Alternatives",
             "Compare Fetch vs Axios: native vs library, interceptors, upload progress, bundle size, and modern alternatives like ky and ofetch."),
        ]),

        "interceptors-and-auth-headers": ("Interceptors & Auth Headers", [
            ("http-interceptors-auth-token-refresh",
             "How do you implement HTTP interceptors for auth headers and token refresh?",
             "HTTP Interceptors — Attach JWT & Auto Token Refresh",
             "default", "medium", "high", 7,
             "Request interceptor attaches Authorization header; response interceptor catches 401, refreshes, retries; queueing concurrent requests during refresh",
             "Kicking off N token-refresh calls when N requests fail at once with 401 — queue them and share one refresh",
             "Show a classic 'token-refresh queue' pattern with a single in-flight refresh Promise and failed-request queue",
             SEC,
             ["How do you prevent parallel token refreshes?",
              "Where do you store the refresh token?",
              "How do Angular HttpInterceptors differ from Axios interceptors?",
              "What if the refresh call itself returns 401?"],
             "HTTP Interceptors — Auth & Token Refresh (2026) Guide",
             "Implement HTTP interceptors for auth: attach JWT, refresh on 401, queue concurrent requests during refresh, and handle edge cases."),
        ]),

        "request-cancellation-and-abortcontroller": ("Request Cancellation & AbortController", [
            ("abortcontroller-fetch-cancellation",
             "How do you cancel fetch requests with AbortController?",
             "AbortController — Cancelling Fetch Requests in JavaScript",
             "default", "medium", "high", 5,
             "new AbortController(), pass signal to fetch, call controller.abort(); aborts propagate AbortError; useful in React on unmount / new-query",
             "Forgetting to abort on unmount — late responses then setState on an unmounted component",
             "Show an effect pattern: AbortController on effect run, abort in cleanup; AbortSignal.timeout() for timeouts (2024+)",
             FS,
             ["What is AbortSignal.timeout?",
              "How do you abort multiple requests together?",
              "Does Axios support AbortController?",
              "How does React Query handle cancellation?"],
             "AbortController & Fetch Cancellation (2026) — Full Guide",
             "Cancel fetch requests with AbortController: signals, timeouts, React useEffect cleanup, and Axios/React Query integration."),
        ]),

        "retries-and-backoff": ("Retries & Backoff", [
            ("retries-with-exponential-backoff-frontend",
             "How do you implement retries with exponential backoff in frontend API calls?",
             "Retries with Exponential Backoff — Frontend Fetch Patterns",
             "default", "medium", "high", 5,
             "Retry only on idempotent methods and certain status codes; exponential backoff + jitter to avoid thundering herd; max attempts cap",
             "Retrying 4xx client errors — usually pointless; retry 408, 429, 5xx with backoff",
             "Show a small retry(fetch, {retries:3, delay:exponential+jitter}) helper; mention React Query's built-in retry options",
             FS,
             ["Which status codes should you retry?",
              "What is jitter and why add it?",
              "How does React Query handle retries?",
              "Why not retry POST?"],
             "Retries with Exponential Backoff (2026) — Frontend Patterns",
             "Implement frontend retry logic: which status codes, exponential backoff + jitter, idempotency, and React Query's built-in retry options."),
        ]),

        "error-handling-patterns": ("Error Handling Patterns", [
            ("frontend-api-error-handling-patterns",
             "What are common frontend API error-handling patterns?",
             "Frontend API Error Handling — Result<T>, Boundaries, Toasts",
             "default", "medium", "high", 6,
             "Result<T, E> return types, global error interceptor, distinct UI states (loading/error/empty/success), retry affordances, user-friendly messages",
             "Showing raw server errors to users (stack traces, SQL hints) — always map errors to safe user messages and log raw in Sentry",
             "Show a Result-style fetch wrapper; integrate with Error Boundary + Sentry + toast; distinguish network vs server vs business errors",
             FS,
             ["What is the Result<T> pattern?",
              "How do you integrate error handling with Sentry?",
              "Why distinguish network vs server errors?",
              "How do React Query and SWR handle errors globally?"],
             "Frontend API Error Handling (2026) — Result, Boundaries, Sentry",
             "Master frontend API error handling: Result<T> pattern, error boundaries, safe user messages, Sentry logging, and React Query/SWR global errors."),
        ]),

        "cors-and-preflight": ("CORS & Preflight", [
            ("cors-preflight-frontend-debug",
             "How do you debug a CORS preflight failure from the frontend side?",
             "Debugging CORS Preflight Failures — Frontend Playbook",
             "default", "medium", "medium", 5,
             "Check response type (opaque), Access-Control-Allow-* headers, preflight OPTIONS request in DevTools Network tab; proxy as last resort",
             "Believing the frontend can fix CORS — only the server/gateway can allow it; frontend can only proxy or change origin",
             "Playbook: reproduce in DevTools, check preflight response, fix server or add a Vite/Next.js proxy for dev",
             FS,
             ["How does a dev proxy (Vite, Next.js rewrites) bypass CORS in dev?",
              "What's the difference between CORS and same-origin policy?",
              "What triggers a preflight?",
              "What is an opaque response?"],
             "Debugging CORS Preflight Failures (2026) — Frontend Playbook",
             "Debug CORS preflight failures from the frontend: DevTools Network tab, Access-Control-Allow-* headers, and dev proxy fallbacks."),
        ]),

        "caching-strategies-frontend": ("Caching Strategies (Frontend)", [
            ("frontend-caching-strategies-http-swr-rq-sw",
             "What frontend caching strategies can you use? (HTTP, React Query, SWR, Service Worker)",
             "Frontend Caching Strategies — HTTP, RQ, SWR, Service Worker",
             "default", "medium", "high", 7,
             "HTTP (Cache-Control, ETag, stale-while-revalidate); in-memory (React Query, SWR); persistent (Service Worker, IndexedDB); CDN edge caches",
             "Treating all caches the same — they have different invalidation models and TTLs; mismatches cause stale data bugs",
             "Map each cache to a use case; show how React Query + HTTP caching compose well (browser cache on the wire, RQ in memory)",
             FS,
             ["How does stale-while-revalidate work in HTTP?",
              "Can React Query read from a Service Worker cache?",
              "What's the difference between browser cache and React Query cache?",
              "How do you invalidate a CDN cache?"],
             "Frontend Caching Strategies (2026) — HTTP, RQ, SW, CDN",
             "Master frontend caching: HTTP, React Query/SWR, Service Worker/IndexedDB, CDN edge — layering them for speed without stale-data bugs."),
        ]),

        "graphql-clients-apollo-urql": ("GraphQL Clients — Apollo & urql", [
            ("apollo-client-basics-cache-fetch-policies",
             "What is Apollo Client? Explain the cache and fetch policies.",
             "Apollo Client Basics — InMemoryCache & Fetch Policies",
             "default", "medium", "medium", 6,
             "useQuery, useMutation, InMemoryCache with normalized entities, fetch policies (cache-first, network-only, cache-and-network)",
             "Using cache-first and wondering why the list doesn't reflect a new item — missing cache update logic on mutation",
             "Compare Apollo with urql and Relay; mention GraphQL Code Generator for typed hooks",
             FS,
             ["What is GraphQL Code Generator?",
              "What is the difference between Apollo and urql?",
              "How do you update the cache after a mutation?",
              "What is a normalized cache?"],
             "Apollo Client Basics (2026) — Cache & Fetch Policies",
             "Master Apollo Client: useQuery, useMutation, normalized InMemoryCache, fetch policies, and mutation cache updates."),

            ("apollo-vs-urql-vs-relay",
             "Apollo vs urql vs Relay — which GraphQL client should you pick?",
             "Apollo vs urql vs Relay (2026) — GraphQL Client Comparison",
             "comparison", "medium", "medium", 6,
             "Apollo: mature, feature-rich, big; urql: small, modular, exchanges; Relay: Meta-scale, opinionated, compiler-based",
             "Picking Relay without an existing compiler/fragment culture — its strengths come with a steep ramp",
             "Give 2026 recommendations: Apollo for most apps, urql for perf-sensitive frontends, Relay for massive Meta-scale codebases",
             FS,
             ["What is urql's exchange system?",
              "When is Relay worth the learning curve?",
              "Which has the smallest bundle?",
              "How do they compare to REST + React Query?"],
             "Apollo vs urql vs Relay (2026) — GraphQL Client Comparison",
             "Compare GraphQL clients Apollo, urql, Relay: bundle, features, Relay compiler, and when to pick each over REST + React Query."),
        ]),

        "scenario-based": ("Scenario-Based", [
            ("design-frontend-fetch-wrapper",
             "How would you design a reusable frontend fetch wrapper? (timeout, auth, retries, typing)",
             "Design a Frontend Fetch Wrapper — Timeout, Auth, Retries, Types",
             "architecture", "hard", "high", 8,
             "Generic typing, AbortSignal.timeout, auth interceptor, retry + backoff, error normalization, JSON auto-parse, base URL handling",
             "Rolling a fetch wrapper without cancellation — leaks requests when the component unmounts",
             "Layered design: low-level httpRaw → httpJson → api.* per-endpoint typed helpers; reference ky/wretch as real-world inspirations",
             FS,
             ["How do you structure per-endpoint typed helpers?",
              "How do you test a fetch wrapper?",
              "Should you return Result<T> or throw?",
              "How do you share types with the backend?"],
             "Design a Frontend Fetch Wrapper (2026) — Full Architecture",
             "Design a reusable frontend fetch wrapper: typed endpoints, timeouts, retries, auth interceptor, error normalization, and testability."),
        ]),

        "comparisons": ("Comparisons", [
            ("rest-vs-graphql-frontend-perspective",
             "REST vs GraphQL from a frontend perspective — which to pick?",
             "REST vs GraphQL (2026) — Frontend Developer Perspective",
             "comparison", "medium", "high", 6,
             "REST: simple, cacheable HTTP; GraphQL: precise fetching, fewer round trips, complex caching, extra tooling",
             "Assuming GraphQL always reduces over-fetching — without careful field selection and cache setup, it can perform worse",
             "Frame the decision by team size/ecosystem; mention tRPC as a third option for TypeScript full-stack teams",
             FS,
             ["What is tRPC?",
              "How does caching differ between REST and GraphQL?",
              "Is GraphQL dying in 2026?",
              "When does REST win?"],
             "REST vs GraphQL (2026) — Frontend Developer Perspective",
             "Compare REST vs GraphQL for frontends: over-fetching, caching, tooling, tRPC alternative, and 2026 adoption."),
        ]),
    },

    # -----------------------------------------------------------------------
    # M35 auth-flows-frontend (9 topics, 15 Qs)
    # -----------------------------------------------------------------------
    "auth-flows-frontend": {
        "jwt-storage-localstorage-vs-cookie": ("JWT Storage — localStorage vs Cookie", [
            ("jwt-localstorage-vs-httponly-cookie",
             "Should you store JWT in localStorage or an HttpOnly cookie?",
             "JWT Storage — localStorage vs HttpOnly Cookie (XSS vs CSRF)",
             "comparison", "medium", "high", 7,
             "localStorage exposed to XSS; HttpOnly cookies immune to JS but vulnerable to CSRF (mitigated by SameSite + CSRF tokens)",
             "Saying 'localStorage is always insecure' — the real trade-off is XSS vs CSRF; each has mitigations and contexts",
             "Recommend HttpOnly + SameSite=Lax/Strict + CSRF tokens for browser apps; localStorage only when cookie delivery is impossible (cross-origin edge cases)",
             SEC,
             ["What is the SameSite cookie attribute?",
              "How do you mitigate CSRF with SameSite?",
              "What is the double-submit CSRF pattern?",
              "How do you handle auth in a cross-origin SPA?"],
             "JWT Storage — localStorage vs HttpOnly Cookie (2026)",
             "Choose JWT storage: localStorage (XSS risk) vs HttpOnly cookie (CSRF risk, mitigations), SameSite, CSRF tokens, and cross-origin SPAs."),

            ("jwt-structure-header-payload-signature",
             "What is the structure of a JWT? Explain header, payload, and signature.",
             "JWT Structure Explained — Header, Payload, Signature",
             "default", "easy", "high", 5,
             "Three base64url parts separated by dots; header.algorithm + type; payload claims (iss, sub, exp, aud); signature binds them",
             "Reading the payload and trusting it without verifying the signature — the payload is base64, not encrypted, and modifiable without signature check",
             "Call out none-algorithm attacks and show a 5-line decode function for the payload (for client-side UX, not trust)",
             SEC,
             ["Is JWT encrypted or just signed?",
              "What is the 'none' algorithm attack?",
              "What are standard claims (iss, sub, exp)?",
              "How do refresh tokens differ from access tokens?"],
             "JWT Structure Explained (2026) — Header, Payload, Signature",
             "Master JWT structure: base64url header/payload/signature, standard claims, 'none' algorithm attack, and why payload isn't encrypted."),
        ]),

        "oauth2-flows-pkce-and-code": ("OAuth2 Flows — PKCE & Code", [
            ("oauth2-authorization-code-flow-pkce",
             "Explain the OAuth 2.0 Authorization Code flow with PKCE. Why is PKCE required for SPAs?",
             "OAuth 2.0 Authorization Code + PKCE — SPA Auth Flow",
             "architecture", "hard", "high", 8,
             "Code flow: auth request → code → token exchange; PKCE adds code_verifier/code_challenge to prevent code-interception attacks for public clients",
             "Using the implicit flow for SPAs in 2026 — deprecated; Auth Code + PKCE is the recommended flow",
             "Walk through each step; note auth0, Okta, Keycloak all default to PKCE for SPAs now",
             SEC,
             ["What is the implicit flow and why is it deprecated?",
              "Where do you store the code_verifier?",
              "How does the code_challenge work?",
              "What is state parameter for?"],
             "OAuth 2.0 Authorization Code + PKCE (2026) — SPA Auth Flow",
             "Master the OAuth 2.0 Authorization Code flow with PKCE: steps, code_verifier/challenge, state parameter, and why it replaces Implicit flow for SPAs."),

            ("oauth2-implicit-flow-deprecation",
             "Why is the OAuth 2.0 Implicit flow deprecated?",
             "Why the OAuth 2.0 Implicit Flow Is Deprecated (2026)",
             "default", "medium", "medium", 4,
             "Access tokens in URL fragments (leakable, not confidential); no client secret; PKCE + code flow is the secure replacement",
             "Still defending Implicit as 'simpler' — security community (RFC 9700) explicitly recommends against it since 2019",
             "Reference OAuth 2.1 (draft) which removes Implicit entirely and mandates PKCE",
             SEC,
             ["What is OAuth 2.1?",
              "Why are URL fragments unsafe for tokens?",
              "What migration path does Auth0/Okta recommend?",
              "When is Implicit still acceptable?"],
             "OAuth 2.0 Implicit Flow Deprecation (2026) — Why & Migration",
             "Understand why the OAuth 2.0 Implicit flow is deprecated: URL fragment leaks, OAuth 2.1 direction, PKCE + Code as the secure replacement."),
        ]),

        "oidc-and-id-tokens": ("OIDC & ID Tokens", [
            ("oidc-vs-oauth2-id-vs-access-token",
             "OIDC vs OAuth 2.0 — what's the difference? ID token vs access token vs refresh token.",
             "OIDC vs OAuth 2.0 — ID, Access & Refresh Tokens Explained",
             "comparison", "medium", "high", 7,
             "OAuth 2.0 = authorization; OIDC = authentication layer on top (adds id_token); access token for API; refresh token for renewal",
             "Treating OIDC and OAuth as interchangeable — OAuth doesn't authenticate; OIDC adds the authN layer",
             "Explain 'OAuth for authZ, OIDC for authN' sound bite; show the id_token shape (claims about the user)",
             SEC,
             ["What is the id_token?",
              "What is the difference between authN and authZ?",
              "Why do you need a refresh token?",
              "What are the OIDC scopes?"],
             "OIDC vs OAuth 2.0 (2026) — ID vs Access vs Refresh Token",
             "Master OIDC vs OAuth 2.0: authentication vs authorization, id_token claims, access/refresh tokens, and scopes."),
        ]),

        "sso-saml-flows": ("SSO & SAML Flows", [
            ("saml-vs-oauth2-oidc-sso",
             "SAML vs OAuth 2.0/OIDC for SSO — when should you use each?",
             "SAML vs OAuth 2.0 / OIDC for SSO — Comparison",
             "comparison", "medium", "medium", 6,
             "SAML: XML assertions, enterprise, legacy; OIDC: JSON + JWT, modern, SPA-friendly; enterprise often SAML, SaaS often OIDC",
             "Assuming SAML is obsolete — it's still dominant in large enterprise IT; SaaS may need both",
             "Recommend building OIDC-first with SAML fallback via an identity broker (Auth0, Keycloak) for enterprise integration",
             SEC,
             ["What is an identity broker?",
              "How do Auth0/Okta support both protocols?",
              "What is a SAML assertion?",
              "Why is OIDC better for SPAs?"],
             "SAML vs OAuth 2.0 / OIDC (2026) — SSO Comparison",
             "Compare SAML vs OAuth 2.0/OIDC for SSO: enterprise vs SaaS, assertions vs JWT, and identity-broker strategies."),
        ]),

        "refresh-tokens-and-silent-renew": ("Refresh Tokens & Silent Renewal", [
            ("refresh-token-rotation-silent-renew-spa",
             "How do refresh-token rotation and silent renewal work in SPAs?",
             "Refresh Token Rotation & Silent Renew — SPA Auth Patterns",
             "default", "hard", "high", 7,
             "Short-lived access + long-lived refresh; rotate refresh on each use; detect reuse as breach; silent renew via hidden iframe or refresh call",
             "Storing a long-lived access token in localStorage — defeats the point of short-lived access tokens",
             "Show a silent-renew pattern with a refresh queue to prevent parallel calls; mention refresh-token family to detect replay",
             SEC,
             ["What is refresh-token rotation?",
              "How do you detect refresh-token reuse?",
              "How does silent renew via iframe work?",
              "What are the risks of long-lived refresh tokens?"],
             "Refresh Token Rotation & Silent Renew (2026) — SPA Patterns",
             "Master refresh-token rotation and silent renewal in SPAs: short-lived access, rotation, reuse detection, and iframe-based renew."),
        ]),

        "session-management-and-logout": ("Session Management & Logout", [
            ("sso-logout-and-session-expiry",
             "How do you handle logout in SSO environments? What is session expiry vs active logout?",
             "SSO Logout & Session Expiry — Front-Channel vs Back-Channel",
             "default", "medium", "medium", 6,
             "Local logout (clear tokens); single logout (SLO) via front-channel iframe or back-channel OIDC; clearing SSO session at IdP",
             "Clearing local tokens but leaving the IdP session alive — the next login re-authenticates silently, surprising the user",
             "Explain front-channel vs back-channel logout in OIDC and why back-channel is more reliable",
             SEC,
             ["What is OIDC front-channel logout?",
              "What is OIDC back-channel logout?",
              "Why does clearing tokens not fully log a user out?",
              "How do you force session expiry on all tabs?"],
             "SSO Logout & Session Expiry (2026) — Front vs Back-Channel",
             "Implement SSO logout: front-channel vs back-channel OIDC, local vs IdP logout, session expiry across tabs, and user expectations."),
        ]),

        "xss-csrf-frontend-defenses": ("XSS & CSRF — Frontend Defenses", [
            ("xss-attacks-types-defenses",
             "What is XSS? Types, impact, and how to defend against it.",
             "XSS — Types (Stored, Reflected, DOM) & Defenses",
             "default", "medium", "high", 7,
             "Stored, reflected, DOM-based XSS; output encoding, CSP, safe sinks (textContent, not innerHTML), framework auto-escaping",
             "Using dangerouslySetInnerHTML in React with user content without sanitization — a direct XSS vulnerability",
             "Walk through DOMPurify for sanitization; CSP nonces; trusted-types on modern browsers",
             SEC,
             ["What is DOMPurify?",
              "What is Trusted Types?",
              "How does React defend against XSS by default?",
              "What is a CSP nonce?"],
             "XSS — Types, Defenses & CSP (2026) — Frontend Security",
             "Master XSS attacks and defenses: stored/reflected/DOM types, DOMPurify, React's auto-escaping, CSP, and Trusted Types."),

            ("csrf-attacks-samesite-csrf-tokens",
             "What is CSRF? How do SameSite cookies and CSRF tokens prevent it?",
             "CSRF — Attacks & Defenses (SameSite, CSRF Token, Origin Header)",
             "default", "medium", "high", 6,
             "CSRF abuses browser auto-submitted cookies; defenses: SameSite=Lax/Strict (default), double-submit CSRF tokens, Origin header check",
             "Relying only on CSRF tokens without SameSite — SameSite catches most cases cheaply; tokens defend against edge cases",
             "Note SameSite=Lax became default in Chrome 80+ (2020); modern apps rely on it first",
             SEC,
             ["What is the double-submit CSRF pattern?",
              "Why did Chrome default to SameSite=Lax?",
              "Is SameSite=Strict always better?",
              "How does the Origin header help?"],
             "CSRF — Attacks & Defenses (2026) — SameSite, Tokens, Origin",
             "Master CSRF defenses: SameSite=Lax/Strict defaults, double-submit tokens, Origin header, and when each layer matters."),

            ("content-security-policy-csp-basics",
             "What is Content Security Policy (CSP)? How do you configure it?",
             "Content Security Policy (CSP) — Nonces, strict-dynamic, Defenses",
             "default", "medium", "high", 6,
             "HTTP header listing allowed sources; script-src, style-src, img-src, connect-src; nonce/hash or strict-dynamic for inline scripts",
             "Adding unsafe-inline to script-src — defeats XSS protection; use nonces or strict-dynamic instead",
             "Recommend CSP Level 3 with strict-dynamic + nonce as the modern baseline; report-uri / report-to for monitoring",
             SEC,
             ["What is strict-dynamic in CSP?",
              "How do nonces work in CSP?",
              "What is the report-uri directive?",
              "Does CSP work in iframes?"],
             "Content Security Policy (2026) — Nonces, strict-dynamic, Reports",
             "Configure Content Security Policy: script-src, nonces, strict-dynamic, report-to, and why unsafe-inline defeats the purpose."),
        ]),

        "secure-cookie-flags": ("Secure Cookie Flags", [
            ("secure-cookie-flags-httponly-samesite-secure",
             "What cookie flags should you set for security? (HttpOnly, Secure, SameSite)",
             "Secure Cookie Flags — HttpOnly, Secure, SameSite Explained",
             "default", "easy", "high", 4,
             "HttpOnly: blocks JS access; Secure: HTTPS-only; SameSite=Lax/Strict: mitigates CSRF; Domain/Path: scope; __Host-/__Secure- prefixes",
             "Setting Secure without HTTPS in production — the cookie will be silently dropped by browsers",
             "Mention the __Host- prefix (enforces Secure + path=/ + no domain) as the strictest modern standard",
             SEC,
             ["What does the __Host- cookie prefix enforce?",
              "What is SameSite=None and when do you need it?",
              "Can HttpOnly cookies be sent in fetch?",
              "What happens if you set Secure on http://?"],
             "Secure Cookie Flags (2026) — HttpOnly, Secure, SameSite",
             "Set secure cookie flags: HttpOnly, Secure, SameSite=Lax/Strict/None, __Host- prefix, and common pitfalls."),
        ]),

        "scenario-based": ("Scenario-Based", []),
    },

    # -----------------------------------------------------------------------
    # M36 realtime-uploads (8 topics, 8 Qs)
    # -----------------------------------------------------------------------
    "realtime-uploads": {
        "websockets-basics": ("WebSockets Basics", [
            ("websockets-basics-handshake-lifecycle",
             "What are WebSockets? How does the handshake and lifecycle work?",
             "WebSockets Explained — Handshake, Lifecycle, Use Cases",
             "default", "medium", "high", 6,
             "HTTP upgrade to ws(s) protocol; full-duplex persistent connection; events: open/message/close/error; heartbeats for liveness",
             "Not implementing reconnect-with-backoff — WebSockets disconnect on network changes, sleep, idle timeouts",
             "Recommend Socket.io or sockette for reconnect + fallback; SSE as a lighter alternative when server-only push is needed",
             FS,
             ["What is the WebSocket handshake?",
              "How do you handle disconnects?",
              "What is Socket.io and how does it differ from raw WebSockets?",
              "When should you prefer SSE over WebSockets?"],
             "WebSockets Explained (2026) — Handshake, Reconnect, Socket.io",
             "Master WebSockets: HTTP upgrade handshake, lifecycle, reconnect-with-backoff, Socket.io/sockette, and SSE trade-offs."),
        ]),

        "stomp-and-sockjs": ("STOMP & SockJS", [
            ("stomp-over-websockets-with-spring",
             "What is STOMP over WebSockets? How does it integrate with Spring?",
             "STOMP over WebSockets & Spring — Pub/Sub Messaging Guide",
             "default", "medium", "medium", 5,
             "STOMP framing on top of WS; pub/sub with destinations (/topic, /queue); Spring's @MessageMapping; SockJS polyfill fallback",
             "Exposing raw destinations without auth — clients can subscribe to any topic; add interceptor-level authorization",
             "Show an Angular/React client with @stomp/stompjs connecting to Spring's /ws endpoint; broker relay for scaling",
             FS,
             ["What is SockJS and when is it needed?",
              "How do you authorize STOMP subscriptions in Spring?",
              "How do you scale STOMP across multiple servers?",
              "What is a STOMP frame?"],
             "STOMP over WebSockets & Spring (2026) — Pub/Sub Guide",
             "Master STOMP over WebSockets with Spring: destinations, @MessageMapping, SockJS fallback, auth, and multi-server scaling."),
        ]),

        "server-sent-events": ("Server-Sent Events", [
            ("sse-vs-websockets-server-push",
             "SSE vs WebSockets — when should you use each for server push?",
             "SSE vs WebSockets — Server Push Comparison",
             "comparison", "medium", "high", 5,
             "SSE: one-way (server→client), HTTP, auto-reconnect, simple; WS: bidirectional, binary, more complex",
             "Using WebSockets for read-only streams (notifications, stock tickers) — SSE is simpler and has built-in reconnect",
             "Mention SSE's event IDs for resume, EventSource retry, and limitations (HTTP/1.1 6-connection cap per origin; HTTP/2 fixes this)",
             FS,
             ["What is the EventSource API?",
              "How does SSE reconnection work?",
              "Why is SSE limited in HTTP/1.1?",
              "Can you send binary with SSE?"],
             "SSE vs WebSockets (2026) — Server Push Comparison",
             "Compare SSE vs WebSockets: one-way vs bidirectional, reconnection, HTTP/1.1 limits, and when SSE's simplicity wins."),
        ]),

        "long-polling-and-fallbacks": ("Long Polling & Fallbacks", [
            ("long-polling-vs-short-polling-vs-ws",
             "Long polling vs short polling vs WebSockets — differences and when to use each?",
             "Long Polling vs Short Polling vs WebSockets — Comparison",
             "comparison", "medium", "medium", 5,
             "Short polling: periodic GET; long polling: server holds request until event/timeout; WS: persistent bidirectional; SSE: server push over HTTP",
             "Choosing short polling for real-time UX — latency = poll interval; long polling or WS is needed for truly live updates",
             "Decision tree: one-way and simple → SSE; bidirectional or binary → WS; legacy / through corporate proxies → long polling",
             FS,
             ["When is short polling acceptable?",
              "How does long polling handle timeouts?",
              "Why do corporate proxies sometimes block WebSockets?",
              "How does Socket.io fall back between transports?"],
             "Long Polling vs Short Polling vs WebSockets (2026)",
             "Choose between short polling, long polling, SSE, and WebSockets: latency, proxy compatibility, and real-time UX trade-offs."),
        ]),

        "file-upload-multipart": ("File Upload — Multipart", [
            ("multipart-file-upload-frontend-basics",
             "How do you upload files with multipart/form-data from the frontend?",
             "Multipart File Upload (Frontend) — FormData & Progress",
             "default", "easy", "high", 5,
             "FormData with file fields, Content-Type set automatically (with boundary), upload progress via XHR or axios, Fetch limitations",
             "Setting Content-Type: multipart/form-data manually — breaks the boundary; leave it to the browser",
             "Show FormData usage with axios onUploadProgress; mention the 100MB practical limit for simple uploads",
             FS,
             ["Why shouldn't you set Content-Type manually for multipart?",
              "How do you validate file types?",
              "How does the backend parse multipart?",
              "What's the practical upload size limit?"],
             "Multipart File Upload (Frontend) (2026) — FormData & Progress",
             "Upload files with multipart/form-data: FormData, auto Content-Type, XHR/axios progress, type validation, and size limits."),
        ]),

        "chunked-and-resumable-uploads": ("Chunked & Resumable Uploads", [
            ("tus-resumable-uploads-chunked",
             "How do resumable/chunked uploads work? (tus protocol, S3 multipart)",
             "Resumable Uploads — tus Protocol & S3 Multipart",
             "default", "medium", "medium", 5,
             "Split file into chunks, upload with offset tracking, resume on failure; tus protocol HEAD/PATCH; S3 multipart for large S3 objects",
             "Building a custom resume protocol instead of using tus or S3 multipart — reinventing a solved wheel",
             "Recommend tus-js-client or Uppy for production; S3 multipart for direct-to-S3 browser uploads with presigned URLs",
             FS,
             ["What is the tus protocol?",
              "What is Uppy?",
              "How does S3 multipart work from the browser?",
              "How large can a chunk be?"],
             "Resumable Uploads (2026) — tus Protocol, S3 Multipart, Uppy",
             "Implement resumable uploads: tus protocol, tus-js-client/Uppy, S3 multipart with presigned URLs, and chunk-offset tracking."),
        ]),

        "file-download-and-streaming": ("File Download & Streaming", [
            ("file-download-streaming-fetch-blob",
             "How do you download large files with streaming in the browser?",
             "File Download & Streaming in the Browser — Fetch, Blob, File System Access API",
             "default", "medium", "medium", 5,
             "fetch + ReadableStream for progress; Blob URLs via createObjectURL; File System Access API for direct disk writes (large files)",
             "Loading a 2GB file into memory via response.blob() — crashes mobile; use streaming writes to disk",
             "Recommend the File System Access API (2024+ baseline) for huge downloads; streams-based download helpers",
             FS,
             ["What is the File System Access API?",
              "How do you show download progress?",
              "What is createObjectURL?",
              "Why can large blobs crash mobile browsers?"],
             "File Download & Streaming (2026) — Fetch, Blob, FS Access API",
             "Stream large file downloads: fetch + ReadableStream for progress, Blob URLs, and the File System Access API for direct disk writes."),
        ]),

        "scenario-based": ("Scenario-Based", []),
    },

    # =========================================================================
    # PILLAR P18 — Frontend Build & Delivery
    # =========================================================================

    # -----------------------------------------------------------------------
    # M49 frontend-build-tools (11 topics, 13 Qs)
    # -----------------------------------------------------------------------
    "frontend-build-tools": {
        "npm-yarn-and-pnpm": ("npm, yarn & pnpm", [
            ("npm-vs-yarn-vs-pnpm",
             "npm vs yarn vs pnpm — what are the differences?",
             "npm vs yarn vs pnpm (2026) — Comparison & Recommendation",
             "comparison", "easy", "high", 6,
             "Install speed, disk usage, monorepo support, lockfile formats; pnpm uses content-addressed store + hard links for minimal disk",
             "Stating 'yarn is always faster' — modern npm 8+ is competitive; pnpm is often the fastest and smallest on disk",
             "Give 2026-accurate guidance: pnpm for monorepos/disk; npm for defaults; yarn berry (pnp) for specific ecosystems",
             BUILD,
             ["What is Yarn PnP?",
              "Why is pnpm disk-efficient?",
              "What is a workspace?",
              "Which lockfile is cross-compatible?"],
             "npm vs yarn vs pnpm (2026) — Full Comparison",
             "Compare npm, yarn, pnpm: install speed, disk usage, monorepo support (workspaces), Yarn PnP, and 2026 recommendations."),

            ("pnpm-disk-efficiency-hard-links",
             "Why is pnpm so disk-efficient? Explain content-addressed store and hard links.",
             "Why pnpm Is Disk-Efficient — Content-Addressed Store Explained",
             "default", "medium", "medium", 4,
             "Global content-addressable store; hard links from project node_modules; shared across projects; strict non-flat layout",
             "Assuming pnpm 'just works' like npm — strict non-flat layout can expose phantom-dependency bugs that npm hides",
             "Explain why phantom dependencies are actually a feature (catches reliance on unlisted packages)",
             BUILD,
             ["What are phantom dependencies?",
              "Why is pnpm's node_modules layout strict?",
              "What is a hard link?",
              "Does pnpm work on Windows?"],
             "Why pnpm Is Disk-Efficient (2026) — Content-Addressed Store",
             "Understand pnpm's disk efficiency: content-addressed store, hard links, strict non-flat node_modules, and phantom dependency detection."),
        ]),

        "package-json-and-lockfiles": ("package.json & Lockfiles", [
            ("package-json-dependencies-devdependencies-peerdependencies",
             "dependencies vs devDependencies vs peerDependencies in package.json — what's the difference?",
             "Dependencies, DevDependencies & PeerDependencies — Explained",
             "comparison", "easy", "high", 5,
             "dependencies: runtime; devDependencies: build/test; peerDependencies: expected host (libraries); optionalDependencies: non-critical",
             "Putting React in dependencies of a React plugin — it should be peerDependencies to avoid duplicate React instances",
             "Mention npm 7+ installs peerDeps automatically (a breaking change from npm 6)",
             BUILD,
             ["Why should libraries use peerDependencies?",
              "What happens with duplicate React versions?",
              "Does npm 7+ install peerDependencies automatically?",
              "What are optionalDependencies?"],
             "Dependencies vs Dev vs Peer (2026) — package.json Explained",
             "Master package.json dependency types: dependencies, devDependencies, peerDependencies, optionalDependencies, and duplicate-package bugs."),

            ("lockfiles-package-lock-yarn-pnpm",
             "What do package-lock.json, yarn.lock, and pnpm-lock.yaml do? Why are they critical?",
             "Lockfiles Explained — package-lock, yarn.lock, pnpm-lock",
             "default", "easy", "high", 4,
             "Record exact resolved versions + integrity hashes; enable reproducible installs across machines; commit to VCS; don't hand-edit",
             "Running npm install and overwriting the lockfile with a looser match — use npm ci in CI for deterministic installs",
             "Recommend npm ci / yarn install --frozen-lockfile / pnpm install --frozen-lockfile in CI for deterministic builds",
             BUILD,
             ["What's the difference between npm install and npm ci?",
              "Why do you commit lockfiles?",
              "What is integrity hashing?",
              "Can you share lockfiles across package managers?"],
             "Lockfiles Explained (2026) — package-lock, yarn, pnpm",
             "Master lockfiles: package-lock.json, yarn.lock, pnpm-lock.yaml, npm ci vs install, integrity, and deterministic CI builds."),
        ]),

        "semver-and-dependency-management": ("SemVer & Dependency Management", [
            ("semver-caret-tilde-exact-explained",
             "How does SemVer work? What do ^, ~, and exact versions mean?",
             "SemVer Explained — Caret (^), Tilde (~), Exact Versions",
             "default", "easy", "high", 4,
             "major.minor.patch; ^ allows minor/patch; ~ allows patch only; exact pins to one version; pre-release and build metadata",
             "Treating ^0.x.y the same as ^1.x.y — in 0.x, ^ allows only patch bumps (API considered unstable)",
             "Show dependabot / renovate for automated version bumps; mention SemVer pitfalls with ESM-only transitions",
             BUILD,
             ["What does ^0.x.y allow?",
              "What is Renovate?",
              "How do pre-release versions sort?",
              "When do you use exact versions?"],
             "SemVer Explained (2026) — Caret, Tilde, Exact Pinning",
             "Master SemVer: major.minor.patch, ^, ~, exact pinning, 0.x special behavior, Renovate/Dependabot, and pre-release ordering."),
        ]),

        "webpack-config-and-loaders": ("Webpack Config & Loaders", [
            ("webpack-loaders-vs-plugins",
             "What is the difference between webpack loaders and plugins?",
             "Webpack Loaders vs Plugins — Differences & Examples",
             "comparison", "medium", "high", 5,
             "Loaders transform individual files (babel-loader, css-loader); plugins hook into the build lifecycle (HtmlWebpackPlugin, MiniCssExtractPlugin)",
             "Confusing loaders with plugins — loaders are per-file; plugins orchestrate the whole build",
             "Mention Vite/esbuild/Turbopack era but Webpack still dominates large legacy codebases",
             BUILD,
             ["What does babel-loader do?",
              "What is HtmlWebpackPlugin for?",
              "How does Vite differ from Webpack?",
              "What is Turbopack?"],
             "Webpack Loaders vs Plugins (2026) — Differences & Examples",
             "Compare Webpack loaders vs plugins: file-level transforms vs lifecycle hooks, examples, and Webpack vs Vite/Turbopack in 2026."),
        ]),

        "vite-and-esbuild": ("Vite & esbuild", [
            ("vite-vs-webpack-speed-architecture",
             "Vite vs Webpack — why is Vite so much faster? (ESM + esbuild + Rollup)",
             "Vite vs Webpack (2026) — Why Vite Is Faster",
             "comparison", "medium", "high", 6,
             "Vite uses native ESM + esbuild dev server (no bundling in dev), Rollup for prod; Webpack bundles everything always; HMR differences",
             "Assuming Vite is only for small projects — it's production-ready for Angular 17+ and Nuxt, and widely adopted in 2026",
             "Mention Turbopack (Next.js) and Rspack (Rust webpack-compatible) as the next frontier",
             BUILD,
             ["What is Turbopack?",
              "What is Rspack?",
              "Why does Vite's dev server skip bundling?",
              "Is esbuild faster than swc?"],
             "Vite vs Webpack (2026) — Why Vite Is Faster",
             "Compare Vite vs Webpack: native ESM, esbuild dev, Rollup prod, HMR, and modern alternatives like Turbopack and Rspack."),
        ]),

        "babel-and-swc": ("Babel & swc", [
            ("babel-vs-swc-vs-esbuild-speed",
             "Babel vs swc vs esbuild — speed and compatibility trade-offs?",
             "Babel vs swc vs esbuild (2026) — Speed & Compatibility",
             "comparison", "medium", "high", 5,
             "Babel: most plugins, slowest; swc: Rust, fast, TS + minify; esbuild: Go, fastest, some feature gaps",
             "Switching to swc/esbuild without checking plugin support — Babel's huge plugin ecosystem covers edge cases not yet in the newcomers",
             "Recommend swc for Next.js/React, esbuild for raw speed, Babel when a specific plugin is needed",
             BUILD,
             ["Why does Next.js use swc?",
              "Is Babel dead in 2026?",
              "When does esbuild's feature gap matter?",
              "How do you write a swc plugin?"],
             "Babel vs swc vs esbuild (2026) — Speed & Plugin Ecosystems",
             "Compare Babel, swc, and esbuild: speed, plugin ecosystems, Next.js adoption, and when each still wins in 2026."),
        ]),

        "tree-shaking-and-code-splitting": ("Tree Shaking & Code Splitting", [
            ("tree-shaking-code-splitting-bundle-size",
             "How do tree shaking and code splitting reduce bundle size?",
             "Tree Shaking & Code Splitting — Cut Frontend Bundle Size",
             "default", "medium", "high", 6,
             "Tree shaking removes unused ESM exports; code splitting breaks bundles into lazy chunks via dynamic import(); route-based + component-based splitting",
             "Importing a whole lodash library (import _ from 'lodash') instead of single methods — kills tree shaking",
             "Recommend lodash-es over lodash, per-method imports, and chunk analysis with rollup-plugin-visualizer or webpack-bundle-analyzer",
             BUILD,
             ["What is webpack-bundle-analyzer?",
              "Why doesn't CommonJS tree-shake well?",
              "What is dynamic import()?",
              "What is the sideEffects field in package.json?"],
             "Tree Shaking & Code Splitting (2026) — Cut Bundle Size",
             "Reduce frontend bundle size with tree shaking and code splitting: ESM, dynamic import(), sideEffects, and bundle analyzers."),
        ]),

        "module-federation": ("Module Federation", [
            ("module-federation-micro-frontends",
             "What is Module Federation? How does it enable micro-frontends?",
             "Module Federation — Webpack Micro-Frontends Explained",
             "default", "hard", "medium", 6,
             "Webpack 5 MF shares modules across separately-deployed apps at runtime; host/remote model; shared dependencies to avoid duplication",
             "Using Module Federation without planning shared deps — duplicate React versions cause hook errors",
             "Mention native-federation (for Vite/Angular), and the micro-frontend design trade-offs (autonomy vs coordination cost)",
             BUILD,
             ["What is native-federation?",
              "How do you share React across remotes?",
              "What are the downsides of micro-frontends?",
              "What is the host vs remote model?"],
             "Module Federation & Micro-Frontends (2026) — Webpack Guide",
             "Master Module Federation for micro-frontends: Webpack 5 host/remote, shared deps, native-federation for Vite, and architectural trade-offs."),
        ]),

        "monorepo-tools-nx-turborepo": ("Monorepo Tools — Nx & Turborepo", [
            ("nx-vs-turborepo-vs-lerna",
             "Nx vs Turborepo vs Lerna — which monorepo tool should you use?",
             "Nx vs Turborepo vs Lerna (2026) — Monorepo Tool Comparison",
             "comparison", "medium", "high", 6,
             "Nx: opinionated, generators, affected graph, Angular/React support; Turborepo: light, fast, remote cache; Lerna: legacy, still alive",
             "Picking Lerna for a new monorepo in 2026 — Nx or Turborepo are better choices; Lerna has been effectively absorbed by Nx",
             "Recommend Nx for opinionated enterprise monorepos; Turborepo for lighter Next.js-first setups",
             BUILD,
             ["Is Lerna still maintained?",
              "What is the Nx affected graph?",
              "How does Turborepo's remote cache work?",
              "When is a monorepo the right choice?"],
             "Nx vs Turborepo vs Lerna (2026) — Monorepo Tool Choice",
             "Compare Nx, Turborepo, and Lerna: generators, affected graph, remote cache, and when a monorepo actually helps."),
        ]),

        "scenario-based": ("Scenario-Based", []),

        "comparisons": ("Comparisons", [
            ("webpack-vs-vite-vs-parcel-vs-rollup",
             "Webpack vs Vite vs Parcel vs Rollup — which bundler for which project?",
             "Webpack vs Vite vs Parcel vs Rollup (2026) — Bundler Choice",
             "comparison", "medium", "high", 6,
             "Webpack: mature, complex; Vite: dev-server speed + Rollup prod; Parcel: zero-config; Rollup: library bundling",
             "Picking Webpack for a new SPA in 2026 — Vite is simpler and faster; Webpack remains dominant in legacy apps",
             "Map each to a use case: SPA/Next-alt (Vite), zero-config prototype (Parcel), npm library (Rollup/tsup), legacy (Webpack)",
             BUILD,
             ["What is tsup?",
              "Why do libraries use Rollup?",
              "Is Parcel still maintained?",
              "Which bundler has the smallest config overhead?"],
             "Webpack vs Vite vs Parcel vs Rollup (2026) — Bundler Choice",
             "Choose the right frontend bundler: Webpack, Vite, Parcel, Rollup/tsup — SPA vs library vs zero-config vs legacy use cases."),
        ]),
    },

    # -----------------------------------------------------------------------
    # M50 frontend-devops-ssr (9 topics, 9 Qs)
    # -----------------------------------------------------------------------
    "frontend-devops-ssr": {
        "ssr-csr-ssg-and-isr": ("SSR, CSR, SSG & ISR", [
            ("ssr-vs-csr-vs-ssg-vs-isr",
             "SSR vs CSR vs SSG vs ISR — differences, trade-offs, and when to use each?",
             "SSR vs CSR vs SSG vs ISR (2026) — Rendering Strategies",
             "comparison", "medium", "high", 8,
             "CSR: client renders; SSR: server renders per request; SSG: build-time render; ISR: hybrid with on-demand revalidation; streaming RSC",
             "Treating SSR and SSG as the same — SSR is per-request (dynamic), SSG is build-time (static); cache behavior and freshness differ",
             "Map each to use case: marketing site (SSG), authenticated app (CSR/SSR), blog/ecommerce (ISR), real-time dashboards (SSR + streaming)",
             FS,
             ["What is ISR?",
              "Is SSR slower than CSR for the user?",
              "When should you use SSG?",
              "What is streaming SSR?"],
             "SSR vs CSR vs SSG vs ISR (2026) — Rendering Strategies",
             "Compare SSR, CSR, SSG, and ISR: build-time vs request-time, streaming, React Server Components, and when each fits."),
        ]),

        "nextjs-app-router-fundamentals": ("Next.js App Router Fundamentals", [
            ("nextjs-app-router-vs-pages-router",
             "Next.js App Router vs Pages Router — what's different?",
             "Next.js App Router vs Pages Router (2026) — Migration Guide",
             "comparison", "medium", "high", 7,
             "App Router: file conventions, nested layouts, Server Components by default, streaming; Pages Router: getServerSideProps/getStaticProps",
             "Still writing getServerSideProps in new Next.js 14+ apps — App Router is the recommended default since Next 13.4 stable (2023)",
             "Mention the stable-in-production transition (Vercel itself uses App Router); incremental migration path",
             FS,
             ["What are Server Components in Next.js?",
              "How do you opt out to Client Components?",
              "What replaces getServerSideProps?",
              "Can you use App Router and Pages Router together?"],
             "Next.js App Router vs Pages Router (2026) — Migration",
             "Compare Next.js App Router vs Pages Router: Server Components, nested layouts, streaming, and migration from getServerSideProps."),

            ("nextjs-data-fetching-server-components",
             "How do you fetch data in Next.js App Router with Server Components?",
             "Next.js Data Fetching in App Router — Server Components Guide",
             "default", "medium", "high", 6,
             "async Server Components with fetch() + { cache, revalidate } options; request memoization; unstable_cache for server-side memoization",
             "Calling a database from a Client Component — only Server Components can touch DB directly; keep that code server-side",
             "Show fetch with next: { revalidate: 60 } for ISR; generateStaticParams for SSG; 'use cache' directive (2024+)",
             FS,
             ["What is 'use cache' in Next.js?",
              "How does fetch cache work in App Router?",
              "What is generateStaticParams?",
              "How do you pass data from Server to Client components?"],
             "Next.js Data Fetching (2026) — Server Components, ISR, Cache",
             "Master Next.js data fetching in App Router: async Server Components, fetch cache, ISR revalidate, generateStaticParams, 'use cache'."),
        ]),

        "angular-universal-ssr": ("Angular Universal SSR", [
            ("angular-universal-ssr-hydration-v17",
             "What is Angular Universal? How has hydration improved in Angular 17+?",
             "Angular Universal & Hydration (v17+) — SSR for Angular",
             "default", "medium", "medium", 5,
             "Angular Universal: server-render Angular app; v16+ added non-destructive hydration; v17+ made SSR opt-in via CLI",
             "Still rebuilding the DOM on hydration — pre-v16 behavior; v16+ non-destructive hydration is significantly faster",
             "Mention Angular SSR CLI schematic (ng add @angular/ssr) and the roadmap toward streaming SSR",
             FS,
             ["What is non-destructive hydration?",
              "How do you add SSR to an Angular app?",
              "When is SSR worth it for Angular?",
              "What is Angular's streaming SSR roadmap?"],
             "Angular Universal & Hydration v17+ (2026) — SSR Guide",
             "Master Angular Universal SSR: non-destructive hydration (v16+), v17 CLI schematic, and streaming SSR roadmap."),
        ]),

        "static-hosting-cdn-netlify-vercel": ("Static Hosting & CDN — Netlify, Vercel", [
            ("static-hosting-netlify-vercel-cloudfront",
             "How do Netlify, Vercel, and CloudFront differ for static/Jamstack hosting?",
             "Netlify vs Vercel vs CloudFront — Static & Jamstack Hosting",
             "comparison", "medium", "medium", 6,
             "Netlify/Vercel: developer-first, CI/CD baked-in, edge functions; CloudFront/S3: full AWS control, cheaper at scale, more ops",
             "Picking CloudFront + S3 for a small SPA without CI/CD overhead — Netlify/Vercel's DX is often cheaper overall",
             "Map scenario to choice: SPA/SSG (Netlify/Vercel), Next.js (Vercel first-party), enterprise AWS (CloudFront)",
             FS,
             ["What is Vercel Edge Network?",
              "What are Netlify Edge Functions?",
              "How does CloudFront compare for cost at scale?",
              "What is a Jamstack architecture?"],
             "Netlify vs Vercel vs CloudFront (2026) — Hosting Comparison",
             "Compare Netlify, Vercel, and CloudFront for static and Jamstack hosting: DX, edge functions, pricing, and Next.js integration."),
        ]),

        "nginx-for-spa": ("Nginx for SPA", [
            ("nginx-config-for-spa-history-api",
             "How do you configure Nginx to serve a React/Angular SPA with client-side routing?",
             "Nginx for SPA — history API fallback + Cache Headers",
             "default", "medium", "high", 5,
             "try_files $uri /index.html for history API fallback; long-term cache for hashed assets, short for index.html; gzip/brotli",
             "Forgetting try_files and getting 404s on deep links when users refresh — the server must fall back to index.html for SPA routes",
             "Show a production-grade Nginx config: gzip/brotli, long-cache hashed assets, no-cache index.html, HSTS + security headers",
             FS,
             ["What is the history API fallback?",
              "Why cache index.html as no-cache?",
              "How do you enable brotli in Nginx?",
              "What HSTS header should you set?"],
             "Nginx for SPA (2026) — History Fallback & Cache Headers",
             "Configure Nginx for a React/Angular SPA: history API fallback, asset caching, gzip/brotli, and security headers."),
        ]),

        "docker-for-frontend": ("Docker for Frontend", [
            ("multi-stage-docker-for-react-angular",
             "How do you write a multi-stage Dockerfile for a React/Angular app?",
             "Multi-Stage Dockerfile for Frontend — Build + Nginx Serve",
             "code", "medium", "medium", 5,
             "Stage 1: node:alpine builder (install, build); Stage 2: nginx:alpine copying dist/; tiny final image, no node_modules",
             "Shipping a 1GB node:latest image to production — multi-stage build with nginx:alpine is ~25MB",
             "Include .dockerignore (node_modules, .git), npm ci in build stage, and signal handling with tini or nginx's PID 1 behavior",
             FS,
             ["Why use multi-stage builds?",
              "What goes in .dockerignore?",
              "Why npm ci instead of npm install in Docker?",
              "How do you inject environment variables at runtime?"],
             "Multi-Stage Dockerfile for Frontend (2026) — Small Images",
             "Write a multi-stage Dockerfile for React/Angular: node builder + nginx serve, .dockerignore, npm ci, and runtime env vars."),
        ]),

        "preview-environments-and-feature-flags": ("Preview Environments & Feature Flags", [
            ("preview-envs-feature-flags-frontend",
             "What are preview environments and feature flags? How do frontend teams use them?",
             "Preview Environments & Feature Flags — Frontend Practices",
             "default", "medium", "medium", 6,
             "Preview per-PR envs (Vercel/Netlify default); feature flags (LaunchDarkly, Unleash, Split) to decouple deploy from release",
             "Deploying behind a feature flag and never cleaning up the flag — accumulates 'flag debt' that makes code hard to reason about",
             "Recommend flag-cleanup conventions, and SSR-safe flag evaluation (no flash of wrong content)",
             FS,
             ["What is flag debt?",
              "What is LaunchDarkly?",
              "How do you evaluate flags in SSR without a flash?",
              "Are preview envs free in Netlify/Vercel?"],
             "Preview Environments & Feature Flags (2026) — Frontend Guide",
             "Use preview environments and feature flags in frontend workflows: LaunchDarkly, Unleash, SSR-safe evaluation, and flag cleanup."),
        ]),

        "scenario-based": ("Scenario-Based", []),
        "comparisons": ("Comparisons", []),
    },
}
