"""
seed_jfi_phase1_data_react.py
=============================

React pillar (P15) question scaffolds.

Exports `REACT_TOPIC_DEFS` — merged into the master TOPIC_DEFS by
`seed_jfi_phase1_data.py`.

Same tuple shape as the main data file:

    (qid, question, title,
     layout, difficulty, importance, reading,
     testing, mistake, stand_out,
     tags, followups, meta_title, meta_desc)
"""

# Company tag presets (re-declared for standalone readability).
REACT_T = ["meta", "netflix", "airbnb", "uber", "flipkart", "razorpay", "swiggy"]
FE = ["meta", "google", "airbnb", "netflix", "uber", "flipkart", "razorpay"]

REACT_TOPIC_DEFS: dict = {

    # -----------------------------------------------------------------------
    # M19 react-core (11 topics, 28 Qs)
    # -----------------------------------------------------------------------
    "react-core": {
        "components-and-jsx": ("Components & JSX", [
            ("functional-vs-class-components-react",
             "What is the difference between functional and class components in React?",
             "Functional vs Class Components in React — Differences & Migration",
             "comparison", "easy", "high", 6,
             "Stateless vs stateful (pre-hooks), hooks replaced class lifecycle, function components are the modern default, performance parity",
             "Believing class components are faster than function components — they're not; function components are the recommended default since hooks (React 16.8+)",
             "Mention React has deprecated some class-only APIs (class-based error boundaries remain); new APIs (Suspense-for-data, Server Components) are function-only",
             REACT_T,
             ["Why did React add hooks?",
              "Can function components have error boundaries?",
              "Are class components deprecated?",
              "What's the performance difference between class and function components?"],
             "Functional vs Class Components in React (2026) — Differences",
             "Compare functional and class components in React: hooks vs lifecycle, when classes still matter, performance, and migration guidance."),

            ("what-is-jsx-how-it-transpiles",
             "What is JSX? How does it transpile to JavaScript?",
             "What Is JSX in React? — How It Compiles to React.createElement",
             "default", "easy", "high", 5,
             "JSX is syntactic sugar over React.createElement (or jsx() in the new transform), Babel/SWC transpiles it, attributes become props, children are variadic",
             "Thinking JSX must return a single parent — Fragments (<> </>) allow multiple roots without a wrapper div",
             "Mention the new JSX transform (React 17+) removes the need to import React in scope; tie into server components",
             REACT_T,
             ["What is a React Fragment?",
              "What is the new JSX transform in React 17+?",
              "Why must component names start with an uppercase letter?",
              "How are JSX attributes different from HTML?"],
             "What Is JSX in React? (2026) — Transpilation & Fragments",
             "Understand JSX: React.createElement desugaring, the new JSX transform (React 17+), Fragments, and why component names must be capitalized."),
        ]),

        "props-and-state": ("Props & State", [
            ("props-vs-state-react",
             "What is the difference between props and state in React?",
             "Props vs State in React — Differences, Immutability & Data Flow",
             "comparison", "easy", "high", 5,
             "Props = inputs from parent (read-only); State = internal, triggers re-render; unidirectional data flow; lifting state up",
             "Mutating props inside a child — props are immutable; mutating them doesn't re-render and breaks React's model",
             "Discuss lifting state up, prop drilling, and when to switch from props to Context/Redux",
             REACT_T,
             ["What is lifting state up?",
              "What is prop drilling?",
              "Why is state updated immutably?",
              "When should you move state to Context?"],
             "Props vs State in React (2026) — Differences Explained",
             "Master props vs state in React: immutability, unidirectional data flow, lifting state up, prop drilling, and when to use Context."),

            ("controlled-vs-uncontrolled-components-react",
             "Controlled vs uncontrolled components in React — what's the difference?",
             "Controlled vs Uncontrolled Components in React — Forms & Refs",
             "comparison", "medium", "high", 6,
             "Controlled: value + onChange drives the DOM from React state; Uncontrolled: DOM owns state, reads via ref; trade-offs in validation, performance, and file inputs",
             "Reading a file input with value prop (it's uncontrolled by design — files are read via ref or event.target.files)",
             "Recommend React Hook Form (uncontrolled by default) for perf, and controlled for complex validation / dependent fields",
             REACT_T,
             ["Why are file inputs always uncontrolled?",
              "How does React Hook Form use uncontrolled inputs?",
              "When is controlled better than uncontrolled?",
              "How do you get the current value of an uncontrolled input?"],
             "Controlled vs Uncontrolled Components in React (2026)",
             "Understand controlled vs uncontrolled inputs in React: value + onChange, refs, React Hook Form performance, and when each is appropriate."),
        ]),

        "hooks-use-state-use-effect": ("Hooks — useState & useEffect", [
            ("usestate-hook-explained-batching-lazy-init",
             "How does the useState hook work? Explain batching and lazy initialization.",
             "useState Hook Explained — Updates, Batching & Lazy Init",
             "default", "medium", "high", 6,
             "Setter triggers re-render, functional updater for stale closures, lazy init () => expensiveInit(), automatic batching in React 18",
             "Reading state right after setState and expecting the new value — state updates are asynchronous; use the updater or an effect",
             "Walk through React 18's automatic batching (all events batched), lazy-init benefits, and the setState(prev => ...) pattern for avoiding stale closures",
             REACT_T,
             ["What is automatic batching in React 18?",
              "When should you use a lazy initializer?",
              "Why is state async?",
              "What is the functional updater form?"],
             "useState Hook Explained (2026) — Updates, Batching, Lazy Init",
             "Master useState: setter semantics, async updates, functional updater, lazy initialization, and React 18 automatic batching."),

            ("useeffect-hook-explained-deps-cleanup",
             "How does useEffect work? Explain dependencies, cleanup, and common bugs.",
             "useEffect Hook Explained — Dependencies, Cleanup & Pitfalls",
             "default", "medium", "high", 8,
             "Effect runs after paint, deps array controls re-run, cleanup runs on unmount and before next effect, Strict Mode double-invoke in dev",
             "Omitting deps causing stale closures, or passing unstable functions/objects causing infinite re-runs",
             "Cover deps lint rule, useCallback/useMemo to stabilize deps, and React 18 Strict Mode double-effect in dev to surface cleanup bugs",
             REACT_T,
             ["Why does useEffect run twice in Strict Mode?",
              "How do you avoid infinite re-runs?",
              "What is the stale closure problem?",
              "When should useEffect cleanup run?"],
             "useEffect Hook Explained (2026) — Dependencies, Cleanup & Pitfalls",
             "Master useEffect: dependency arrays, cleanup semantics, React 18 Strict Mode double-invoke, stale closures, and infinite re-run bugs."),

            ("useeffect-vs-uselayouteffect",
             "What is the difference between useEffect and useLayoutEffect?",
             "useEffect vs useLayoutEffect — When to Use Each",
             "comparison", "medium", "high", 5,
             "useEffect runs after paint (non-blocking); useLayoutEffect runs synchronously after DOM updates but before paint (blocking); use the latter only for layout measurement",
             "Using useLayoutEffect by default — it blocks paint; useEffect is the correct default",
             "Mention SSR warnings for useLayoutEffect (no DOM on server), and useInsertionEffect for CSS-in-JS libs",
             REACT_T,
             ["When must you use useLayoutEffect?",
              "What is useInsertionEffect?",
              "Does useLayoutEffect work on the server?",
              "Why does useLayoutEffect block paint?"],
             "useEffect vs useLayoutEffect in React (2026) — When to Use Each",
             "Choose useEffect vs useLayoutEffect in React: paint timing, SSR caveats, useInsertionEffect for CSS-in-JS, and layout-measurement use cases."),

            ("useeffect-stale-closure-dependency-array",
             "What is the stale-closure problem in useEffect? How do you fix it?",
             "useEffect Stale Closure Problem — Dependency Array Pitfalls",
             "default", "medium", "high", 6,
             "Captured variables become stale when deps are omitted; setter functional form, refs for mutable values, exhaustive-deps lint rule",
             "Disabling eslint-react-hooks/exhaustive-deps to 'fix' warnings — typically hides a real bug",
             "Show a useInterval hook that uses a ref to always call the latest callback without resetting the interval",
             REACT_T,
             ["What is the exhaustive-deps lint rule?",
              "Why does disabling deps lint cause bugs?",
              "How does a ref solve the stale-closure problem?",
              "When are useCallback and useMemo needed?"],
             "useEffect Stale Closures (2026) — Dependency Array Pitfalls",
             "Fix React's stale-closure bug in useEffect: exhaustive-deps lint, functional updaters, refs for latest-callback, and useInterval example."),
        ]),

        "hooks-use-ref-use-memo-use-callback": ("Hooks — useRef, useMemo & useCallback", [
            ("useref-vs-usestate-when-to-use-each",
             "useRef vs useState — when should you use each in React?",
             "useRef vs useState in React — When to Use Each",
             "comparison", "medium", "high", 5,
             "useRef for mutable values that don't trigger re-render (DOM refs, timers, previous values); useState for reactive data",
             "Using useState for a setInterval ID or mutable counter that shouldn't cause re-renders — use useRef instead",
             "Show usePrevious hook with useRef, and useRef<T>(null) typing for DOM elements in TypeScript",
             REACT_T,
             ["How do you implement usePrevious?",
              "Can useRef hold any value?",
              "How do you type useRef in TypeScript?",
              "Does updating a ref re-render the component?"],
             "useRef vs useState (2026) — When to Use Each in React",
             "Choose useRef vs useState in React: mutable vs reactive data, DOM refs, usePrevious hook, and TypeScript typing."),

            ("usememo-vs-usecallback-vs-react-memo",
             "What is the difference between React.memo, useMemo, and useCallback? When do you actually need them?",
             "React.memo vs useMemo vs useCallback — When (Not) to Use Them",
             "comparison", "medium", "high", 7,
             "React.memo memoizes component render; useMemo memoizes a value; useCallback memoizes a function; all cost memory and dep-array overhead",
             "Wrapping every function in useCallback thinking it always helps — without a memoized child, it has no effect and adds overhead",
             "Introduce React Compiler (2024) which auto-memoizes and makes manual use of these rare; quote the React team's advice 'don't memo by default'",
             REACT_T,
             ["What is the React Compiler?",
              "When does useCallback actually help?",
              "How does React.memo compare props?",
              "Why doesn't useMemo guarantee the cache won't be cleared?"],
             "React.memo vs useMemo vs useCallback (2026) — When to Use",
             "Compare React.memo, useMemo, useCallback: memoization trade-offs, dep arrays, and how the React Compiler makes them largely unnecessary."),

            ("when-memoization-hurts-react",
             "When can memoization actually hurt React performance?",
             "When Memoization Hurts React Performance — Common Pitfalls",
             "default", "medium", "medium", 5,
             "Cost of comparing deps can exceed the work saved; object/array deps that change every render; over-memoization bloating code",
             "Adding useMemo to simple calculations — the allocation and comparison cost likely outweigh the tiny saving",
             "Mention React Compiler as the ergonomic long-term answer; until then, measure before memoizing",
             REACT_T,
             ["How do you profile React memoization?",
              "Why can useMemo cost more than it saves?",
              "When does a stable prop accidentally become unstable?",
              "What is a deep-equal prop-comparison helper?"],
             "When Memoization Hurts React Performance (2026) — Pitfalls",
             "Know when useMemo/useCallback/React.memo hurt performance in React: tiny calcs, unstable deps, code bloat, and profiler-first guidance."),

            ("forwardref-useimperativehandle",
             "What is forwardRef and useImperativeHandle in React? When do you need them?",
             "forwardRef & useImperativeHandle in React — Ref Forwarding Guide",
             "default", "medium", "medium", 6,
             "forwardRef to pass refs through a function component; useImperativeHandle to expose a custom ref API (focus, scrollIntoView)",
             "Using refs to imperatively manipulate children when lifting state or passing callbacks would be more idiomatic",
             "Show a custom <Input> exposing { focus, clear } via useImperativeHandle; note React 19 'ref as prop' (may remove the need for forwardRef)",
             REACT_T,
             ["Does React 19 still require forwardRef?",
              "When should you use useImperativeHandle?",
              "How do you type forwardRef in TypeScript?",
              "What is a ref cleanup function?"],
             "forwardRef & useImperativeHandle (2026) — Ref Forwarding",
             "Use forwardRef and useImperativeHandle to forward refs and expose imperative APIs; comparison with React 19's ref-as-prop proposal."),
        ]),

        "hooks-use-context-use-reducer": ("Hooks — useContext & useReducer", [
            ("usecontext-avoid-prop-drilling",
             "How does useContext avoid prop drilling? Show an example.",
             "useContext in React — Avoiding Prop Drilling with Context API",
             "default", "easy", "high", 6,
             "Provider/Consumer pair; useContext hook; default value; common use for theming, auth, i18n",
             "Using a single large Context for everything — any update re-renders every consumer; split Contexts by change frequency",
             "Show a ThemeContext example, and mention context-selector patterns (e.g., use-context-selector) for perf",
             REACT_T,
             ["How does useContext trigger re-renders?",
              "What is use-context-selector?",
              "When should you NOT use Context?",
              "How do you combine Context with useReducer?"],
             "useContext in React (2026) — Avoiding Prop Drilling",
             "Use React Context to avoid prop drilling: Provider/Consumer, useContext hook, theming patterns, and use-context-selector for performance."),

            ("usereducer-vs-usestate-when",
             "When should you use useReducer instead of useState?",
             "useReducer vs useState in React — When to Use Each",
             "comparison", "medium", "high", 5,
             "useReducer for complex state transitions, multiple related values, action-based logic; useState for simple values",
             "Reaching for Redux immediately — useReducer + Context can replace Redux for many mid-size apps",
             "Show a form with useReducer and a discriminated action union; mention Redux Toolkit's createSlice is a useReducer-flavored API",
             REACT_T,
             ["Can useReducer replace Redux?",
              "How do you type useReducer actions in TypeScript?",
              "How does Immer integrate with useReducer?",
              "When does useReducer become Redux?"],
             "useReducer vs useState (2026) — When to Use Each in React",
             "Choose useReducer vs useState: complex transitions, action unions, Immer integration, and when to graduate to Redux Toolkit."),

            ("context-api-performance-pitfalls",
             "What are the performance pitfalls of the React Context API?",
             "React Context Performance Pitfalls — Re-renders & Fixes",
             "default", "medium", "high", 6,
             "Every Provider value change re-renders all consumers; unstable object literals; splitting Contexts or using selector libraries",
             "Passing a fresh object literal as the Context value every render — unstable reference = cascading re-renders",
             "Show three fixes: useMemo the value, split Contexts by responsibility, or use use-context-selector / Zustand for selector-level subscription",
             REACT_T,
             ["Why does Context cause over-rendering?",
              "What is the use-context-selector library?",
              "How do you split a single Context into many?",
              "Is Zustand a Context alternative?"],
             "React Context Performance Pitfalls (2026) — Re-renders Fix",
             "Fix React Context performance: memoize values, split Contexts, use use-context-selector, or switch to Zustand for selector subscriptions."),
        ]),

        "custom-hooks": ("Custom Hooks", [
            ("how-to-write-custom-hooks-react",
             "How do you write a custom hook in React? Give a useFetch example.",
             "Custom Hooks in React — How to Write Them (useFetch Example)",
             "code", "medium", "high", 6,
             "Functions starting with use, composing built-in hooks, returning state + actions; exhaustive-deps respect; AbortController for fetch",
             "Forgetting to clean up async operations on unmount — the returned fetch may set state on an unmounted component",
             "Build a useFetch with loading/data/error, AbortController on unmount, and dependency-aware refetch",
             REACT_T,
             ["How do you cancel a fetch in a hook?",
              "Why must hook names start with use?",
              "Can custom hooks take other hooks as arguments?",
              "When should a custom hook return an object vs a tuple?"],
             "Custom Hooks in React (2026) — useFetch Example & Guide",
             "Write custom React hooks: naming rules, composition, useFetch with AbortController, cleanup, and return shapes (tuple vs object)."),

            ("rules-of-react-hooks",
             "What are the rules of React hooks? Why do they exist?",
             "Rules of React Hooks — Why They Exist (Top-Level, Same Order)",
             "default", "easy", "high", 5,
             "Only call hooks at the top level and from React functions; the rules enforce consistent call order so React can track state positionally",
             "Calling a hook inside an if/for/early-return — breaks state order and triggers the 'rendered more/fewer hooks' error",
             "Reference the eslint-plugin-react-hooks rule of hooks and how React Compiler relaxes some manual concerns (memoization) but not the call-order rule",
             REACT_T,
             ["What is the exhaustive-deps ESLint rule?",
              "Why does hook order matter?",
              "Can you call a hook inside a try/catch?",
              "Does React Compiler change the rules of hooks?"],
             "Rules of React Hooks (2026) — Why They Exist & Common Bugs",
             "Understand the rules of React hooks: top-level calls, same order, ESLint enforcement, and the React Compiler's limits."),
        ]),

        "lifecycle-and-effects": ("Lifecycle & Effects", [
            ("class-lifecycle-to-hooks-mapping",
             "How do class lifecycle methods map to React hooks?",
             "React Class Lifecycle → Hooks Mapping (componentDidMount etc.)",
             "default", "medium", "medium", 6,
             "componentDidMount → useEffect(fn, []); componentDidUpdate → useEffect with deps; componentWillUnmount → cleanup; getDerivedStateFromProps → useMemo/useState with key",
             "Translating getDerivedStateFromProps directly into useEffect — the pattern is usually derived state during render or key-reset instead",
             "Note that shouldComponentUpdate maps to React.memo (shallow) or useMemo, and that hooks simplify conditional logic that was awkward in classes",
             REACT_T,
             ["How does componentDidCatch map to hooks?",
              "What replaces getDerivedStateFromProps?",
              "Is there a shouldComponentUpdate equivalent in hooks?",
              "How do you handle cleanup in hooks?"],
             "Class Lifecycle → Hooks Mapping in React (2026) — Cheatsheet",
             "Map React class lifecycle methods (didMount, didUpdate, willUnmount, derivedStateFromProps) to hooks: useEffect, useMemo, React.memo."),

            ("useeffect-mount-update-unmount-patterns",
             "How do you handle mount, update, and unmount with useEffect?",
             "useEffect Mount, Update & Unmount Patterns — React Examples",
             "default", "medium", "high", 5,
             "[] deps = mount-only; specified deps = update; cleanup inside useEffect = unmount/next-run; Strict Mode double-invoke in dev",
             "Forgetting Strict Mode double-runs effects in dev — leads to duplicate subscriptions if cleanup isn't idempotent",
             "Stress idempotent cleanup; show an event listener pattern that survives Strict Mode correctly",
             REACT_T,
             ["Why does Strict Mode double-run effects?",
              "How do you skip the initial mount run?",
              "How do you run an effect only once?",
              "What makes a cleanup idempotent?"],
             "useEffect Mount/Update/Unmount (2026) — React Patterns",
             "Master useEffect for mount/update/unmount in React: dep arrays, cleanup, Strict Mode double-invoke, and idempotent subscription patterns."),
        ]),

        "error-boundaries": ("Error Boundaries", [
            ("react-error-boundaries-componentDidCatch",
             "What are Error Boundaries in React? How do you implement one?",
             "Error Boundaries in React — componentDidCatch & Fallback UI",
             "default", "medium", "high", 6,
             "Class component with componentDidCatch and getDerivedStateFromError; catches render-phase errors; no hook equivalent yet; react-error-boundary lib",
             "Expecting error boundaries to catch async/event-handler errors — they only catch render, effect, and constructor errors",
             "Recommend the react-error-boundary library for a function-component API, and explain why async errors need try/catch at the call site",
             REACT_T,
             ["What errors do boundaries NOT catch?",
              "What is the react-error-boundary library?",
              "How do you reset an error boundary?",
              "Is there a hooks-only error boundary?"],
             "Error Boundaries in React (2026) — componentDidCatch & Libraries",
             "Implement React Error Boundaries: componentDidCatch, getDerivedStateFromError, react-error-boundary library, and why async errors need try/catch."),
        ]),

        "suspense-and-concurrent-features": ("Suspense & Concurrent Features", [
            ("react-suspense-for-data-fetching",
             "How does React Suspense work for data fetching?",
             "React Suspense for Data Fetching — How It Works",
             "default", "hard", "high", 7,
             "Suspense catches thrown Promises, shows fallback, resumes on resolve; works natively with Server Components, Next.js App Router, and data libs",
             "Assuming Suspense works with any fetch — requires a Suspense-aware source (React Query, Relay, or framework integration)",
             "Mention React 19's use() hook for unwrapping promises in components, and streaming SSR with Suspense boundaries",
             REACT_T,
             ["What is the React 19 use() hook?",
              "How does Suspense enable streaming SSR?",
              "Does React Query support Suspense?",
              "Why can't a fetch() directly suspend?"],
             "React Suspense for Data Fetching (2026) — How It Works",
             "Master React Suspense for data: thrown promises, fallback, streaming SSR, React 19 use() hook, and integration with React Query/Relay."),

            ("react-usetransition-usedeferredvalue",
             "What are useTransition and useDeferredValue in React 18+?",
             "useTransition & useDeferredValue — React Concurrent Features",
             "default", "hard", "medium", 6,
             "Mark updates as non-urgent; keep UI responsive during expensive renders; useDeferredValue defers a value until higher-priority updates settle",
             "Wrapping an input's value update in startTransition — the input then lags behind keystrokes (input should be urgent; filter result is the transition)",
             "Show typeahead search: urgent input state + useDeferredValue for the list; mention React 19's useOptimistic for optimistic UI",
             REACT_T,
             ["What is useOptimistic?",
              "When should you use useDeferredValue?",
              "How does startTransition interact with Suspense?",
              "Can you mix urgent and non-urgent updates?"],
             "useTransition & useDeferredValue (2026) — React Concurrent",
             "Use React concurrent features: useTransition, useDeferredValue, useOptimistic, startTransition, and responsive typeahead search patterns."),
        ]),

        "scenario-based": ("Scenario-Based", [
            ("build-counter-with-usereducer",
             "How do you build a counter with useReducer in React?",
             "Build a Counter with useReducer — React Example (TypeScript)",
             "code", "easy", "medium", 4,
             "Action types (increment/decrement/reset/set), discriminated union, reducer function, useReducer hook, optional middleware",
             "Mutating state inside the reducer — reducers must return a new state object",
             "Add TypeScript discriminated union types, then extend the example to useContext for app-wide state",
             REACT_T,
             ["How do you type useReducer actions?",
              "How do you add middleware to useReducer?",
              "When does a counter need useReducer over useState?",
              "How do you combine useReducer with Context?"],
             "Build a Counter with useReducer in React (2026) — TS Example",
             "Build a counter with useReducer: discriminated action unions, typed reducer, Context integration, and when to prefer useReducer over useState."),

            ("debounce-throttle-hook-react",
             "How do you implement a useDebounce / useThrottle hook in React?",
             "useDebounce & useThrottle Hooks in React — Implementations",
             "code", "medium", "high", 6,
             "useEffect with setTimeout, cleanup on value change/unmount, stable callback via useRef, TypeScript generics",
             "Recreating the debounced function on every render — loses the timer reference; wrap in useRef or useMemo",
             "Compare useDebounce (debounce a value for search) vs useDebouncedCallback (debounce a function for event handlers)",
             REACT_T,
             ["What's the difference between useDebounce and useDebouncedCallback?",
              "How do you cancel a debounced effect on unmount?",
              "Is there a standard library for these hooks?",
              "How do you throttle a mouse-move handler?"],
             "useDebounce & useThrottle Hooks in React (2026) — Code",
             "Build useDebounce and useThrottle in React: setTimeout, cleanup on unmount, stable refs, typed generics, and common library alternatives."),

            ("implement-infinite-scroll-react",
             "How do you implement infinite scroll in React?",
             "Infinite Scroll in React — Intersection Observer + React Query",
             "code", "medium", "high", 7,
             "Intersection Observer ref for the sentinel row, paginated fetch (cursor or offset), React Query useInfiniteQuery, list virtualization for huge lists",
             "Using window scroll events for infinite scroll — rAF/throttle needed, janky; Intersection Observer is the modern approach",
             "Show useInfiniteQuery with Intersection Observer and react-virtual for performance; mention react-intersection-observer library",
             REACT_T,
             ["What is useInfiniteQuery in React Query?",
              "Why use Intersection Observer over scroll events?",
              "How do you virtualize an infinite list?",
              "How do you restore scroll position?"],
             "Infinite Scroll in React (2026) — Intersection Observer + RQ",
             "Build infinite scroll in React: Intersection Observer, useInfiniteQuery, virtualization with react-virtual, and scroll-position restoration."),
        ]),

        "comparisons": ("Comparisons", [
            ("react-vs-angular-vs-vue",
             "React vs Angular vs Vue — what are the differences?",
             "React vs Angular vs Vue — Differences, Trade-offs (2026)",
             "comparison", "medium", "high", 7,
             "React: library, unopinionated; Angular: full framework, TypeScript-first, RxJS, DI; Vue: progressive, SFCs, template-first; ecosystems, job markets, perf profiles",
             "Declaring one 'the best' — each wins in different team/product contexts; avoid absolute statements",
             "Give 2026-accurate market shares (React largest, Angular second in enterprise, Vue strong in Asia), and note Svelte/SolidJS as rising alternatives",
             REACT_T,
             ["When is Angular better than React?",
              "What is Svelte and how does it differ?",
              "What is SolidJS?",
              "Is Vue growing or shrinking in 2026?"],
             "React vs Angular vs Vue (2026) — Full Comparison Guide",
             "Compare React, Angular, and Vue in 2026: paradigms, ecosystems, TypeScript support, job markets, and modern alternatives like Svelte and SolidJS."),

            ("class-vs-functional-components-after-hooks",
             "After hooks, should you still use class components in React?",
             "Class vs Functional Components After Hooks — 2026 Recommendation",
             "comparison", "easy", "medium", 4,
             "Function components with hooks are the default; class components remain supported but not recommended for new code",
             "Mixing classes and functions without a plan — pick one convention per module; new code should be functional",
             "Note that Error Boundaries still need a class component (until a hook equivalent lands); everything else is functional",
             REACT_T,
             ["Why are class components still supported?",
              "What features are function-only?",
              "Is there a hook-based error boundary?",
              "Should you migrate class components to hooks?"],
             "Class vs Functional Components After Hooks (2026)",
             "In 2026, React function components with hooks are the default; classes linger for error boundaries and legacy — when (if ever) to migrate."),

            ("redux-vs-context-api-vs-zustand",
             "Redux vs Context API vs Zustand — when should you use each?",
             "Redux vs Context API vs Zustand — When to Use Each (2026)",
             "comparison", "medium", "high", 6,
             "Context: simple sharing, re-render all consumers; Redux: time-travel, middleware, large apps; Zustand: lightweight, selector-based, minimal boilerplate",
             "Always reaching for Redux first — for most small/medium apps, Zustand or React Query + Context is enough",
             "Also mention Jotai (atomic) and Redux Toolkit (Redux + Immer + minimal boilerplate) as practical modern picks",
             REACT_T,
             ["What is Jotai?",
              "When does Redux make sense over Zustand?",
              "Is React Query a state manager?",
              "Can you mix Redux with Context?"],
             "Redux vs Context API vs Zustand (2026) — State Management",
             "Choose between Redux, Context API, and Zustand: boilerplate, re-render behavior, middleware, and when React Query replaces a store entirely."),
        ]),
    },

    # -----------------------------------------------------------------------
    # M20 react-state-data (10 topics, 18 Qs)
    # -----------------------------------------------------------------------
    "react-state-data": {
        "context-api-patterns": ("Context API Patterns", [
            ("context-api-best-practices",
             "What are best practices for using the React Context API?",
             "React Context API Best Practices — Splitting & Memoization",
             "default", "medium", "high", 6,
             "Split by change frequency, memoize Provider value, colocate Context and Provider, expose a custom hook (useTheme), don't overuse",
             "Exposing the Context object directly and letting consumers call useContext — wrap in a custom hook for missing-provider error",
             "Pattern: export Provider + custom hook; Context-selector when any single slice changes rarely but consumers are many",
             REACT_T,
             ["How do you throw a helpful error when Provider is missing?",
              "What is the 'split contexts' pattern?",
              "Why wrap Context in a custom hook?",
              "When is a Zustand store a better choice than Context?"],
             "React Context API Best Practices (2026) — Splitting & Memo",
             "Master Context API best practices: split by frequency, memoize Provider value, expose useXxx hooks, and error on missing Provider."),

            ("context-api-performance-re-renders",
             "Why does the Context API cause excessive re-renders? How do you fix it?",
             "React Context Re-renders — Causes and Fixes",
             "default", "medium", "high", 5,
             "Any Provider value change re-renders all consumers; unstable object literals; fix with useMemo, Context splitting, or selector libs",
             "Passing {user, setUser, theme, setTheme} in one Provider — any user update also re-renders theme consumers",
             "Introduce use-context-selector and how React 19's upcoming Context selector semantics might change this",
             REACT_T,
             ["What is use-context-selector?",
              "How do you split Contexts effectively?",
              "Why is useMemo important for Provider value?",
              "Does React 19 change Context re-render behavior?"],
             "React Context Re-renders (2026) — Causes & Fixes",
             "Fix excessive React Context re-renders: memoize Provider values, split Contexts, use-context-selector, and upcoming React 19 improvements."),
        ]),

        "redux-fundamentals": ("Redux Fundamentals", [
            ("redux-core-concepts-store-action-reducer",
             "Explain the core concepts of Redux — store, action, reducer.",
             "Redux Core Concepts — Store, Action, Reducer Explained",
             "default", "easy", "high", 6,
             "Single store, pure reducers, actions as dispatched objects, subscribers, immutable updates",
             "Storing derived data in the store — prefer selectors (reselect / Redux Toolkit's createSelector) to compute from raw state",
             "Recommend Redux Toolkit over classic Redux; mention reselect for memoized selectors",
             REACT_T,
             ["What is a pure reducer?",
              "Why must state updates be immutable?",
              "What is reselect?",
              "Does Redux always require middleware?"],
             "Redux Core Concepts (2026) — Store, Action, Reducer Explained",
             "Master Redux fundamentals: store, pure reducers, actions, subscribers, and why Redux Toolkit is the modern default."),

            ("redux-data-flow-middleware-thunk",
             "Explain Redux data flow and middleware (thunk, saga).",
             "Redux Data Flow & Middleware — Thunk vs Saga Explained",
             "default", "medium", "high", 7,
             "Action → middleware chain → reducer → store → subscribers; thunk for async action creators; saga for complex flows with generators",
             "Putting side effects inside reducers — reducers must be pure; side effects live in middleware (thunks, sagas) or React Query",
             "Compare thunk (simple), saga (generator-based, testable flows), and listener middleware (Redux Toolkit's modern addition)",
             REACT_T,
             ["What is Redux listener middleware?",
              "Thunk vs saga — which to pick?",
              "What is the difference between RTK Query and redux-thunk?",
              "How do you test a thunk?"],
             "Redux Data Flow & Middleware (2026) — Thunk, Saga, Listener",
             "Master Redux data flow and middleware: thunks, sagas, listener middleware, and when RTK Query replaces the async-action pattern."),

            ("redux-pure-reducers-immutability",
             "Why must Redux reducers be pure and immutable?",
             "Redux Pure Reducers & Immutability — Why They Matter",
             "default", "medium", "medium", 5,
             "Pure = deterministic and side-effect-free; immutable = React can do cheap shallow equality for re-render decisions; enables time-travel debugging",
             "Pushing to a state array with push() — mutates; use spread or Immer for an immutable update",
             "Recommend Immer (built into Redux Toolkit) so you can write mutable-looking code that produces immutable updates",
             REACT_T,
             ["How does Immer make reducers easier?",
              "Why does immutability enable time-travel debugging?",
              "What are structural sharing benefits?",
              "Can a reducer call APIs?"],
             "Redux Pure Reducers & Immutability (2026) — Why They Matter",
             "Understand why Redux reducers must be pure and immutable: time travel, shallow-equal React re-renders, Immer, and common mutation bugs."),
        ]),

        "redux-toolkit": ("Redux Toolkit", [
            ("redux-toolkit-createslice-configurestore",
             "How does Redux Toolkit work? Explain createSlice and configureStore.",
             "Redux Toolkit Explained — createSlice, configureStore & Immer",
             "default", "medium", "high", 6,
             "createSlice auto-generates actions + reducer with Immer; configureStore wires middleware/devtools; RTK Query for data fetching",
             "Still writing hand-rolled switch-statement reducers — Redux Toolkit is the recommended default as of 2020",
             "Show a todo slice with createSlice, an extraReducer for async thunks, and an RTK Query endpoint for fetching",
             REACT_T,
             ["What does Immer do inside createSlice?",
              "What is extraReducers?",
              "How does RTK Query differ from React Query?",
              "Is Redux Toolkit mandatory for Redux?"],
             "Redux Toolkit (2026) — createSlice, configureStore, Immer",
             "Master Redux Toolkit: createSlice, configureStore, Immer-powered reducers, extraReducers, and when RTK Query replaces thunks."),

            ("createasyncthunk-redux-toolkit",
             "How do you use createAsyncThunk in Redux Toolkit?",
             "createAsyncThunk in Redux Toolkit — Async Actions Explained",
             "default", "medium", "medium", 5,
             "Auto-generates pending/fulfilled/rejected action types; thunk function receives (arg, thunkApi); handled via extraReducers",
             "Not using rejectWithValue for custom errors — default rejection gives the raw Error, losing server payloads",
             "Compare with RTK Query (preferred for data fetching) and show a typical authLogin thunk",
             REACT_T,
             ["What is rejectWithValue?",
              "When to pick RTK Query over createAsyncThunk?",
              "How do you cancel a thunk?",
              "How do you test a createAsyncThunk?"],
             "createAsyncThunk in Redux Toolkit (2026) — Async Actions",
             "Use createAsyncThunk in Redux Toolkit: pending/fulfilled/rejected, rejectWithValue, cancellation, and RTK Query comparison."),
        ]),

        "zustand-and-jotai": ("Zustand & Jotai", [
            ("zustand-basics-vs-redux",
             "What is Zustand? How does it compare to Redux?",
             "Zustand Basics vs Redux — Lightweight Store Explained",
             "comparison", "medium", "high", 6,
             "Zustand: tiny API (create, set, get), selector-based subscriptions, no boilerplate, no providers; Redux: structured, devtools, middleware ecosystem",
             "Forgetting to use selectors in Zustand — subscribing to the whole store re-renders on any change",
             "Show a typed Zustand store with middleware (persist, devtools, immer) and selector subscription",
             REACT_T,
             ["How do you add devtools to Zustand?",
              "What is the Zustand persist middleware?",
              "Is Zustand React-only?",
              "How does Zustand compare to Jotai?"],
             "Zustand Basics vs Redux (2026) — Lightweight React Store",
             "Master Zustand: minimal API, selectors, persist/devtools middleware, and when it beats Redux Toolkit for small/medium apps."),

            ("jotai-atomic-state-model",
             "What is Jotai and the atomic state model?",
             "Jotai & Atomic State Model — React State Beyond Stores",
             "default", "medium", "medium", 5,
             "Atoms as small state units; derived atoms for selectors; no central store; Suspense-friendly",
             "Treating atoms like global variables without Provider scoping — Jotai supports per-subtree atoms with <Provider>",
             "Contrast Jotai atoms with Recoil (similar API; Recoil is less maintained as of 2024) and Zustand stores",
             REACT_T,
             ["How does Jotai compare to Recoil?",
              "What is a derived atom?",
              "How does Jotai integrate with Suspense?",
              "Can atoms be async?"],
             "Jotai Atomic State (2026) — React State Beyond Stores",
             "Master Jotai's atomic state model: atoms, derived atoms, Suspense integration, Provider scoping, and Recoil comparison."),
        ]),

        "react-query-tanstack": ("React Query (TanStack Query)", [
            ("react-query-tanstack-basics",
             "What is React Query (TanStack Query)? Why has it become so popular?",
             "React Query Basics — Server-State Library for React",
             "default", "medium", "high", 7,
             "Server-state caching, stale-time / cache-time, background refetch, dedupe, mutation helpers; separates server state from client state",
             "Using Redux to cache server data — overkill; React Query handles caching, dedupe, refetch, and invalidation natively",
             "Explain useQuery/useMutation, queryKey hierarchy, and why server state is fundamentally different from client state",
             REACT_T,
             ["What is the difference between server state and client state?",
              "What is queryKey?",
              "How does React Query dedupe requests?",
              "What is the difference between staleTime and cacheTime?"],
             "React Query Basics (2026) — Server-State Library Explained",
             "Master React Query (TanStack Query): useQuery, useMutation, stale/cache time, dedupe, and why server state needs its own tool."),

            ("usequery-vs-usemutation-react-query",
             "What is the difference between useQuery and useMutation in React Query?",
             "useQuery vs useMutation in React Query — Differences Explained",
             "comparison", "medium", "high", 5,
             "useQuery for reads (cached, background refetched); useMutation for writes (explicit trigger, on-success invalidation)",
             "Calling useQuery for a write operation — it auto-runs and caches; mutations must be triggered manually and invalidate the right queryKeys",
             "Show optimistic updates with useMutation, onMutate, and queryClient.cancelQueries",
             REACT_T,
             ["How do optimistic updates work with useMutation?",
              "What is queryClient.invalidateQueries?",
              "Can mutations be retried?",
              "How do you invalidate related queries after a mutation?"],
             "useQuery vs useMutation (2026) — React Query Differences",
             "Compare useQuery vs useMutation in React Query: reads vs writes, optimistic updates, invalidation, and retry behavior."),

            ("stale-time-cache-time-invalidation",
             "What are staleTime, cacheTime (gcTime), and query invalidation in React Query?",
             "React Query staleTime, cacheTime & Invalidation — Explained",
             "default", "medium", "high", 6,
             "staleTime: how long data is fresh; gcTime (v5 rename of cacheTime): how long inactive data stays in cache; invalidateQueries marks stale",
             "Setting staleTime to 0 (default) and wondering why refetches happen constantly on window focus",
             "Show patterns for lists + details; explain why gcTime > staleTime; mention queryClient.setQueryData for manual writes",
             REACT_T,
             ["What's new in TanStack Query v5 (cacheTime → gcTime rename)?",
              "How do you refetch on window focus?",
              "What is queryClient.setQueryData?",
              "How do you share cache across tabs?"],
             "React Query staleTime & gcTime (2026) — Invalidation Guide",
             "Master React Query caching: staleTime, gcTime (v5), invalidateQueries, setQueryData, and refetch strategies for lists + details."),
        ]),

        "swr": ("SWR", [
            ("swr-vs-react-query-comparison",
             "SWR vs React Query — what are the differences and when should you use each?",
             "SWR vs React Query (TanStack) — Differences & When to Use",
             "comparison", "medium", "medium", 5,
             "Both do stale-while-revalidate; React Query has more features (mutations, infinite query, devtools); SWR is simpler with Vercel/Next.js lineage",
             "Picking SWR just because it's smaller — React Query's features often matter in real apps; measure before switching",
             "Give fair trade-offs; note that SWR is smaller and integrates nicely with Vercel Edge/Next.js; React Query has the richer ecosystem",
             REACT_T,
             ["Is SWR smaller than React Query?",
              "Does SWR support mutations?",
              "Which has better Next.js integration?",
              "Can you migrate SWR to React Query easily?"],
             "SWR vs React Query (2026) — Differences & When to Pick Each",
             "Compare SWR vs TanStack React Query: features, bundle size, Next.js integration, mutations, and migration considerations."),
        ]),

        "server-components-and-data": ("Server Components & Data", [
            ("react-server-components-explained",
             "What are React Server Components (RSC)? How are they different from client components?",
             "React Server Components Explained — RSC vs Client Components",
             "default", "hard", "high", 8,
             "Server-only rendering, zero JS shipped, direct data access (DB), cannot use state/effects, 'use client' boundary, streaming",
             "Trying to use state/hooks in a Server Component — it's by design not supported; move interactivity to a Client Component",
             "Mention Next.js App Router as the first production-ready host; streaming with Suspense; serialization boundary for props",
             REACT_T,
             ["Can you pass functions as props to a Client Component?",
              "How does 'use client' work?",
              "How do RSCs stream to the browser?",
              "Are RSCs the same as SSR?"],
             "React Server Components Explained (2026) — RSC vs Client",
             "Master React Server Components: server-only rendering, zero-JS shipping, 'use client' boundary, streaming, and Next.js App Router integration."),

            ("server-vs-client-components-nextjs-app-router",
             "Server vs Client components in Next.js App Router — what's the difference?",
             "Server vs Client Components in Next.js App Router — Comparison",
             "comparison", "hard", "high", 6,
             "Server components default; 'use client' opts into interactivity; shared components can be server-rendered then hydrated; data fetching patterns differ",
             "Putting 'use client' at the top of every page — bloats JS bundle; only leaf components that need state/effects should be client",
             "Recommend composition: Server component fetches and passes data to a small Client component for interactivity",
             REACT_T,
             ["Where should 'use client' go?",
              "Can a Server Component import a Client Component?",
              "How do you fetch data in Server Components?",
              "What replaces getServerSideProps in App Router?"],
             "Server vs Client Components in Next.js App Router (2026)",
             "Master Server vs Client components in Next.js App Router: composition, 'use client' placement, data-fetching patterns, and migration from Pages Router."),
        ]),

        "optimistic-updates-and-caching": ("Optimistic Updates & Caching", [
            ("optimistic-updates-pattern-react",
             "What is the optimistic-update pattern? How do you implement it in React?",
             "Optimistic Updates in React — UI-First Pattern Explained",
             "default", "medium", "high", 6,
             "Update the UI immediately, send the request, reconcile or rollback on error; React Query's onMutate + context pattern; React 19 useOptimistic",
             "Forgetting the rollback path — on server error, the UI is out of sync with reality",
             "Show a React Query example with onMutate/onError/onSettled and the React 19 useOptimistic hook",
             REACT_T,
             ["What is React 19's useOptimistic?",
              "How does onMutate pattern work in React Query?",
              "How do you rollback on error?",
              "When is optimistic update risky?"],
             "Optimistic Updates in React (2026) — UI-First Pattern",
             "Implement optimistic updates in React: React Query onMutate rollback, React 19 useOptimistic, and patterns to keep UI and server consistent."),
        ]),

        "scenario-based": ("Scenario-Based", [
            ("build-todo-app-redux-toolkit",
             "How do you build a todo app with Redux Toolkit? Show the slice + UI.",
             "Build a Todo App with Redux Toolkit — Complete Example",
             "code", "easy", "medium", 6,
             "todosSlice with add/toggle/delete reducers (Immer), typed state, useDispatch/useSelector, persisting to localStorage",
             "Dispatching mutation objects directly — use the action creators auto-generated by createSlice for type safety",
             "Add RTK Query for syncing with a backend; mention middleware for persist; show a TypeScript-first setup",
             REACT_T,
             ["How do you persist Redux state to localStorage?",
              "How does RTK Query fit into a todo app?",
              "How do you type Redux Toolkit state?",
              "What middleware comes with configureStore by default?"],
             "Build a Todo App with Redux Toolkit (2026) — Full Example",
             "Build a typed todo app with Redux Toolkit: createSlice, useSelector/useDispatch, Immer, persist middleware, and RTK Query sync."),
        ]),

        "comparisons": ("Comparisons", [
            ("redux-vs-zustand-vs-react-query",
             "Redux vs Zustand vs React Query — when should you use each?",
             "Redux vs Zustand vs React Query — State Management Choice (2026)",
             "comparison", "medium", "high", 6,
             "Redux: structured client state, middleware; Zustand: lightweight client state; React Query: server state, caching, sync; they can coexist",
             "Comparing React Query against Redux as if they solve the same problem — server state (RQ) and client state (Redux/Zustand) are different",
             "Map responsibilities: client UI state (Zustand/useReducer), server cache (React Query), cross-cutting workflows (Redux Toolkit + listener middleware)",
             REACT_T,
             ["Do you still need Redux if you use React Query?",
              "Can Zustand and React Query coexist?",
              "What is RTK Query?",
              "When does Redux still win?"],
             "Redux vs Zustand vs React Query (2026) — State Choice",
             "Choose Redux, Zustand, or React Query in React: client vs server state, when each wins, and how to combine them in real apps."),
        ]),
    },

    # -----------------------------------------------------------------------
    # M21 react-routing-forms (9 topics, 12 Qs)
    # -----------------------------------------------------------------------
    "react-routing-forms": {
        "react-router-basics": ("React Router Basics", [
            ("react-router-v6-basics",
             "What are the basics of React Router v6?",
             "React Router v6 Basics — Routes, Route, Link, useNavigate",
             "default", "easy", "high", 6,
             "BrowserRouter, Routes, Route element prop, nested routes, Outlet, Link/NavLink, useNavigate, useParams",
             "Still writing component-prop syntax (v5 style) — v6 uses the element prop and auto-relative nested routes",
             "Highlight v6 breaking changes vs v5, the new data routers (createBrowserRouter), and loaders/actions",
             REACT_T,
             ["What are the breaking changes from v5 to v6?",
              "What is createBrowserRouter?",
              "What are route loaders?",
              "How does Outlet work?"],
             "React Router v6 Basics (2026) — Routes, Link, useNavigate",
             "Master React Router v6: Routes, nested routes with Outlet, Link/NavLink, useNavigate, useParams, and the data-router APIs."),

            ("useparams-usesearchparams-uselocation",
             "What do useParams, useSearchParams, and useLocation do in React Router?",
             "useParams, useSearchParams & useLocation — React Router Hooks",
             "default", "easy", "medium", 4,
             "useParams: URL path params; useSearchParams: query string (get/set tuple); useLocation: full location (pathname, search, hash, state)",
             "Mutating searchParams.get result directly — useSearchParams returns a tuple [params, setParams]; use setParams to update",
             "Show typical patterns: filters in URL via useSearchParams, scroll-restoration with useLocation",
             REACT_T,
             ["How do you preserve query params on navigation?",
              "Is the useSearchParams setter replace or push?",
              "How do you access location state?",
              "How do you read nested route params?"],
             "useParams, useSearchParams & useLocation (2026) — Router Hooks",
             "Use React Router hooks: useParams for path params, useSearchParams tuple for queries, and useLocation for pathname/search/state."),
        ]),

        "nested-routes-and-layouts": ("Nested Routes & Layouts", [
            ("nested-routes-shared-layouts-outlet",
             "How do nested routes and shared layouts work in React Router (Outlet)?",
             "Nested Routes & Shared Layouts with Outlet — React Router",
             "default", "medium", "high", 5,
             "Define children in a Route element tree; parent renders <Outlet/>; Outlet context; layout components for chrome",
             "Mixing a layout component with an independent Routes block, losing Outlet context and breaking route-relative links",
             "Show a dashboard layout with Outlet + useOutletContext for sharing data; relative links",
             REACT_T,
             ["What is useOutletContext?",
              "How do you create a layout route without a path?",
              "What is an index route?",
              "How do you make a layout route catch-all?"],
             "Nested Routes & Shared Layouts (2026) — React Router Outlet",
             "Master nested routes in React Router: Outlet, layout routes, index routes, useOutletContext, and relative links."),
        ]),

        "route-guards-and-loaders": ("Route Guards & Loaders", [
            ("protected-routes-auth-react-router",
             "How do you implement protected (authenticated) routes in React Router?",
             "Protected Routes in React Router — Auth Guard Pattern",
             "default", "medium", "high", 6,
             "RequireAuth wrapper, Navigate to /login, state to remember intended URL; data-router loaders for async auth check with redirect",
             "Leaking the protected content briefly before the redirect fires — loaders (data router) let you redirect before render",
             "Show both patterns: element-based (RequireAuth wrapper) and loader-based (throw redirect()) with pros/cons",
             REACT_T,
             ["What is the loader API in React Router?",
              "How do you redirect from a loader?",
              "How do you remember the intended URL after login?",
              "Should auth logic live in a loader or a component?"],
             "Protected Routes in React Router (2026) — Auth Guards",
             "Implement protected routes in React Router: RequireAuth wrapper, loader-based redirects, intended-URL memory, and data-router patterns."),

            ("loaders-actions-data-router-apis",
             "What are loaders and actions in React Router's data-router APIs?",
             "Route Loaders & Actions — React Router Data APIs Explained",
             "default", "medium", "high", 6,
             "loader runs before rendering a route (data-prep); action handles form submissions; Form component + useSubmit; suspends rendering on loader promise",
             "Fetching in useEffect on every route render instead of using a loader — loaders parallelize and happen before render",
             "Compare to Next.js App Router data fetching; note deferred loaders for streaming + Await",
             REACT_T,
             ["What is deferred loader in React Router?",
              "How do you handle form submissions with an action?",
              "How does React Router compare to Next.js App Router?",
              "Can loaders run in parallel?"],
             "Route Loaders & Actions (2026) — React Router Data APIs",
             "Master React Router data-router APIs: loaders, actions, Form, deferred data, and parallels with Next.js App Router data fetching."),
        ]),

        "forms-controlled-vs-uncontrolled": ("Forms — Controlled vs Uncontrolled", [
            ("forms-controlled-vs-uncontrolled-refs",
             "Controlled vs uncontrolled forms in React — when to use each?",
             "Controlled vs Uncontrolled Forms in React — When to Use Each",
             "comparison", "medium", "high", 5,
             "Controlled: React state drives input; Uncontrolled: DOM holds state, read via ref on submit; performance & validation trade-offs",
             "Writing controlled inputs for every field in a 50-field form — unnecessary re-renders; React Hook Form uses uncontrolled + subscription model",
             "Recommend React Hook Form for large forms; controlled for fields with dependent logic / live validation",
             REACT_T,
             ["Why does React Hook Form use uncontrolled inputs?",
              "How do you validate on submit vs on change?",
              "How do you read uncontrolled input values?",
              "Which is faster for 100-field forms?"],
             "Controlled vs Uncontrolled Forms (2026) — React Performance",
             "Choose controlled vs uncontrolled forms in React: performance, validation, React Hook Form subscription model, and when each fits."),
        ]),

        "react-hook-form": ("React Hook Form", [
            ("react-hook-form-basics",
             "What are the basics of React Hook Form (register, handleSubmit, formState)?",
             "React Hook Form Basics — register, handleSubmit, formState",
             "default", "medium", "high", 6,
             "register for fields, handleSubmit wrapping onSubmit, formState.errors for validation UI, minimal re-render model via subscriptions",
             "Calling useWatch on the whole form in every render — subscribe to specific names to stay performant",
             "Show a typed form with register + resolver (Zod); mention useFormContext for composition",
             REACT_T,
             ["What is useFormContext?",
              "How does React Hook Form achieve minimal re-renders?",
              "How do you integrate Zod?",
              "What is Controller for?"],
             "React Hook Form Basics (2026) — register, handleSubmit",
             "Master React Hook Form: register, handleSubmit, formState, Controller, useFormContext, and Zod schema validation."),

            ("react-hook-form-with-zod-yup",
             "How do you validate forms with React Hook Form + Zod (or Yup)?",
             "React Hook Form + Zod Validation — Typed Forms with Resolver",
             "default", "medium", "high", 6,
             "Zod schema + zodResolver passed to useForm, schema-inferred types via z.infer<typeof schema>, error messages derived from schema",
             "Duplicating validation: writing Zod schema AND TypeScript types by hand — use z.infer for single source of truth",
             "Recommend Zod over Yup for better TypeScript inference and modern API; show a typed form with resolver",
             REACT_T,
             ["Is Zod better than Yup in 2026?",
              "What is zodResolver?",
              "How do you share a Zod schema with the backend?",
              "How do you show server-side errors in React Hook Form?"],
             "React Hook Form + Zod (2026) — Typed Validation Guide",
             "Validate React Hook Form with Zod: zodResolver, z.infer types, schema-driven errors, and sharing schemas between client and server."),
        ]),

        "formik-and-yup": ("Formik & Yup", [
            ("formik-vs-react-hook-form",
             "Formik vs React Hook Form — which should you use?",
             "Formik vs React Hook Form (2026) — Comparison & Recommendation",
             "comparison", "medium", "high", 5,
             "React Hook Form: uncontrolled, minimal re-renders, smaller bundle; Formik: controlled, mature, less actively maintained in 2024-2026",
             "Picking Formik for a new large app without checking its maintenance status — React Hook Form has stronger momentum",
             "Give fair trade-offs and reference the 2024 Formik maintenance situation (slower cadence)",
             REACT_T,
             ["Is Formik still maintained?",
              "Why is React Hook Form faster?",
              "Can you migrate Formik to React Hook Form?",
              "Which has better TypeScript support?"],
             "Formik vs React Hook Form (2026) — Which to Use",
             "Compare Formik and React Hook Form: controlled vs uncontrolled, performance, bundle size, TypeScript, and 2026 maintenance realities."),
        ]),

        "validation-with-zod": ("Validation with Zod", [
            ("zod-schema-validation-basics",
             "What is Zod? How does schema validation work?",
             "Zod Schema Validation Basics — TypeScript-First Validation",
             "default", "medium", "high", 6,
             "TypeScript-first schemas, z.infer for type inference, .parse / .safeParse, transforms, refinements, discriminated unions",
             "Using .parse (throws) in hot paths where .safeParse would be safer and return a discriminated result",
             "Mention Zod v4 perf improvements, reuse across client/server, tRPC integration",
             REACT_T,
             ["What is the difference between parse and safeParse?",
              "How does z.infer work?",
              "What is a discriminated union in Zod?",
              "Can you share Zod schemas between frontend and backend?"],
             "Zod Schema Validation Basics (2026) — TypeScript-First",
             "Master Zod: TypeScript-first schemas, parse vs safeParse, z.infer, discriminated unions, transforms, and reuse across client/server."),

            ("zod-vs-yup-vs-joi",
             "Zod vs Yup vs Joi — which should you use in 2026?",
             "Zod vs Yup vs Joi (2026) — TypeScript, Bundle, Performance",
             "comparison", "medium", "medium", 5,
             "Zod: best TS inference; Yup: mature but weaker TS; Joi: server-focused, large bundle; Zod dominates modern frontends",
             "Choosing Joi in the browser — it's larger and Node-focused; Zod is smaller and TS-first",
             "Mention Valibot as a smaller newer alternative for bundle-sensitive frontends",
             REACT_T,
             ["What is Valibot?",
              "Which has the best TypeScript inference?",
              "Is Yup still a good choice?",
              "How big is Zod's bundle?"],
             "Zod vs Yup vs Joi (2026) — Comparison and Recommendation",
             "Compare Zod, Yup, Joi (and Valibot): TypeScript inference, bundle size, performance, and the right 2026 choice."),
        ]),

        "file-upload-handling": ("File Upload Handling", [
            ("file-upload-react-formdata-progress",
             "How do you handle file uploads in React (FormData, progress, multipart)?",
             "File Upload in React — FormData, Progress & Multipart",
             "default", "medium", "high", 6,
             "<input type=file>, FormData, XHR for upload progress (Fetch lacks it), multipart/form-data; backend multipart handling",
             "Using Fetch for file uploads and wondering why upload progress doesn't work — Fetch doesn't expose upload progress yet",
             "Show XHR-based upload with progress; mention axios onUploadProgress; reference resumable upload libs (tus, Uppy)",
             REACT_T,
             ["Why doesn't Fetch support upload progress?",
              "How does axios show upload progress?",
              "What is tus?",
              "How do you validate file size client-side?"],
             "File Upload in React (2026) — FormData, Progress, Multipart",
             "Upload files in React: FormData, multipart/form-data, XHR/axios progress events, and resumable uploads with tus/Uppy."),
        ]),

        "scenario-based": ("Scenario-Based", []),
    },

    # -----------------------------------------------------------------------
    # M22 react-performance-patterns (11 topics, 13 Qs)
    # -----------------------------------------------------------------------
    "react-performance-patterns": {
        "reconciliation-and-keys": ("Reconciliation & Keys", [
            ("react-reconciliation-fiber",
             "What is React's reconciliation (Fiber) algorithm?",
             "React Reconciliation (Fiber) — How React Updates the DOM",
             "default", "hard", "high", 8,
             "Fiber architecture (rebranded from stack), work units, incremental rendering, priority lanes (React 18), diffing by type + key",
             "Saying React always re-renders the whole tree — it only re-renders matched subtrees and commits minimal DOM changes",
             "Mention React 18's concurrent rendering, priority lanes, and time-slicing; link to useTransition",
             REACT_T,
             ["What are priority lanes in React 18?",
              "How does React 18 time-slice work?",
              "What is concurrent rendering?",
              "What happens if keys change?"],
             "React Reconciliation (Fiber) Explained (2026) — How It Works",
             "Master React reconciliation: Fiber architecture, work units, priority lanes (React 18), time-slicing, and the diffing algorithm."),

            ("react-keys-and-index-as-key-pitfall",
             "Why do React keys matter? What are the pitfalls of using array index as a key?",
             "React Keys Explained — Why Index as Key Is a Bug",
             "default", "medium", "high", 6,
             "Keys identify items across renders; stable keys preserve component state; index changes when list reorders, causing wrong state mapping",
             "Using the array index as a key for a sortable/filterable list — state attaches to position, not item",
             "Show a classic bug: reversing a list with index keys causes input values to stick to positions instead of items",
             REACT_T,
             ["When is array index OK as a key?",
              "What happens when a key changes?",
              "Can you use the item's object reference as a key?",
              "How do React DevTools help debug keys?"],
             "React Keys & Index-as-Key Pitfall (2026) — Why Stable Keys",
             "Master React keys: stable identity, state preservation, and the classic index-as-key bug — plus safe patterns."),
        ]),

        "memoization-memo-and-usememo": ("Memoization — memo & useMemo", [
            ("react-memo-vs-usememo-vs-usecallback",
             "React.memo vs useMemo vs useCallback — which does what?",
             "React.memo vs useMemo vs useCallback — Differences & Use Cases",
             "comparison", "medium", "high", 7,
             "React.memo wraps a component (props equality); useMemo caches a value; useCallback caches a function; all use dep arrays",
             "Adding React.memo to every component — without stable props, memo does nothing except add comparison overhead",
             "Mention React Compiler (2024) auto-memoizes; default rule: don't memoize until profiler shows benefit",
             REACT_T,
             ["What is the React Compiler?",
              "Why doesn't React.memo help with unstable object props?",
              "How does prop comparison work in React.memo?",
              "Can you combine React.memo with useCallback?"],
             "React.memo vs useMemo vs useCallback (2026) — Full Guide",
             "Master React.memo, useMemo, and useCallback: differences, dep arrays, React Compiler, and profiler-first memoization strategy."),

            ("when-memoization-hurts-react-perf",
             "When can memoization actually HURT React performance?",
             "When Memoization Hurts React Performance — Common Bugs",
             "default", "medium", "medium", 5,
             "Dep comparison cost, stale values, memory overhead, deep-equal checks, unstable deps that change every render",
             "Deep-equaling objects in React.memo's equality function — the check can cost more than the render",
             "Share profiler workflows (React DevTools Profiler, Chrome Performance), and stress 'measure first'",
             REACT_T,
             ["How do you use the React DevTools Profiler?",
              "What happens when deps change every render?",
              "Is memoization worth it for small components?",
              "When does deep-equal comparison hurt?"],
             "When Memoization Hurts React Performance (2026) — Bugs",
             "Know when React memoization hurts: deep-equal costs, unstable deps, memory, and profiler-first guidance."),
        ]),

        "code-splitting-and-lazy": ("Code Splitting & React.lazy", [
            ("react-lazy-suspense-code-splitting",
             "How does React.lazy + Suspense enable code splitting?",
             "React.lazy + Suspense — Route & Component Code Splitting",
             "default", "medium", "high", 5,
             "Dynamic import() + React.lazy returns a lazy component; Suspense renders fallback until chunk loads; Error Boundary for failures",
             "Forgetting an Error Boundary around React.lazy — a failed chunk load crashes the app silently",
             "Show route-based splitting with React Router, and chunk-prefetching on hover for perceived speed",
             REACT_T,
             ["How do you prefetch a lazy chunk?",
              "Can you code-split a component without a route?",
              "How does chunk failure work in React.lazy?",
              "What's a named import with React.lazy?"],
             "React.lazy + Suspense (2026) — Route & Component Splitting",
             "Master React.lazy and Suspense: dynamic imports, route-based splitting, prefetch, and Error Boundary for failed chunks."),
        ]),

        "virtualization-and-windowing": ("Virtualization & Windowing", [
            ("react-list-virtualization-react-window",
             "How do you virtualize a huge list in React (react-window, react-virtual)?",
             "List Virtualization in React — react-window & TanStack Virtual",
             "default", "medium", "high", 6,
             "Only render visible items + a small buffer; dramatically reduces DOM node count; libraries: react-window, react-virtualized, TanStack Virtual",
             "Rendering 10,000 items to the DOM and trying to fix jank with memoization — virtualization is the right tool",
             "Recommend TanStack Virtual (framework-agnostic, modern) over react-window for new code",
             REACT_T,
             ["What is TanStack Virtual?",
              "How does dynamic row height work?",
              "Why is virtualization often better than pagination?",
              "How does virtualization interact with accessibility?"],
             "List Virtualization in React (2026) — react-window & TanStack",
             "Virtualize huge React lists: react-window, TanStack Virtual, dynamic row heights, and accessibility considerations."),
        ]),

        "render-optimization": ("Render Optimization", [
            ("common-react-perf-pitfalls-inline-objects",
             "What are common React performance pitfalls? (inline objects, unstable functions, context churn)",
             "Common React Performance Pitfalls — Inline Props, Context Churn",
             "default", "medium", "high", 6,
             "New object/array/function on every render as a prop, large Context values, unkeyed lists, unnecessary re-renders",
             "Fixing perf by memoizing every component instead of identifying the offending prop or context",
             "Workflow: profile → find dropped-frame roots → fix root cause (often a single unstable prop); then memoize if still needed",
             REACT_T,
             ["How do you profile a slow React app?",
              "What causes context-consumer churn?",
              "Why do inline objects break React.memo?",
              "How do you find the root cause of a slow render?"],
             "React Performance Pitfalls (2026) — Profiler-First Fixes",
             "Fix common React perf bugs: inline objects, unstable functions, context churn, and profiler-first root-cause analysis."),
        ]),

        "higher-order-components": ("Higher-Order Components", [
            ("higher-order-components-hoc-react",
             "What are Higher-Order Components (HOCs) in React? Give an example.",
             "Higher-Order Components (HOCs) in React — With Examples",
             "default", "medium", "medium", 5,
             "Function taking a component and returning a wrapped component; used pre-hooks for cross-cutting concerns; largely replaced by hooks",
             "Writing new HOCs in 2026 — hooks are the preferred primitive; HOCs still appear in legacy and some libraries (connect, withRouter)",
             "Recognize HOCs in the wild (Redux connect, withAuth); but prefer custom hooks for new code",
             REACT_T,
             ["Why have HOCs fallen out of fashion?",
              "How does Redux connect use HOCs?",
              "How do you pass TypeScript generics through a HOC?",
              "What is a render-prop component?"],
             "Higher-Order Components in React (2026) — Legacy & Libraries",
             "Understand Higher-Order Components in React: examples, trade-offs, library legacy (connect, withRouter), and hooks as the modern alternative."),
        ]),

        "render-props": ("Render Props", [
            ("render-props-pattern-react",
             "What is the render-props pattern in React?",
             "Render Props Pattern in React — With Examples",
             "default", "medium", "medium", 4,
             "A prop whose value is a function that returns JSX; enables sharing behavior without inheritance; popular pre-hooks",
             "Preferring render props for new code in 2026 — hooks express the same patterns more ergonomically",
             "Identify patterns still using render props (some chart and auth libs) and how to migrate to hooks",
             REACT_T,
             ["Are render props still used?",
              "How do render props compare to HOCs?",
              "How do render props compare to hooks?",
              "What is the children-as-a-function pattern?"],
             "Render Props Pattern in React (2026) — When It's Still Used",
             "Understand the render-props pattern in React: examples, legacy code recognition, and migration to hooks."),
        ]),

        "compound-components": ("Compound Components", [
            ("compound-components-pattern-tabs",
             "What are compound components? Show a Tabs example.",
             "Compound Components in React — Tabs Pattern Explained",
             "default", "medium", "medium", 5,
             "Parent manages shared state via Context; children communicate implicitly; ergonomic declarative API (Tabs, TabList, Tab, TabPanel)",
             "Using prop-drilling between a Tabs parent and each Tab — Context cleanly expresses the implicit relationship",
             "Link to headless-UI libraries (Radix, Headless UI, Ark UI) that popularized this pattern",
             REACT_T,
             ["What are headless UI libraries?",
              "How does Radix use the compound-components pattern?",
              "How do you type compound components in TypeScript?",
              "When is compound components overkill?"],
             "Compound Components in React (2026) — Tabs Pattern",
             "Master compound components in React: shared Context, declarative API, and headless libraries like Radix UI and Headless UI."),
        ]),

        "provider-and-container-patterns": ("Provider & Container Patterns", [
            ("provider-container-presentational-react",
             "What are the Provider and container/presentational patterns in React?",
             "Provider & Container/Presentational Patterns — React Architecture",
             "default", "medium", "medium", 5,
             "Provider: wraps subtree with Context/Redux; Container/Presentational: split logic from UI (container has state, presentational is dumb)",
             "Insisting on strict container/presentational split everywhere — hooks let containers and presentation coexist cleanly in one component",
             "Note that container/presentational was popular with class components; hooks make it largely optional",
             REACT_T,
             ["Are container components still useful in 2026?",
              "How do hooks replace the container pattern?",
              "What is a Provider component?",
              "How do you compose multiple Providers?"],
             "Provider & Container/Presentational Patterns (2026)",
             "Understand React's Provider and container/presentational patterns: historical context, hooks-era relevance, and Provider composition."),
        ]),

        "scenario-based": ("Scenario-Based", [
            ("optimize-slow-react-list",
             "How do you optimize a slow list in React?",
             "Optimize a Slow React List — Profiler, Keys, Virtualization",
             "default", "medium", "high", 7,
             "Profiler to find slow commits, stable keys, memoize list item, virtualize for large N, avoid inline handlers, batch updates",
             "Memoizing before profiling — often adds complexity without measurable gain",
             "Ordered playbook: (1) Profile, (2) stable keys, (3) memoize item, (4) virtualize, (5) defer non-urgent with useTransition",
             REACT_T,
             ["How do you use the React DevTools Profiler?",
              "Why are stable keys critical for list perf?",
              "When is useTransition useful for lists?",
              "What is the flashing-re-render debug trick?"],
             "Optimize a Slow React List (2026) — Step-by-Step Playbook",
             "Speed up slow React lists: profiler, stable keys, item memoization, virtualization (TanStack Virtual), and useTransition."),
        ]),

        "comparisons": ("Comparisons", [
            ("hocs-vs-render-props-vs-hooks",
             "HOCs vs Render Props vs Hooks — how did React pattern evolution go?",
             "HOCs vs Render Props vs Hooks (2026) — Evolution of React Patterns",
             "comparison", "medium", "medium", 5,
             "Each solves cross-cutting code reuse; HOCs (wrapper hell), render props (callback hell), hooks (composable, flat)",
             "Starting a new project with HOCs or render props — hooks are the modern default and ergonomics are better",
             "Show the same reusable 'useAuth' logic expressed three ways, and why hooks win on composition",
             REACT_T,
             ["Why do hooks win over HOCs?",
              "When might you still write a HOC?",
              "What is wrapper hell?",
              "What's the hook equivalent of a render prop?"],
             "HOCs vs Render Props vs Hooks (2026) — Pattern Evolution",
             "Understand the evolution from HOCs to render props to hooks in React: wrapper hell, composition, and the modern recommendation."),
        ]),
    },

    # -----------------------------------------------------------------------
    # M23 react-testing (8 topics, 7 Qs)
    # -----------------------------------------------------------------------
    "react-testing": {
        "jest-fundamentals": ("Jest Fundamentals", [
            ("jest-basics-describe-it-expect",
             "What are the basics of Jest — describe, it/test, expect?",
             "Jest Basics — describe, it, expect, Matchers",
             "default", "easy", "high", 5,
             "Test tree (describe/it), expect with matchers, beforeEach/afterEach, mocks (jest.fn / jest.spyOn), coverage",
             "Putting logic inside describe without an it block — describe is for grouping, not assertions",
             "Mention Vitest as a fast Jest-compatible alternative now preferred in Vite/Vue ecosystems",
             REACT_T,
             ["What is Vitest?",
              "What's the difference between toBe and toEqual?",
              "How do you mock a module in Jest?",
              "How do snapshot tests work?"],
             "Jest Basics (2026) — describe, it, expect, Matchers",
             "Master Jest basics: describe, it/test, expect matchers, beforeEach/afterEach, mocks, and Vitest as the modern alternative."),
        ]),

        "react-testing-library": ("React Testing Library", [
            ("react-testing-library-philosophy",
             "What is the philosophy of React Testing Library? Test like a user.",
             "React Testing Library Philosophy — Test Like a User",
             "default", "easy", "high", 5,
             "Query by accessible role/text/label (how users find); avoid testing implementation details; fire user events with userEvent",
             "Using getByTestId everywhere — a signal that a11y-first queries are being bypassed; prefer role/label queries",
             "Recommend userEvent v14 over fireEvent for realistic user interactions; waitFor for async UI changes",
             REACT_T,
             ["Why avoid getByTestId?",
              "What is userEvent v14?",
              "What is waitFor for?",
              "How do you query a button by label?"],
             "React Testing Library Philosophy (2026) — Test Like a User",
             "Master RTL's philosophy: accessibility-first queries, avoid implementation-detail tests, userEvent v14, and waitFor for async UI."),

            ("rtl-queries-getby-queryby-findby",
             "What is the difference between getBy, queryBy, and findBy queries in RTL?",
             "RTL Queries — getBy vs queryBy vs findBy Explained",
             "comparison", "easy", "high", 4,
             "getBy: throws if missing; queryBy: returns null if missing (use for absence assertions); findBy: async, waits then resolves or throws",
             "Using getBy for an element that appears asynchronously — immediately throws; use findBy",
             "Pair queryBy with expect(...).not.toBeInTheDocument(); use findBy for async UI",
             REACT_T,
             ["When do you use queryBy over getBy?",
              "What async helper does findBy use under the hood?",
              "What is the -All variant of each?",
              "Which query is best for assertions?"],
             "RTL Queries getBy vs queryBy vs findBy (2026) — Differences",
             "Choose RTL queries: getBy (throws), queryBy (absence checks), findBy (async) with common assertion patterns."),
        ]),

        "testing-hooks-and-context": ("Testing Hooks & Context", [
            ("testing-custom-hooks-renderhook",
             "How do you test custom hooks with renderHook?",
             "Testing Custom Hooks with renderHook — React Testing Library",
             "default", "medium", "medium", 5,
             "renderHook from @testing-library/react (v13+ merged), act() for state updates, wrapper for Context providers",
             "Forgetting act() around state-updating calls — triggers act-warning and can leak state between tests",
             "Show a useCounter test and a Context-wrapped hook test (wrapper: ({children}) => <Provider>...</Provider>)",
             REACT_T,
             ["What is act() for?",
              "How do you test a hook that uses Context?",
              "Can you test async hooks with renderHook?",
              "Why is renderHook now in @testing-library/react?"],
             "Testing Custom Hooks with renderHook (2026) — Guide",
             "Test custom hooks with renderHook: act() wrapping, Context providers, async hooks, and @testing-library/react integration."),
        ]),

        "mocking-fetch-and-modules": ("Mocking Fetch & Modules", [
            ("mocking-fetch-modules-msw-jest",
             "How do you mock fetch and modules in React tests? Why is MSW recommended?",
             "Mocking Fetch & Modules in React Tests — Jest, MSW, vi.mock",
             "default", "medium", "high", 6,
             "jest.mock / vi.mock for module mocking, MSW (Mock Service Worker) for network mocking at the fetch layer — closer to real",
             "Mocking fetch globally with jest.fn — brittle and duplicates production logic; MSW intercepts at the network layer",
             "Recommend MSW for API mocks in tests AND browser dev; mention its Node server mode for Jest/Vitest",
             REACT_T,
             ["What is MSW?",
              "How does MSW compare to jest.mock?",
              "Can you use MSW in Storybook?",
              "What is vi.mock (Vitest)?"],
             "Mocking Fetch & Modules in React Tests (2026) — MSW, Jest",
             "Master API mocking in React tests: jest.mock/vi.mock for modules and MSW for fetch/network — why MSW is the modern best practice."),
        ]),

        "snapshot-testing": ("Snapshot Testing", [
            ("snapshot-testing-when-useful-harmful",
             "When is snapshot testing useful vs harmful in React?",
             "Snapshot Testing in React — When It Helps and When It Hurts",
             "default", "medium", "medium", 4,
             "Useful for stable output (config files, small pure components); harmful for large components (false positives, noisy diffs)",
             "Snapshot-testing a whole page component — any small change cascades noisy diffs and developers blind-update",
             "Prefer behavior-based RTL assertions over UI snapshots; use inline snapshots for small focused checks",
             REACT_T,
             ["What is an inline snapshot?",
              "Why are snapshot tests considered brittle?",
              "When are snapshots actually useful?",
              "How do you review a snapshot diff?"],
             "Snapshot Testing in React (2026) — When It Helps, When It Hurts",
             "Use snapshot testing wisely in React: inline snapshots for small pieces, avoid whole-component snapshots, and prefer RTL behavior assertions."),
        ]),

        "e2e-with-playwright": ("E2E with Playwright", [
            ("playwright-vs-cypress-e2e",
             "Playwright vs Cypress for E2E testing — which should you use?",
             "Playwright vs Cypress (2026) — E2E Testing Comparison",
             "comparison", "medium", "high", 6,
             "Playwright: multi-browser, multi-tab, cross-language; Cypress: single-origin limitation historically, great DX; 2026 both strong",
             "Dismissing Cypress without knowing it added multi-origin support in v12 and 14; both are viable in 2026",
             "Include fair comparison: Playwright has edge on parallelism and browser coverage; Cypress has edge on real-time reload + debugging UX",
             REACT_T,
             ["Does Cypress support multi-origin?",
              "Which is faster for large suites?",
              "What are component tests?",
              "Can Playwright replace unit tests?"],
             "Playwright vs Cypress (2026) — E2E Testing Comparison",
             "Compare Playwright vs Cypress for E2E: multi-browser, multi-origin, parallelism, DX, and component testing."),
        ]),

        "e2e-with-cypress": ("E2E with Cypress", []),
        "scenario-based": ("Scenario-Based", []),
    },
}
