"""Upgrade M27 Docker module to System Design quality bar.

For each existing Q: inject `architecture_diagram` (Mermaid) + `tradeoffs` section.
For empty folders (comparisons, scenario-based): write fresh new SEO/interview Qs.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from upgrade_helper import insert_sections, write_topic_file

ROOT = os.path.join(os.path.dirname(__file__), "..", "content", "java-backend-intermediate", "docker")


# ============================================================================
# 1. docker-fundamentals (5 Qs)
# ============================================================================
fundamentals_upgrades = {
    "jvm-memory-docker-container-limits": {
        "diagram": {
            "title": "Where the JVM's Memory Goes Inside a 512Mi Container",
            "content": "The JVM's resident memory is **far more than the heap**. Below is the breakdown for a typical Spring Boot app and where each region lives relative to the container limit.\n\n```mermaid\nflowchart TB\n    subgraph Container[\"Container memory limit: 512Mi\"]\n        subgraph Heap[\"Heap (-XX:MaxRAMPercentage=75% \u2248 384Mi)\"]\n            Y[Young Gen<br/>Eden + Survivor]\n            O[Old Gen<br/>Tenured]\n        end\n        subgraph NonHeap[\"Non-heap (\u2248 128Mi headroom)\"]\n            M[Metaspace<br/>~100-150Mi]\n            T[Thread stacks<br/>1Mi \u00d7 N threads]\n            C[Code cache<br/>~50Mi]\n            G[GC bookkeeping<br/>~20Mi]\n            D[Direct buffers<br/>NIO / Netty]\n        end\n    end\n    K[Kernel cgroup]\n    K -.OOMKill SIGKILL.-> Container\n    style Heap fill:#e8f5e9\n    style NonHeap fill:#fff3e0\n```\n\nIf `-Xmx` equals the container limit, **non-heap regions push total RSS above the cgroup ceiling** and the kernel kills the process before the JVM can react."
        },
        "tradeoffs": {
            "title": "Trade-offs and Production Tuning",
            "content": "**`MaxRAMPercentage` higher = more heap, less GC pressure, but less safety margin.** 75% is the standard. Going to 85% reduces minor GC frequency but leaves only 15% for non-heap \u2014 a Spring Boot app with Hibernate, multiple thread pools, and many loaded classes will exceed this and OOMKill.\n\n**Going lower than 50% wastes memory** \u2014 you paid for 1Gi of container memory but the heap only uses 500Mi; the extra is wasted unless your app has unusually heavy non-heap usage (lots of NIO direct buffers, very large class graphs).\n\n**`-Xmx` vs `MaxRAMPercentage`.** Fixed `-Xmx` is fine if you control both the container limit and the JVM flags together (Kubernetes deployment with both pinned). Percentage-based scales automatically when you change the container limit \u2014 better for environments where ops adjusts limits without coordinating with dev.\n\n**Container support pre-JDK 8u191 vs modern JVMs.** On JDK 8u131\u2013u190 you must add `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap`. JDK 8u191+ and JDK 11+ enable container support by default. Always verify with `java -XshowSettings:vm -version` inside the container which heap size the JVM actually sees.\n\n**G1 GC vs ZGC vs Shenandoah inside small containers.** G1 is the safe default for 1\u20138Gi heaps. ZGC and Shenandoah have lower pause times but consume more native memory \u2014 inside a 512Mi container, ZGC's metadata overhead can eat 50\u201380Mi extra, leaving even less headroom. Use G1 for small containers; reach for ZGC only when heap is \u22654Gi and pause time matters."
        },
    },
    "docker-volumes-named-vs-bind-mounts": {
        "diagram": {
            "title": "How Named Volumes, Bind Mounts, and tmpfs Sit on the Host",
            "content": "Each mount type lives in a different place on the host and has a different lifecycle relative to the container.\n\n```mermaid\nflowchart LR\n    subgraph Host[\"Host machine\"]\n        VOL[/var/lib/docker/volumes/<br/>postgres_data/]\n        BIND[/Users/dev/myapp/src/<br/>any host path]\n        TM[RAM only<br/>tmpfs - never on disk]\n    end\n    subgraph C[\"Container\"]\n        P1[/var/lib/postgresql/data]\n        P2[/app/src]\n        P3[/run/secrets]\n    end\n    VOL -.docker-managed.-> P1\n    BIND -.host-path projection.-> P2\n    TM -.kernel memory.-> P3\n    style VOL fill:#e3f2fd\n    style BIND fill:#fff3e0\n    style TM fill:#fce4ec\n```\n\n**Named volume** \u2014 Docker owns the host path; portable across machines. **Bind mount** \u2014 you specify the host path; tied to that machine. **tmpfs** \u2014 no host path at all; pure RAM."
        },
        "tradeoffs": {
            "title": "Trade-offs by Use Case",
            "content": "**Named volume vs bind mount for development.** Bind mount wins for source code (live edits, hot reload). Named volume wins for `node_modules` or `.m2/repository` on macOS/Windows because bind-mount I/O goes through a virtualized filesystem layer with major performance penalty (5\u201310x slower for many small files).\n\n**Named volume vs cloud block storage in production.** Named volumes on a single host are fine for dev/staging but a single-node failure loses the data. For real persistence, the volume driver should point to network storage (EFS, Azure Files, Ceph) or you should not put data in the container at all \u2014 use a managed database instead.\n\n**tmpfs trade-off.** Zero disk persistence is the security feature \u2014 secrets vanish on container stop. The cost is that all tmpfs allocations consume container memory and count toward the cgroup limit. Allocating a 1Gi tmpfs in a 2Gi container leaves only 1Gi for the JVM.\n\n**Read-only root + writable volumes pattern.** Best practice is `--read-only` on the container with explicit named volumes for `/tmp`, `/var/cache`, and any directory the app must write to. This stops attackers from modifying binaries or planting persistence even if they achieve code execution \u2014 a defense-in-depth measure that costs almost nothing."
        },
    },
    "docker-health-checks-spring-boot": {
        "diagram": {
            "title": "Health Check State Machine \u2014 Starting \u2192 Healthy \u2192 Unhealthy",
            "content": "Docker tracks each container in one of three health states. Transitions are driven by the HEALTHCHECK command's exit code over a sliding window of `retries` consecutive failures.\n\n```mermaid\nstateDiagram-v2\n    [*] --> Starting: container starts\n    Starting --> Starting: failures during start_period are ignored\n    Starting --> Healthy: first success after start_period\n    Healthy --> Healthy: continued successes\n    Healthy --> Unhealthy: 3 consecutive failures<br/>(retries threshold)\n    Unhealthy --> Healthy: any single success\n    Unhealthy --> [*]: orchestrator restart<br/>(K8s liveness)\n    note right of Starting: 60s grace window<br/>JVM is initializing\n    note right of Unhealthy: depends_on: service_healthy<br/>blocks dependent containers\n```\n\nThe **start_period** is the most-skipped parameter. Spring Boot needs 15\u201360s to load the context; without a grace window, Docker marks the container unhealthy before it has a chance to start."
        },
        "tradeoffs": {
            "title": "Trade-offs and Common Pitfalls",
            "content": "**Probe interval frequency.** A 5-second `interval` detects unhealthy state quickly but adds load \u2014 each call hits the database (Actuator's default `/health`). Go to 30 seconds in production unless you genuinely need fast detection (rare; the orchestrator usually decides routing on a longer cadence).\n\n**Liveness vs readiness ambiguity.** Docker has only one HEALTHCHECK; it conflates liveness and readiness. Kubernetes's split (liveness restarts, readiness routes) is the right model. If you ship to both Docker Swarm and Kubernetes, write the healthcheck to be conservative \u2014 it should fail only on true unrecoverable conditions, not transient downstream issues.\n\n**Heavy Actuator health checks.** `/actuator/health` runs every registered indicator, including database queries and Redis pings. Under heavy load this can itself trigger latency. Use `/actuator/health/liveness` (no dependency checks, just process-alive) for liveness and `/actuator/health/readiness` for readiness routing.\n\n**HEALTHCHECK in Dockerfile vs Compose.** Compose can override the Dockerfile HEALTHCHECK \u2014 useful when you want one image with environment-specific health policies (e.g., relaxed in dev, strict in prod). Always test the effective healthcheck with `docker inspect <container> | jq '.[0].Config.Healthcheck'` before assuming the Dockerfile value is in effect."
        },
    },
    "debugging-spring-boot-in-docker": {
        "diagram": {
            "title": "The Debugging Escalation Ladder",
            "content": "Start with the cheapest tool (logs) and escalate only when the lower rung does not reveal the root cause. Each step up has more diagnostic power but more risk of destabilizing the running service.\n\n```mermaid\nflowchart TB\n    A[1. docker logs / kubectl logs<br/>passive observation] --> Q1{Root cause<br/>visible?}\n    Q1 -->|Yes| Done[Resolved]\n    Q1 -->|No| B[2. docker exec / kubectl exec<br/>jstack, jcmd, env, netstat]\n    B --> Q2{Found it?}\n    Q2 -->|Yes| Done\n    Q2 -->|No| C[3. JFR / Async-profiler<br/>continuous profiling - low overhead]\n    C --> Q3{Found it?}\n    Q3 -->|Yes| Done\n    Q3 -->|No| D[4. JDWP remote debug<br/>HIGH RISK - blocks threads]\n    D --> Done\n    style A fill:#e8f5e9\n    style B fill:#fff9c4\n    style C fill:#ffe0b2\n    style D fill:#ffcdd2\n```\n\n**Skip levels at your own risk.** Reaching for JDWP when the answer is in the logs wastes everyone's time and risks outage."
        },
        "tradeoffs": {
            "title": "Trade-offs of Each Debugging Approach",
            "content": "**`kubectl exec` vs ephemeral debug containers.** `exec` works on most images but fails on distroless (no shell). `kubectl debug` attaches a sidecar with a shell to inspect a distroless pod \u2014 slightly heavier but works everywhere.\n\n**JDWP `suspend=y` vs `suspend=n`.** `suspend=y` blocks the JVM at startup until a debugger attaches \u2014 catches initialization bugs but a forgotten flag means the pod never starts in production. `suspend=n` starts immediately but can miss early-startup issues. Always use `suspend=n` outside development.\n\n**JFR (Java Flight Recorder) vs jstack thread dumps.** Thread dumps are point-in-time snapshots; JFR is a continuous low-overhead profile. For \"why is latency high under load\" use JFR with `-XX:StartFlightRecording=duration=120s,filename=/tmp/load.jfr`. For \"is the app deadlocked right now\" use two `jstack` calls 10s apart and diff them.\n\n**Heap dumps in containers.** A 4Gi heap dump takes ~30s to write and consumes equal disk space. Inside a container with a small ephemeral disk this can fill the disk and cascade to OOM eviction. Stream the dump out: `kubectl cp pod:/tmp/dump.hprof ./dump.hprof &` while the dump is still in progress, or write to a mounted volume sized for it.\n\n**Production debug safety rules.** Never enable JDWP in prod (auth-less code execution). Never run `jstack` on every pod simultaneously (each thread dump pauses the JVM briefly \u2014 doing 50 at once causes a coordinated stall). Profile one canary pod, not the fleet."
        },
    },
    "docker-container-resource-limits-jvm": {
        "diagram": {
            "title": "How CPU Throttling Bites the JVM",
            "content": "CPU limits in Linux cgroups use the CFS bandwidth controller. Inside a 100ms measurement window, the container gets a quota proportional to its limit. Once consumed, the kernel pauses execution for the rest of the window.\n\n```mermaid\nsequenceDiagram\n    participant App as App threads<br/>(8 threads)\n    participant CFS as Linux CFS scheduler\n    participant GC as G1 GC threads<br/>(parallel)\n    Note over CFS: Window starts (100ms)<br/>Container limit = 1 CPU \u2192 quota = 100ms<br/>but 8 threads can burn it in 12.5ms\n    App->>CFS: request CPU<br/>burst 50ms work\n    CFS->>App: granted (50ms used)\n    GC->>CFS: minor GC pause needed<br/>parallel GC wants 8 cores\n    CFS->>GC: granted (50ms used)\n    Note over CFS: Quota exhausted<br/>at 100ms mark\n    App->>CFS: more work\n    CFS-->>App: THROTTLED (wait 50ms)\n    Note over App,GC: 20ms minor GC \u2192 stretches to 200ms<br/>tail latency spike\n```\n\nThe fix is either **raising the CPU limit** or telling the JVM how many CPUs to count on with `-XX:ActiveProcessorCount=N` so it does not spawn 8 GC threads when only 1 CPU is available."
        },
        "tradeoffs": {
            "title": "Trade-offs and QoS Class Selection",
            "content": "**Guaranteed vs Burstable QoS.** Guaranteed (requests = limits) gives the pod the highest scheduling priority and the latest eviction order \u2014 it pays for the privilege by reserving exact resources up front, hurting cluster bin-packing. Burstable (requests < limits) packs more efficiently but pods can be throttled or evicted under pressure. Pick Guaranteed for latency-sensitive APIs, Burstable for batch/background workers.\n\n**CPU limits vs no CPU limits.** A controversial school of thought says set CPU `requests` but no CPU `limits` \u2014 the kernel only throttles under contention. This avoids the throttling-of-GC problem but breaks predictable per-pod behavior and makes capacity planning harder. The mainstream recommendation is to set limits but generously (1.5\u20132x typical usage) and monitor `cpu_throttled_periods` carefully.\n\n**Memory requests vs limits.** Always set requests = limits for memory in production. Memory cannot be reclaimed gracefully \u2014 a pod that bursts above its request gets OOMKilled the moment a higher-priority pod needs the memory. Burstable memory is acceptable only for stateless workers that recover instantly from a kill.\n\n**`ActiveProcessorCount` precision.** Set it to the **integer floor** of your CPU limit \u2014 a pod with `cpu: 1500m` should get `-XX:ActiveProcessorCount=1` (not 1.5; the JVM uses this for thread pool sizing and fractional values get rounded). For pods with sub-1-CPU limits, set it to 1 explicitly so the JVM does not detect 0 cores and refuse to start."
        },
    },
}


# ============================================================================
# 2. docker-compose (1 Q)
# ============================================================================
compose_upgrades = {
    "docker-compose-spring-boot-postgres-redis": {
        "diagram": {
            "title": "Compose Stack Topology and Startup Order",
            "content": "Compose creates a project-specific bridge network and brings up services in dependency order. With healthchecks, dependent services wait for actual readiness, not just container start.\n\n```mermaid\nflowchart TB\n    subgraph Net[\"Compose-managed bridge network: myapp_default\"]\n        subgraph PG[postgres service]\n            P[postgres:16-alpine<br/>healthcheck: pg_isready]\n            V[(named volume<br/>postgres_data)]\n            P --- V\n        end\n        subgraph RD[redis service]\n            R[redis:7-alpine<br/>healthcheck: redis-cli ping]\n        end\n        subgraph APP[app service]\n            A[Spring Boot<br/>port 8080]\n        end\n    end\n    Host[Host: localhost:8080] -->|published port| A\n    A -->|jdbc:postgresql://postgres:5432<br/>service-name DNS| P\n    A -->|spring.data.redis.host=redis| R\n    A -.depends_on:<br/>condition: service_healthy.-> P\n    A -.depends_on:<br/>condition: service_healthy.-> R\n```\n\n**Service names are DNS hostnames.** No port publishing needed for east-west traffic; only the app's 8080 is exposed to the host."
        },
        "tradeoffs": {
            "title": "Trade-offs and Production-Like Compose Setups",
            "content": "**Compose vs Kubernetes for local dev.** Compose wins on simplicity (one YAML, `up -d` and you are running). Kind/Minikube wins on parity with production (same manifests, same probes, same RBAC). For a small team or early project, Compose is fine. For a team shipping to K8s production, Kind on the laptop catches issues earlier.\n\n**`depends_on` strategies.** `condition: service_started` waits for the container process; `condition: service_healthy` waits for the healthcheck; `condition: service_completed_successfully` waits for a one-shot init container to exit. Use `service_healthy` for databases, `service_started` is almost always wrong.\n\n**Profiles vs separate compose files.** Profiles (`--profile infra`) keep one file with selective startup; multiple compose files (`-f docker-compose.yml -f docker-compose.dev.yml`) layer overrides. Profiles are cleaner for \"include or skip\" decisions; multiple files are better for environment-specific overrides (dev vs CI vs staging).\n\n**Volume persistence trap in CI.** Named volumes survive `docker compose down`. In CI you almost always want a clean slate \u2014 always use `docker compose down -v` in CI cleanup or each test run inherits state from the previous one. In dev, never use `-v` reflexively or you wipe your local database every time you restart."
        },
    },
}


# ============================================================================
# 3. docker-networking (1 Q)
# ============================================================================
networking_upgrades = {
    "docker-networking-bridge-host-overlay": {
        "diagram": {
            "title": "Bridge vs Host vs Overlay \u2014 What Each Mode Looks Like",
            "content": "The three modes differ in where the container's network stack lives and how it reaches other containers.\n\n```mermaid\nflowchart TB\n    subgraph Bridge[\"Bridge mode (default)\"]\n        BH[Host eth0]\n        BR[docker0 bridge]\n        BC1[container1<br/>veth + own NS]\n        BC2[container2<br/>veth + own NS]\n        BH --> BR\n        BR --> BC1\n        BR --> BC2\n        BC1 <-.NAT iptables.-> BR\n    end\n    subgraph Host[\"Host mode\"]\n        HH[Host eth0]\n        HC[container<br/>shares host NS]\n        HH --- HC\n    end\n    subgraph Overlay[\"Overlay (Swarm/K8s CNI)\"]\n        N1H[Node 1 eth0]\n        N2H[Node 2 eth0]\n        OC1[container A]\n        OC2[container B]\n        N1H --- OC1\n        N2H --- OC2\n        OC1 -.VXLAN tunnel<br/>UDP 4789.-> OC2\n    end\n    style Bridge fill:#e3f2fd\n    style Host fill:#fff3e0\n    style Overlay fill:#f3e5f5\n```\n\nThe more isolation, the more overhead. Host mode is fastest but exposes ports directly. Overlay enables multi-node communication at the cost of VXLAN encapsulation."
        },
        "tradeoffs": {
            "title": "Trade-offs and Network Mode Decision Rules",
            "content": "**Bridge for almost everything.** Default bridge networking on a single host with Compose-managed networks gives you DNS, isolation, and minimal overhead. Choose anything else only when you have a specific reason.\n\n**Host mode for performance-critical workloads.** Bridge NAT adds 1\u20132% overhead per packet. For 99% of apps this is invisible. For network-monitoring tools (tcpdump, Wireshark, Promtail with host log scraping), Kafka brokers under heavy load, or anything that benchmarks show is bottlenecked on networking, host mode pays. Cost: port collisions and zero network isolation.\n\n**Overlay/CNI in production.** In Docker Swarm you pick overlay explicitly. In Kubernetes the CNI plugin (Calico, Cilium, Flannel, AWS VPC CNI) handles it transparently \u2014 the differences are policy enforcement (Calico/Cilium support NetworkPolicy with eBPF), MTU tuning (VXLAN reduces effective MTU; jumbo frames need MTU 9000 minus encapsulation), and observability (Cilium's Hubble adds L7 visibility).\n\n**`--network=host` security warning.** Host mode means a container with a vulnerability can reach `localhost`-bound services on the host (databases, monitoring agents, the Docker socket if exposed) without crossing any network boundary. Combine with read-only root and dropped capabilities or do not use it.\n\n**MACVLAN/IPVLAN modes.** Less common but useful when the container needs its own MAC address on the physical network (legacy applications expecting bare-metal network identity). Adds operational complexity \u2014 only reach for it when bridge cannot meet the requirement."
        },
    },
}


# ============================================================================
# 4. docker-security (3 Qs)
# ============================================================================
security_upgrades = {
    "docker-non-root-user-java-security": {
        "diagram": {
            "title": "Defense-in-Depth Layers Around the JVM Process",
            "content": "Each hardening control closes a different escalation path. Together they reduce a successful exploit from \"root on the host\" to \"limited code execution inside the container.\"\n\n```mermaid\nflowchart TB\n    Attack[RCE in Spring Boot app<br/>e.g., deserialization vuln]\n    Attack --> L1{Running as root<br/>inside container?}\n    L1 -->|Yes| Bad1[Read all files<br/>install tools<br/>attempt escape]\n    L1 -->|No: USER appuser| L2{Read-only root FS?}\n    L2 -->|No| Bad2[Modify binaries<br/>plant persistence]\n    L2 -->|Yes| L3{Capabilities dropped?}\n    L3 -->|No| Bad3[NET_ADMIN, SYS_ADMIN<br/>raw sockets, mount]\n    L3 -->|Yes: drop ALL| L4{No-new-privileges?}\n    L4 -->|No| Bad4[setuid binary escalation]\n    L4 -->|Yes| L5{seccomp/AppArmor?}\n    L5 -->|No| Bad5[Dangerous syscalls<br/>kernel exploits]\n    L5 -->|Yes: default profile| OK[Limited blast radius:<br/>only app-level access]\n    style Attack fill:#ffcdd2\n    style OK fill:#c8e6c9\n    style Bad1 fill:#ffebee\n    style Bad2 fill:#ffebee\n    style Bad3 fill:#ffebee\n    style Bad4 fill:#ffebee\n    style Bad5 fill:#ffebee\n```\n\nAny single control can be bypassed by a determined attacker. Layering them all forces multiple bypasses to escalate \u2014 raising the cost of attack and the chance of detection."
        },
        "tradeoffs": {
            "title": "Trade-offs of Each Hardening Control",
            "content": "**Non-root vs developer convenience.** Non-root breaks workflows that assume write access to anywhere in `/`. Logging libraries that try to write to `/var/log`, scratch directories at `/tmp` (still writable on most setups), and any heap-dump path must be explicitly owned by the app user or mounted as a volume. The fix takes 30 minutes; the audit finding takes weeks to remediate when discovered late.\n\n**`readOnlyRootFilesystem` operational cost.** Spring Boot needs writable `/tmp` for Tomcat, an extracted JAR cache, and JVM crash logs. Each writable path becomes a volume mount. The benefit is enormous (attackers cannot persist anything to disk); the cost is a few extra volume declarations.\n\n**`drop: [\"ALL\"]` then add back what you need.** This is the right default. A web app needs no Linux capabilities at all. Special cases (binding to ports below 1024 without root, raw sockets for ICMP) need targeted additions \u2014 `add: [\"NET_BIND_SERVICE\"]` for port 80/443. Avoid the lazy `add: [\"ALL\"]` or `privileged: true`.\n\n**Distroless vs Alpine.** Distroless eliminates the shell entirely \u2014 attackers cannot `sh -c 'wget ...'`. The cost is debugging difficulty: `kubectl exec` gives you no shell. Pair distroless with `kubectl debug` ephemeral containers for troubleshooting. Alpine keeps the shell for `kubectl exec` convenience but accepts a slightly larger attack surface.\n\n**SecurityContext at pod vs container level.** `runAsUser` at the pod level applies to all containers; at the container level overrides per-container. Set the strict policy at the pod level; only relax for specific containers (e.g., an init container that needs root to chown a volume)."
        },
    },
    "docker-image-scanning-security-best-practices": {
        "diagram": {
            "title": "Image Security Pipeline \u2014 Scan, Sign, Verify, Run",
            "content": "Modern image security is a chain of controls running from source code to production runtime. A break anywhere in the chain leaves a gap.\n\n```mermaid\nflowchart LR\n    SRC[Source code +<br/>Dockerfile + deps] --> BUILD[CI: docker build]\n    BUILD --> SCAN1[Trivy scan<br/>fail on CRITICAL]\n    SCAN1 -->|pass| SIGN[Cosign sign<br/>with key in OIDC]\n    SIGN --> PUSH[docker push to<br/>registry]\n    PUSH --> SCAN2[Registry scan<br/>continuous, on new CVEs]\n    SCAN2 -->|alert on new CVE| REBUILD[Rebuild base image]\n    REBUILD --> BUILD\n    PUSH --> ADM[Admission controller<br/>K8s OPA / Kyverno]\n    ADM --> VER[Cosign verify<br/>reject unsigned]\n    VER --> RUN[Pod runs]\n    RUN --> RT[Runtime: Falco<br/>detect anomalies]\n    style SCAN1 fill:#fff9c4\n    style SCAN2 fill:#fff9c4\n    style SIGN fill:#c8e6c9\n    style VER fill:#c8e6c9\n    style RT fill:#bbdefb\n```\n\nCI scanning catches CVEs at build time. Registry scanning catches **newly disclosed** CVEs in already-pushed images. Signing + admission verification prevents tampered images from reaching production."
        },
        "tradeoffs": {
            "title": "Trade-offs and Practical Trade-offs",
            "content": "**Severity threshold for blocking builds.** Failing CI on CRITICAL only catches the worst issues but the queue stays manageable. Adding HIGH usually doubles the noise and creates pressure to add `.trivyignore` exceptions, which becomes a graveyard of un-reviewed CVEs. Start with CRITICAL-only, add HIGH after the team has tooling to triage.\n\n**Distroless vs minimal Alpine.** Distroless wins on security (no shell, no package manager, smaller surface). Alpine wins on debuggability and tooling (musl libc instead of glibc has subtle differences \u2014 some Java native libraries have compatibility issues). For Spring Boot, both work; pick distroless if your team has the discipline to use ephemeral debug containers.\n\n**Pinned digests vs floating tags.** Pinned digests give reproducible builds but require Dependabot/Renovate to update them \u2014 without automation, you fall behind on patches. Floating tags get patches automatically but make builds non-reproducible. The mature setup is pinned digests with weekly automated PRs to update them.\n\n**Image signing complexity.** Cosign + keyless signing via OIDC is the modern default \u2014 no key management, signatures bound to the CI workflow that produced them. The cost is admission-controller setup (Kyverno or OPA Gatekeeper) and operational maturity to handle signature failures gracefully. For early-stage teams, scanning alone is the higher-ROI control.\n\n**SBOM (Software Bill of Materials).** Generating an SBOM with Syft and storing it alongside the image is becoming a regulatory requirement (US executive order, EU CRA). Cost is small (Syft runs in seconds); benefit is fast CVE response when a new vulnerability is disclosed in a library buried deep in your dependency tree."
        },
    },
    "docker-environment-variables-vs-secrets": {
        "diagram": {
            "title": "Where Secrets Live in Each Delivery Method",
            "content": "Each method exposes the secret in a different place. The progression below shows how visibility shrinks as the method gets more secure.\n\n```mermaid\nflowchart TB\n    subgraph Dockerfile[\"ENV in Dockerfile - WORST\"]\n        D1[Image layer]\n        D2[docker inspect]\n        D3[Registry]\n        D4[Process /proc/1/environ]\n        D5[CI build cache]\n    end\n    subgraph Runtime[\"-e at runtime\"]\n        R1[docker inspect]\n        R2[Process /proc/1/environ]\n        R3[Crash dumps]\n    end\n    subgraph K8s[\"Kubernetes Secret as env var\"]\n        K1[etcd encrypted at rest]\n        K2[Process /proc/1/environ]\n        K3[Pod spec via API + RBAC]\n    end\n    subgraph KFile[\"K8s Secret as mounted file\"]\n        KF1[etcd encrypted at rest]\n        KF2[tmpfs in container]\n    end\n    subgraph Vault[\"Vault dynamic secret - BEST\"]\n        V1[Vault server]\n        V2[Per-pod 24h TTL token<br/>auto-rotated]\n    end\n    Dockerfile -.exposed in 5 places.-> Bad[5 leak surfaces]\n    Runtime -.exposed in 3 places.-> Mid[3 leak surfaces]\n    K8s -.exposed in 2-3 places.-> Better[2-3 leak surfaces]\n    KFile -.exposed in 1 place.-> Good[1 leak surface]\n    Vault -.dynamic per-pod.-> Best[0 shared secrets<br/>auto rotation]\n    style Bad fill:#ffcdd2\n    style Mid fill:#ffe0b2\n    style Better fill:#fff9c4\n    style Good fill:#c8e6c9\n    style Best fill:#a5d6a7\n```"
        },
        "tradeoffs": {
            "title": "Trade-offs and Maturity Path",
            "content": "**Env vars vs files.** Env vars leak through `/proc/<pid>/environ`, crash dumps, child process inheritance, and any logging that prints the environment. Mounted files are namespace-isolated to the container's filesystem and harder to leak accidentally. Spring Boot's `spring.config.import=optional:configtree:/run/secrets/` reads files as properties \u2014 use it.\n\n**K8s Secrets default encoding.** Out of the box, Kubernetes Secrets are only base64-encoded in etcd \u2014 not encrypted. Enable encryption at rest with an `EncryptionConfiguration` (KMS provider) before treating Secrets as actually secret. Without this, anyone with etcd read access has plaintext credentials.\n\n**Vault complexity.** Vault adds operational burden: a Vault cluster to run, sidecars or agents in every pod, auth method configuration, policy management. The payoff is dynamic credentials (per-pod, short-lived, auto-rotated). Worth it for regulated workloads (PCI, HIPAA, SOC2) or when multiple services share a database. Overkill for a small startup with one service.\n\n**External Secrets Operator (ESO) middle ground.** ESO syncs from cloud secret managers (AWS Secrets Manager, Azure Key Vault, GCP Secret Manager) into Kubernetes Secrets automatically. You get cloud-managed rotation without running Vault. The trade-off is that secrets still flow through K8s Secrets (subject to the etcd encryption caveat above) \u2014 so combine ESO with encryption at rest.\n\n**Image signing of secret-handling code.** A subtle attack: an attacker pushes a malicious image with the same name; if you do not verify signatures, your pod pulls and runs it with full secret access. Cosign verification at admission closes this hole."
        },
    },
}


# ============================================================================
# 5. multi-stage-builds (2 Qs)
# ============================================================================
multistage_upgrades = {
    "multistage-dockerfile-spring-boot": {
        "diagram": {
            "title": "Two Stages, One Dockerfile \u2014 What Ships and What Doesn't",
            "content": "The builder stage assembles the artifact; the runtime stage carries only what executes. Discarding the builder is what cuts image size from 500MB to 150MB.\n\n```mermaid\nflowchart LR\n    subgraph Builder[\"Stage 1: builder (eclipse-temurin:21-jdk-alpine ~400MB)\"]\n        B1[COPY pom.xml]\n        B2[RUN mvn dependency:go-offline]\n        B3[COPY src/]\n        B4[RUN mvn package]\n        B5[RUN java -Djarmode=layertools extract]\n        B1 --> B2 --> B3 --> B4 --> B5\n    end\n    subgraph Runtime[\"Stage 2: runtime (eclipse-temurin:21-jre-alpine ~80MB)\"]\n        R1[COPY --from=builder dependencies/]\n        R2[COPY --from=builder spring-boot-loader/]\n        R3[COPY --from=builder snapshot-dependencies/]\n        R4[COPY --from=builder application/]\n        R5[USER appuser]\n        R6[ENTRYPOINT JarLauncher]\n        R1 --> R2 --> R3 --> R4 --> R5 --> R6\n    end\n    B5 -.discarded.-> X[\u2717 builder image<br/>not pushed]\n    B5 -.only extracted layers.-> R1\n    Reg[Registry] <-.150MB push.- Runtime\n    style Builder fill:#fff3e0\n    style Runtime fill:#e8f5e9\n    style X fill:#ffcdd2\n```\n\nThe **layered extraction** is the secret to fast incremental pushes \u2014 only the 2MB application layer changes when code changes."
        },
        "tradeoffs": {
            "title": "Trade-offs and When Multi-Stage Is Overkill",
            "content": "**JIB vs Dockerfile.** JIB (Google's Maven/Gradle plugin) builds layered OCI images directly from the build tool with no Dockerfile and no Docker daemon. Faster CI builds, smaller images by default, automatic layering. Cost: less control over the image (cannot easily install custom packages or run arbitrary RUN commands). Use JIB for vanilla Spring Boot apps; use Dockerfile when you need anything custom.\n\n**Layered JAR vs single-fat-JAR.** Layered extraction adds a step and slightly complicates the Dockerfile. The payoff is incremental push speed: 2MB code change vs 200MB full JAR. Worth it for any project that pushes more than a few times a week. Skip it for one-off batch jobs.\n\n**Slim JRE vs full JRE.** `eclipse-temurin:21-jre-alpine` is ~80MB; the full Debian JRE is ~250MB. Alpine uses musl libc which has subtle differences from glibc \u2014 most Java code is fine, but any native library compiled against glibc may fail. Test thoroughly before adopting Alpine for production; if issues arise, the slim Debian variant (`eclipse-temurin:21-jre-jammy`) is a good middle ground.\n\n**`-XX:UseAppCDS` for faster startup.** Multi-stage Dockerfiles can pre-compute Class Data Sharing archives in the builder stage and copy them into the runtime stage. AppCDS cuts Spring Boot startup from 8s to 3\u20134s. Cost: extra build complexity. Worth it for serverless (cold start matters) or large fleets where startup latency aggregates.\n\n**JLink for custom JREs.** JLink builds a JRE containing only the modules your app uses \u2014 a Spring Boot app's custom JRE can be 50MB instead of 80MB. Significant savings at scale; complexity not worth it for a small handful of services."
        },
    },
    "docker-layer-caching-optimization": {
        "diagram": {
            "title": "Cache Hit vs Miss \u2014 the Cascade in Action",
            "content": "A code change ideally invalidates only the last few layers. A `COPY . .` invalidates everything below it. The cascade is what makes instruction order so consequential.\n\n```mermaid\nflowchart TB\n    subgraph Good[\"Good ordering: code change\"]\n        G1[FROM jdk:21] --> G2[COPY pom.xml<br/>HIT: pom unchanged]\n        G2 --> G3[RUN mvn dep:go-offline<br/>HIT: pom unchanged]\n        G3 --> G4[COPY src/<br/>MISS: code changed]\n        G4 --> G5[RUN mvn package<br/>MISS]\n        G4 -.30s rebuild.-> Done1[Done in 30s]\n    end\n    subgraph Bad[\"Bad ordering: same code change\"]\n        D1[FROM jdk:21] --> D2[COPY . .<br/>MISS: any file changed]\n        D2 --> D3[RUN mvn dep:go-offline<br/>MISS: cascade]\n        D3 --> D4[RUN mvn package<br/>MISS: cascade]\n        D4 -.7 min rebuild.-> Done2[Done in 7 min]\n    end\n    style G2 fill:#c8e6c9\n    style G3 fill:#c8e6c9\n    style G4 fill:#fff9c4\n    style G5 fill:#fff9c4\n    style D2 fill:#ffcdd2\n    style D3 fill:#ffcdd2\n    style D4 fill:#ffcdd2\n    style Done1 fill:#a5d6a7\n    style Done2 fill:#ef9a9a\n```\n\n**14x speedup** from instruction ordering alone. No build tool, no parallelism \u2014 just placing volatile inputs after stable ones."
        },
        "tradeoffs": {
            "title": "Trade-offs and BuildKit Features",
            "content": "**BuildKit vs classic builder.** BuildKit (default since Docker 23) parallelizes independent stages, supports cache mounts (`--mount=type=cache`), and offers better remote caching. Classic builder is single-threaded and lacks cache mounts. There is no reason to disable BuildKit on a modern setup.\n\n**Local cache vs registry-based remote cache.** Local cache is fast but lost on every CI runner. Registry-based remote cache (`--cache-to type=registry,ref=...,mode=max`) persists across CI runs but adds push/pull overhead. For CI, registry remote cache is essential \u2014 a cold-cache CI build can take 10x longer than a warm one.\n\n**`--mount=type=cache` for Maven.** `RUN --mount=type=cache,target=/root/.m2 ./mvnw package` keeps the Maven local repository between builds without bloating the final image. Even after a cache-miss layer, Maven downloads only newly required JARs instead of re-fetching everything.\n\n**Squashed layers vs preserved layers.** `docker build --squash` collapses all layers into one to reduce image size by deleting intermediate state. Cost: every code change re-pushes the entire image (no layer reuse). Almost never worth it \u2014 layered images push faster overall because of cache reuse.\n\n**Multi-arch builds (`docker buildx`).** Building for amd64 + arm64 simultaneously (Apple Silicon dev, Graviton prod) doubles build time but produces a manifest list that pulls the right arch automatically. Use BuildKit's `--platform=linux/amd64,linux/arm64` with QEMU emulation \u2014 slow on emulation, fast on native runners (use ARM CI runners for ARM builds when possible)."
        },
    },
}


# ============================================================================
# Apply all upgrades
# ============================================================================
def main():
    files = [
        ("docker-fundamentals/complete-qa.json", fundamentals_upgrades),
        ("docker-compose/complete-qa.json", compose_upgrades),
        ("docker-networking/complete-qa.json", networking_upgrades),
        ("docker-security/complete-qa.json", security_upgrades),
        ("multi-stage-builds/complete-qa.json", multistage_upgrades),
    ]
    for rel, ups in files:
        path = os.path.join(ROOT, rel)
        log = insert_sections(path, ups)
        print(f"\n=== {rel} ===")
        for slug, msg in log.items():
            print(f"  {slug}: {msg}")


if __name__ == "__main__":
    main()
