#!/usr/bin/env bash
# Heartbeat + activity-logger hook for the auto-handoff watchdog.
#
# Registered in .cursor/hooks.json against postToolUse, afterFileEdit,
# afterAgentResponse, and sessionStart events. Runs on every agent action.
#
# Responsibilities (all cheap, must finish in < 100ms typical):
#   1. Touch .cursor/handoffs/.heartbeat with the current ISO timestamp.
#   2. Append a one-line JSON record to .cursor/handoffs/.activity.jsonl
#      describing what just happened (tool, file, command, exit code).
#   3. Trim the activity log to the last 200 lines.
#   4. Regenerate .cursor/handoffs/AUTO-LATEST.md from the activity log so
#      a continuation agent always has a fresh, factual snapshot to read,
#      even if the human never typed "handoff".
#
# This hook always exits 0 and prints nothing to stdout, so it never
# interferes with the agent's normal flow. Errors go to .watchdog.log.

set -uo pipefail

# Resolve repo root from script location: .cursor/hooks/ -> ../..
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
handoffs_dir="$repo_root/.cursor/handoffs"
log_file="$handoffs_dir/.watchdog.log"

mkdir -p "$handoffs_dir"

# Read hook input JSON from stdin. Cursor sends event-specific fields here.
input="$(cat 2>/dev/null || true)"

# Best-effort extraction. We do not fail if jq cannot parse anything.
ts="$(date +%Y-%m-%dT%H:%M:%S%z)"
event="$(printf '%s' "$input" | jq -r '.hook_event_name // .event // "unknown"' 2>/dev/null)"
tool="$(printf '%s' "$input" | jq -r '.tool_name // .tool // empty' 2>/dev/null)"

# Try to capture a short, useful summary of what the tool did.
summary=""
case "$event" in
  postToolUse|preToolUse)
    case "$tool" in
      Write|Edit|StrReplace|MultiEdit)
        path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.path // .input.file_path // empty' 2>/dev/null)"
        summary="edit ${path:-?}"
        ;;
      Read)
        path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.path // empty' 2>/dev/null)"
        summary="read ${path:-?}"
        ;;
      Shell|Bash)
        cmd="$(printf '%s' "$input" | jq -r '.tool_input.command // .tool_input.cmd // empty' 2>/dev/null | head -c 160)"
        exit_code="$(printf '%s' "$input" | jq -r '.tool_response.exit_code // .tool_output.exit_code // empty' 2>/dev/null)"
        summary="shell exit=${exit_code:-?} :: ${cmd:-?}"
        ;;
      *)
        summary="${tool:-tool}"
        ;;
    esac
    ;;
  afterFileEdit)
    path="$(printf '%s' "$input" | jq -r '.file_path // .path // empty' 2>/dev/null)"
    summary="afterFileEdit ${path:-?}"
    ;;
  afterAgentResponse|afterAgentThought)
    snippet="$(printf '%s' "$input" | jq -r '.text // .content // empty' 2>/dev/null | tr '\n' ' ' | head -c 200)"
    summary="agent: ${snippet:-(empty)}"
    ;;
  sessionStart)
    summary="session start"
    ;;
  stop|sessionEnd)
    summary="session end"
    ;;
  *)
    summary="${event}"
    ;;
esac

# 1. Heartbeat (used by the watchdog to detect tab silence).
printf '%s\n' "$ts" > "$handoffs_dir/.heartbeat" 2>>"$log_file" || true

# 2. Activity log (append + trim).
printf '%s\n' "$(jq -cn --arg ts "$ts" --arg event "$event" --arg tool "$tool" --arg summary "$summary" \
  '{ts:$ts, event:$event, tool:$tool, summary:$summary}' 2>>"$log_file")" \
  >> "$handoffs_dir/.activity.jsonl" 2>>"$log_file" || true

# Trim to last 200 lines so the file does not grow forever.
if [ -f "$handoffs_dir/.activity.jsonl" ]; then
  tmp_trim="$handoffs_dir/.activity.jsonl.tmp"
  tail -n 200 "$handoffs_dir/.activity.jsonl" > "$tmp_trim" 2>>"$log_file" && \
    mv "$tmp_trim" "$handoffs_dir/.activity.jsonl"
fi

# 3. Regenerate AUTO-LATEST.md (best-effort, never blocks the hook).
auto_file="$handoffs_dir/AUTO-LATEST.md"
{
  printf -- '---\n'
  printf 'created: %s\n' "$ts"
  printf 'status: auto\n'
  printf 'task: <auto-generated from activity log; agent has not written a manual handoff>\n'
  printf 'parent_plan: None\n'
  printf 'slug: auto-latest\n'
  printf -- '---\n\n'
  printf '# Auto Handoff (rolling snapshot)\n\n'
  printf 'This file is regenerated by `.cursor/hooks/heartbeat.sh` on every agent action. It is the **fallback** snapshot the watchdog or a fresh tab uses if no manual `handoff` was saved. Treat it as a factual log of recent activity, not a curated debrief.\n\n'

  printf '## 0. How to resume in 60 seconds\n\n'
  printf -- '- Read the recent activity below to infer what the previous tab was doing.\n'
  printf -- '- If `LATEST.md` (the manual handoff) exists and is newer, prefer that one.\n'
  printf -- '- Sample the last 3 edited files (in section 2) to verify their on-disk state.\n'
  printf -- '- Then continue the most recent in-progress edit.\n\n'

  printf '## 1. Last heartbeat\n\n'
  printf -- '- Timestamp: `%s`\n\n' "$ts"

  printf '## 2. Recent activity (last 30 events, newest last)\n\n'
  printf -- '```jsonl\n'
  if [ -f "$handoffs_dir/.activity.jsonl" ]; then
    tail -n 30 "$handoffs_dir/.activity.jsonl"
  else
    printf '(no activity yet)\n'
  fi
  printf -- '```\n\n'

  printf '## 3. Files most recently touched\n\n'
  if [ -f "$handoffs_dir/.activity.jsonl" ]; then
    tail -n 100 "$handoffs_dir/.activity.jsonl" \
      | jq -r 'select(.summary | startswith("edit ") or startswith("afterFileEdit ")) | .summary' 2>/dev/null \
      | sort -u \
      | sed 's/^/- /'
  fi
  printf '\n'

  printf '## 4. Recent shell commands (last 10)\n\n'
  printf -- '```\n'
  if [ -f "$handoffs_dir/.activity.jsonl" ]; then
    tail -n 100 "$handoffs_dir/.activity.jsonl" \
      | jq -r 'select(.summary | startswith("shell ")) | .summary' 2>/dev/null \
      | tail -n 10
  fi
  printf -- '```\n\n'

  printf '## 5. Notes for the continuation agent\n\n'
  printf -- '- This snapshot was machine-generated. Numbers and paths come from real tool calls but the *intent* of the work has to be inferred from the activity log and from any open .cursor/plans/*.plan.md.\n'
  printf -- '- Before editing, run `git status` and `git diff --stat` to confirm the current tree state.\n'
  printf -- '- If you are unsure what to do next, prefer fixing the most recent failing shell command (look for `exit=non-zero` lines in section 2) before starting new work.\n'
} > "$auto_file.tmp" 2>>"$log_file"

mv "$auto_file.tmp" "$auto_file" 2>>"$log_file" || true

exit 0
