#!/usr/bin/env python3
"""
go-authored.py — fully authored sections for the highest-value Go topics.
Each question carries (question, quick, spoken, deep) — written distinctly,
the way you'd actually answer in an interview. NOT mechanical derivations.
Pattern example for panic-vs-error, slice-internals, append-growth.
"""

AUTHORED = {
"panic-vs-error": [
  # Q1
  ("When should you panic vs return an error in Go?",
   "Return an error for anything a caller could reasonably handle: missing file, bad input, failed network call. Panic for programmer bugs — an impossible state, a broken invariant, arithmetic you proved safe. Libraries should almost never panic on user input.",
   "Go splits failure into two kinds, and the choice depends on who can fix it. If the caller could do something about it — retry, show a message, fall back — return an error value. A file that doesn't exist, a request with bad input, a database that's down: those are expected failures, so (result, error) is the contract.\n\nA panic says something is wrong with the program itself. An index that should always be valid because you proved the math, a map that was initialized in the same function, a switch that handled every case — if those fail, no caller can fix it; the code is wrong. That's what panic is for.\n\nThe practical line I use: panic when the bug would be silently corrupting if continued; error when the failure is a legitimate outcome of the request. A library that panics on user input pushes its bugs into every caller's crash log — which is why well-behaved packages convert even their internal panics to errors at the package boundary.",
   "The two mechanisms are built differently, which explains the rule.\n\nAn error value is just data: a struct or a string implementing `error`. It flows through return values like any other data, gets checked explicitly, and can carry context by wrapping. Nothing about an error is special to the runtime — it's ordinary Go.\n\nA panic changes control flow. The moment `panic` executes, the current goroutine starts unwinding: each function's deferred calls run, in reverse order, until something calls `recover` or the program dies. That's a heavyweight, non-local jump — and it's exactly what makes it wrong for expected failures. If a missing file unwound your stack, every caller would need a recover block around every file operation — which is just exceptions with extra steps.\n\nSo the runtime gives errors the cheap, local, explicit path, and panics the expensive, non-local path. The cost difference is the design signal: use the cheap one for the common case. A library wrapping its panics with a deferred recover at its API boundary is converting 'programmer bug' into 'caller-visible error' — the right direction at the boundary."),
  # Q2
  ("What happens when a panic occurs?",
   "The goroutine unwinds: deferred functions run in LIFO order, then if nothing recovers, the program prints the panic value and stack trace and exits.",
   "When panic is called, the current function stops at that line. Its deferred calls run — this is the key behavior — then the caller's deferred calls, and so on up the goroutine's stack, in reverse order of how they were set up. That's LIFO: what was deferred last runs first.\n\nIf any deferred function along the way calls recover, the unwinding stops there and that function returns normally. If none does, the whole program prints the panic value with a goroutine dump and exits with a non-zero status. One goroutine's unrecovered panic kills every goroutine — the process goes down together.",
   "The unwinding order is what makes defer/recover work at all. Consider the pattern:\n\n```go\nfunc safeCall() (err error) {\n    defer func() {\n        if r := recover(); r != nil {\n            err = fmt.Errorf(\"panicked: %v\", r)\n        }\n    }()\n    doWork() // may panic\n    return nil\n}\n```\n\nWhen doWork panics, the deferred closure runs first — because it was deferred in this function — and recover grabs the panic value before the unwind escapes. If the defer were placed AFTER doWork, the panic would pass the function before the closure was registered: recover has to be set up before the dangerous call, which is why defer sits at the top of the function.\n\nThe stack trace the runtime prints is the unwind path — the panic site plus every frame it passed through. That's why panics are diagnostic gold when they're genuine bugs: the trace tells you exactly which impossible state occurred and where."),
  # Q3
  ("What is recover and where is it valid?",
   "recover() returns the panic value and stops the unwinding — but only inside a deferred function while a panic is in flight. Anywhere else it returns nil.",
   "Recover is the hatch in the middle of a panic. It only does something when called inside a deferred function during an active panic on the same goroutine: it stops the unwind, the deferred function returns normally, and the panic value is handed to you as the return of recover.\n\nCalled anywhere else — outside a defer, after the unwind finished, on a different goroutine — recover returns nil and does nothing. There is no 'check for panics' you can do proactively; you can only be the deferred function that catches one in flight.\n\nThe idiomatic use is exactly one: a package boundary. A library function that might panic internally (because of a bug or an intentional invariant check) wraps its body in a deferred recover so its callers see an error value instead of a crash. Anything more elaborate — recover as control flow — is fighting the language.",
   "Why the defer-only restriction? Because recover works by intercepting the unwind, and the unwind only runs through deferred calls. There's no stack inspection at arbitrary points, no exception object you can query — the mechanism is literally: the runtime is walking out of your function, defer gave you a callback on the way out, and recover says 'stop here, hand me the reason.'\n\nThe goroutine restriction matters in practice: a deferred recover in goroutine A cannot catch a panic in goroutine B. Each goroutine unwinds its own stack, which means code that spawns goroutines must give each one its own recover at its own boundary — usually a small wrapper function:\n\n```go\nfunc runSafely(fn func()) {\n    defer func() { if r := recover(); r != nil { log.Printf(\"worker panic: %v\", r) } }()\n    fn()\n}\n```\n\nWithout that, any panic in a worker goroutine takes down the whole server, no matter how many recovers the parent function has."),
  # Q4
  ("Does panic in one goroutine crash the whole program?",
   "Yes. An unrecovered panic in any goroutine terminates the entire process — all goroutines die together. Each goroutine needs its own recover at its own boundary.",
   "It does, and this surprises people who expect exception-like isolation. Go's runtime does not try to unwind other goroutines or isolate the failure — the process exits. Every goroutine, including the main one and every in-flight request, dies immediately.\n\nThe consequence is a rule for real services: any goroutine you spawn gets its own deferred recover at its own boundary. The parent's recover doesn't cover the child — they're separate stacks. If a server accepts a connection and handles it in a goroutine, that handler needs a top-level recover that converts panics into a 500 (or at least a logged crash of that one request) rather than taking down the whole server with it.",
   "Mechanically, each goroutine has its own stack and unwind is per-stack. When goroutine B panics, the runtime unwinds B's stack; when it runs out without finding a recover, there is nothing else to do safely — the other goroutines are in arbitrary states, possibly holding locks mid-operation, and the runtime has no safe way to pause and clean them. Exit is the only honest option.\n\nThat's the deep reason the goroutine-recover pattern exists: the only code that can catch a goroutine's panic is code inside that goroutine. Libraries like net/http actually do this for you in the request handler — http.Handler panics are recovered per-connection and turned into a closed connection — which is why a nil-map write in one HTTP handler doesn't kill your whole web server. Know where your runtime draws that boundary for you and where you must draw it yourself."),
  # Q5
  ("Is panic/recover Go's exception handling?",
   "No. Errors are values, returned and checked explicitly. Panic/recover is a crash mechanism with a recovery hatch for boundaries. Using panic for control flow defeats Go's explicit error design.",
   "It looks like try/catch if you squint, but it isn't. Exceptions are a control-flow primitive: any frame can throw, any ancestor catches, and the compiler weaves the propagation through every call. Go's error path is none of that — an error is a return value, visible in the signature, checked at the call site with `if err != nil`. The propagation is the explicit return chain, not the runtime's unwinding.\n\nPanic/recover exists for the other kind of failure: the program is wrong. It's a crash mechanism — with a hatch so boundaries can convert the crash into a value. That's why the idioms never overlap: you don't catch panics the way you catch exceptions, and you don't use errors for impossible states.\n\nThe tell that they're different: in exception languages, adding a throw to a function changes nothing in the signature — callers find out at runtime. In Go, a function that can fail says so in its return type, and the compiler makes you deal with the error before using the result. The visibility is the design, and panic/recover deliberately doesn't have it.",
   "The design difference shows up in what each mechanism costs the reader. With exceptions, any call might throw anything — safety requires knowing the exception hierarchy, and the failure path is invisible at the call site. With Go errors, the failure path is the part after the `if` — you can read a function and see exactly which calls can fail and what happens then.\n\nThat's also why recover-as-control-flow is an anti-pattern: it reinstates the invisible control flow Go was designed to avoid, but with worse ergonomics than exceptions (no type-based dispatch, one-shot recover, defer-only placement). The Go standard library's own usage is the calibration: panics in the runtime for genuine invariant violations (nil map write, index out of range), errors for everything a caller could face, recover only at package boundaries like http's per-connection handler. When the standard library uses a mechanism sparingly, that's the target."),
],

"slice-internals-len-cap": [
  # Q1
  ("What are len and cap of a slice in Go, and how are they related?",
   "len is how many elements the slice can see right now; cap is how many slots exist in the backing array. Appends below cap never allocate; at cap, append reallocates and roughly doubles.",
   "A slice is a header with three fields: a pointer to the start of its elements, a length, and a capacity. The length is what you iterate over — `for i := 0; i < len(s); i++` and what `range` covers. The capacity is the size of the underlying array from the slice's start — the total room the slice can grow into before the runtime has to move it.\n\nThey differ the moment you re-slice: `t := s[:2]` on a 3-element slice gives len 2 but cap 3, because the backing array still has that third slot. That gap is exactly what append exploits — appending to t writes into the spare slot in place.\n\nWhen len reaches cap, the next append allocates a new, larger backing array (roughly double for small slices), copies the elements, and the slice header now points at the new storage. Old aliases to the previous array don't see the growth — they've forked.",
   "The len/cap split exists because slices are windows over arrays, not owned storage. The backing array is a fixed-size allocation; the slice header is a lens over it:\n\n```\ns := make([]int, 2, 4)\n\nbacking array: [ _ _ _ _ ]   (4 slots allocated)\ns: ptr ──▶ [ 0 0 ]           len 2 — what s can see\n                          cap 4 — total room from ptr\n```\n\nEvery slice operation is defined on these two numbers. Indexing checks against len (index 2 of len-2 slice panics even though slot 2 physically exists). Append checks against cap. Re-slicing recomputes both within the cap budget: `s[2:4]` on a cap-4 slice is legal even for a len-2 slice, because the window arithmetic works on the underlying array's extent.\n\nThis is also why cap is a performance property and len is a correctness property: exceeding len is a bug the runtime catches (panic); exceeding cap is just an allocation the runtime handles. Code that pre-sizes with `make([]T, 0, n)` is aligning cap with the expected len so the appends never pay the copy."),
  # Q2
  ("What is the internal structure of a Go slice?",
   "Three words: a pointer to the backing array's start, the length, and the capacity. Copying a slice copies this header — the elements stay shared.",
   "At the machine level a slice is a small struct — pointer, length, capacity — passed around by value. The elements live elsewhere, in a separate array the header points into. That's the whole trick behind slice behavior.\n\nWhen you assign or pass a slice, those three words get copied. The new header has the same pointer, so both slices view the same elements — a write through one is visible through the other. When you append and there's capacity spare, the write goes into that shared array, and any slice with a window over the slot sees it.\n\nThis is why slice behavior feels inconsistent to newcomers: assignment shares, but growth forks. It's not inconsistent — it's a pointer-with-bounds that grows by getting a new pointer. Every surprise is one of those two facts surfacing.",
   "You can watch the header be three words with unsafe or with the reflect package, but the behavior demonstrates it more usefully:\n\n```go\ns := []int{1, 2, 3}\nt := s                // header copied — same backing array\nt[0] = 100\nfmt.Println(s[0])      // 100 — shared storage\n\nu := append(s, 4)     // s is at cap (3/3): must reallocate\ns[0] = 200\nfmt.Println(u[0])      // 100 — u forked to new storage\n```\n\nThe first print shows sharing (header copy, same pointer). The second shows forking: append at capacity allocated a new array, copied the elements, and returned a header pointing at the new one. s's header still points at the old array, so s[0] = 200 doesn't touch u.\n\nThis is also the mechanism behind Q1's len/cap facts and every 'why did my slice change' bug in Go — they're all header semantics. The array itself never moves until an append forces it; only headers are copied, and only growth reallocates."),
  # Q3
  ("How does append grow a slice internally?",
   "If len < cap, append writes into the spare slot — no allocation. At len == cap, it allocates a bigger array (~2x small slices), copies, and returns the new header. The result must be reassigned.",
   "Append has exactly two modes. With capacity spare, it's a store: write the element at index len, bump len, return the same header. No allocation, no copy — and critically, every slice sharing that backing array sees the change.\n\nAt capacity, append grows: allocate a new array (roughly double the current capacity for small slices — a 3-cap slice grows to 6), copy the existing elements over, append the new one, and return a header pointing at the new storage. The old array is abandoned — slices still viewing it are now forked and won't see the new element or any future changes.\n\nBecause append can go either way, its return value is the only reliable handle: `s = append(s, x)`. When growth happened, the returned header points at the new array; ignoring the return keeps using the old, stale header and silently drops elements.",
   "The doubling strategy is the classic amortized-constant trick from dynamic arrays: appending n elements with naive 1-slot growth costs O(n²) total copies; doubling means each element is copied O(1) times on average. Go tapers the factor for very large slices (where 2x over-allocates gigabytes) but small slices get ~2x.\n\nYou can observe both modes with cap prints:\n\n```go\ns := make([]int, 0, 3)      // cap 3 from the start\ns = append(s, 1)           // fits: cap still 3\ns = append(s, 2)           // fits: cap still 3\ns = append(s, 3)           // fits exactly: cap still 3\ns = append(s, 4)           // full: new array, cap now 6\nfmt.Println(len(s), cap(s)) // 4 6\n```\n\nThe gotcha this mechanism creates: append below capacity mutates shared state. `t := s[:2]; t = append(t, 42)` writes into s's backing array if the slot exists — s sees a changed element it never touched. That's not a bug in append; it's the in-place mode doing exactly what it's for. The fix when sharing isn't wanted is a real copy (`make + copy` or `append(nil, s...)`), which forces the allocate-mode behavior on purpose."),
  # Q4
  ("Why does printing a slice show different values than expected after a sub-slice and append?",
   "Because a sub-slice shares the backing array. t := s[:2]; append(t, 42) writes 42 into the third slot of the SAME array — s sees [1 2 42] even though you never touched s directly.",
   "This is the single most common Go data bug, and it's always the same mechanism. `t := s[:2]` creates a new header pointing at the same array — len 2, cap still 3, so there's a spare slot. `append(t, 42)` has capacity available, so it takes the in-place path: write 42 at index 2, bump t's len to 3.\n\nIndex 2 of the backing array is s's third element. s still has len 3, so when you print it, the runtime shows the array — which now contains 42. You never called append on s, never assigned s anywhere — but s changed, because s was never a copy. It was a window, and the write happened through another window onto the same room.\n\nThe fix when this is unwanted: give t its own storage before appending — `t := make([]T, len, cap); copy(t, s[:2])`, or the idiom `append([]T(nil), s[:2]...)` — so append's growth-or-in-place decision happens on t's own array, not s's.",
   "The step-by-step trace makes it permanent:\n\n```\ns := []int{1, 2, 3}\n\nt := s[:2]\n// backing: [1 2 3]\n// s: ptr→0, len 3, cap 3\n// t: ptr→0, len 2, cap 3   ← same array, shorter window\n\nt = append(t, 42)\n// len 2 < cap 3 → in-place: backing[2] = 42\n// t: ptr→0, len 3, cap 3\n// backing is now [1 2 42]\n\nfmt.Println(s)  // [1 2 42] ← s's len-3 window over the mutated array\n```\n\nThe sub-slice's cap reaching beyond its len is what makes this possible — the runtime allows appending up to cap without reallocating, and cap extends to the end of the underlying array, not to the sub-slice's cut-off point.\n\nThis is the mechanism at the center of Go's most famous aliasing bug reports: two views over one array, one grows in place, the other observes the write. Understanding this one trace — and knowing the make+copy escape hatch — is the practical difference between using slices and being surprised by them."),
  # Q5
  ("What is the zero value of a slice and what operations work on it?",
   "nil. You can len it (0), range it (no iterations), append to it (allocates), and delete-free operations are fine. Only indexing panics — and writing to a nil map's sibling panic is different: nil slice writes work via append.",
   "A declared-but-unassigned slice is nil — the header's pointer is null, len and cap zero. But unlike a nil map, which panics on writes, a nil slice is mostly usable:\n\nlen(nil-slice) is 0, cap is 0. Ranging over it executes zero iterations — loop bodies just don't run. Append works, and it's not a special case: appending to a zero-cap slice takes the allocate path (there's no room), so `var s []int; s = append(s, x)` behaves exactly like starting from `[]int{}`. JSON marshals it as null (that's the visible difference from an empty-but-non-nil slice, and it matters for APIs).\n\nWhat you cannot do: index into it — `s[0]` on a nil slice panics with index out of range, same as any over-index. And functions that check `if s == nil` for emptiness will distinguish nil from empty; for most purposes `len(s) == 0` is the correct emptiness test because it covers both.",
   "The nil slice's usability is a deliberate design choice — it makes the accumulate idiom work without initialization:\n\n```go\nvar results []string\nfor _, r := range raw {\n    if keep(r) {\n        results = append(results, clean(r))\n    }\n}\n// no make() needed up front; nil grows on first append\n```\n\nCompare the map: `var m map[string]int; m[\"k\"] = 1` panics (assignment to entry in nil map) because a map needs its hash structure initialized by make before any write can find a bucket. A slice's structure is the header itself — three words, all validly zero — and the backing array only needs to exist once there's something to store, which is exactly when append allocates it.\n\nThe nil vs empty distinction surfaces at boundaries: `json.Marshal(nil)` gives `null`, `json.Marshal([]int{})` gives `[]` — API consumers notice. `len(s) == 0` treats both as empty, which is almost always what logic wants. Reserve `s == nil` for the rare case where the distinction is the signal (an absent field vs a present-but-empty list)."),
],
}
